#!/usr/bin/env bash
# 3d.tcl — portiert nach shell
# Quelle: tcl, Projects@abstractions:tcl/3d.tcl
# Erzeugt: 2026-08-18 durch ABSTRACTIONS_MANAGER.py

set -euo pipefail

# 3d.html — portiert nach bash
# Quelle: html, Projects@secret-vault-public:public/3d.html
# Erzeugt: 2026-08-09 durch ABSTRACTIONS_MANAGER.py

# Bash 5 script to generate 3d.html
# This script creates the HTML file programmatically

generate_html() {
    local filename="$1"
    
    {
        # Write DOCTYPE and html tag
        echo "<!DOCTYPE html>"
        echo "<html lang=\"de\">"
        
        # Write head section
        write_head
        
        # Write body section
        write_body
        
        # Close html tag
        echo "</html>"
    } > "$filename"
}

write_head() {
    echo "<head>"
    echo "<meta charset=\"utf-8\">"
    echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
    echo "<title>Secret-Vault Public — Interaktive Architektur</title>"
    echo "<meta name=\"description\" content=\"Vom Passwort zur verschlüsselten Datei — jede Schicht bleibt im Browser. Drehen, zoomen, Knoten auswählen.\">"
    echo "<meta name=\"theme-color\" content=\"#5b5bd6\">"
    
    # Write CSS styles
    write_styles
    
    echo "</head>"
}

write_styles() {
    echo "<style>"
    echo "  :root{"
    echo "    --bg:#fbfaf7; --panel:#fff; --line:#e6e3dc; --text:#16191d; --muted:#5f6773;"
    echo "    --ac:#5b5bd6; --buehne:#0e1420; --buehne-line:#1d2739;"
    echo "    color-scheme: light;"
    echo "  }"
    echo "  @media (prefers-color-scheme: dark){"
    echo "    :root{ --bg:#0f1115; --panel:#171a21; --line:#262b36; --text:#f2f4f8; --muted:#9aa3b2;"
    echo "           color-scheme: dark; }"
    echo "  }"
    echo "  *{box-sizing:border-box}"
    echo "  body{margin:0;background:var(--bg);color:var(--text);"
    echo "       font:15px/1.55 -apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,sans-serif}"
    echo "  .wrap{max-width:1240px;margin:0 auto;padding:34px 22px 60px}"
    echo "  .technik{font-size:12px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;"
    echo "           color:var(--ac);margin:0 0 10px}"
    echo "  h1{font-size:clamp(30px,5vw,52px);line-height:1.05;margin:0 0 14px;letter-spacing:-.03em}"
    echo "  .lede{font-size:16.5px;color:var(--muted);max-width:62ch;margin:0 0 26px}"
    echo "  .raster{display:grid;grid-template-columns:minmax(0,1fr) 288px;gap:18px;align-items:start}"
    echo "  @media (max-width:880px){ .raster{grid-template-columns:1fr} }"
    echo "  .buehne{position:relative;background:var(--buehne);border-radius:14px;overflow:hidden;"
    echo "          min-height:520px;aspect-ratio:16/11}"
    echo "  .buehne canvas{display:block;width:100%;height:100%}"
    echo "  .knoepfe{position:absolute;top:14px;right:14px;display:flex;gap:8px;z-index:2}"
    echo "  button{font:inherit;font-size:14px;font-weight:650;padding:9px 14px;border-radius:9px;"
    echo "         border:1px solid var(--line);background:var(--panel);color:var(--text);cursor:pointer}"
    echo "  button:hover{border-color:var(--ac)}"
    echo "  button[aria-pressed=\"true\"]{background:var(--ac);border-color:var(--ac);color:#fff}"
    echo "  .karte{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:20px}"
    echo "  .karte h2{font-size:11px;font-weight:700;letter-spacing:.09em;text-transform:uppercase;"
    echo "            color:var(--muted);margin:0 0 12px}"
    echo "  .karte h3{font-size:23px;margin:0 0 4px;letter-spacing:-.02em}"
    echo "  .karte .sub{color:var(--muted);margin:0 0 18px;font-size:14.5px}"
    echo "  .feld{border-top:1px solid var(--line);padding:12px 0 0;margin:0 0 12px}"
    echo "  .feld dt{font-size:11px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;"
    echo "           color:var(--muted);margin:0 0 3px}"
    echo "  .feld dd{margin:0;font-weight:650}"
    echo "  .blaettern{display:flex;gap:8px;margin-top:16px}"
    echo "  .blaettern button{flex:1;text-align:center;line-height:1.25;padding:11px 8px}"
    echo "  .legende{display:flex;gap:22px;flex-wrap:wrap;margin:16px 0 0;font-size:13.5px;color:var(--muted)}"
    echo "  .legende span{display:inline-flex;align-items:center;gap:9px}"
    echo "  .strich{width:30px;height:0;border-top-width:3px;border-top-style:solid;display:inline-block}"
    echo "  .fuss{margin:14px 0 0;font-size:13px;color:var(--muted);max-width:80ch}"
    echo "  .fehler{padding:40px;text-align:center;color:var(--muted)}"
    echo "  a{color:var(--ac)}"
    echo "</style>"
}

write_body() {
    echo "<body>"
    echo "<div class=\"wrap\">"
    
    echo ""
    echo "  <p class=\"technik\">three.js · r128</p>"
    echo "  <h1>Secret-Vault Public</h1>"
    echo "  <p class=\"lede\">Vom Passwort zur verschlüsselten Datei — jede Schicht bleibt im Browser. Drehen, zoomen, Knoten auswählen.</p>"
    echo ""
    echo "  <div class=\"raster\">"
    echo "    <div class=\"buehne\" id=\"buehne\">"
    echo "      <div class=\"knoepfe\">"
    echo "        <button id=\"btn-plus\" title=\"Näher\">+</button>"
    echo "        <button id=\"btn-minus\" title=\"Weiter weg\">−</button>"
    echo "        <button id=\"btn-reset\">Zurücksetzen</button>"
    echo "        <button id=\"btn-iso\" aria-pressed=\"true\" title=\"Isometrisch oder perspektivisch\">Iso</button>"
    echo "      </div>"
    echo "    </div>"
    echo ""
    echo "    <aside class=\"karte\">"
    echo "      <h2>Ausgewählter Knoten</h2>"
    echo "      <h3 id=\"k-name\">—</h3>"
    echo "      <p class=\"sub\" id=\"k-sub\">Knoten anklicken oder durchblättern</p>"
    echo "      <dl class=\"feld\"><dt>Schicht</dt><dd id=\"k-schicht\">—</dd></dl>"
    echo "      <dl class=\"feld\"><dt>ID</dt><dd id=\"k-id\">—</dd></dl>"
    echo "      <div class=\"blaettern\">"
    echo "        <button id=\"btn-prev\">←<br>Vorheriger</button>"
    echo "        <button id=\"btn-next\">Nächster<br>→</button>"
    echo "      </div>"
    echo "    </aside>"
    echo "  </div>"
    echo ""
    echo "  <div class=\"legende\" id=\"legende\"></div>"
    echo "  <p class=\"fuss\">Schematische Dokumentationsansicht — Blockgrößen messen weder Datenmenge noch Leistung. Keine Telemetrie, keine Fernabfragen: Die Seite lädt einmalig three.js vom CDN und rechnet danach ausschließlich lokal.</p>"
    echo ""
    echo "</div>"
    
    # Write script tags
    write_scripts
    
    echo "</body>"
}

write_scripts() {
    echo "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js\"></script>"
    echo "<script>"
    echo "(function(){"
    echo "  \"use strict\";"
    echo "  var SPEC = {\"schichten\": [{\"name\": \"Eingaben\", \"farbe\": \"#5f6773\", \"blocks\": [{\"id\": \"passphrase\", \"name\": \"Passphrase\", \"untertitel\": \"nie gespeichert\"}, {\"id\": \"vault-datei\", \"name\": \"Vault-Datei\", \"untertitel\": \"Ciphertext\"}, {\"id\": \"neue-felder\", \"name\": \"neue Felder\", \"untertitel\": \"Formular\"}]}, {\"name\": \"Schluesselableitung\", \"farbe\": \"#2481cc\", \"blocks\": [{\"id\": \"pbkdf2-210k\", \"name\": \"PBKDF2 210k\", \"untertitel\": \"Iterationen\"}, {\"id\": \"salt-16-b\", \"name\": \"Salt 16 B\", \"untertitel\": \"zufaellig\"}, {\"id\": \"sha-256\", \"name\": \"SHA-256\", \"untertitel\": \"HMAC\"}]}, {\"name\": \"Verschluesselung\", \"farbe\": \"#5b5bd6\", \"blocks\": [{\"id\": \"aes-256-gcm\", \"name\": \"AES-256-GCM\", \"untertitel\": \"authentisiert\"}, {\"id\": \"iv-12-b\", \"name\": \"IV 12 B\", \"untertitel\": \"nie doppelt\"}, {\"id\": \"crypto-subtle\", \"name\": \"crypto.subtle\", \"untertitel\": \"WebCrypto\"}]}, {\"name\": \"Verwaltung\", \"farbe\": \"#b45309\", \"blocks\": [{\"id\": \"anbieter\", \"name\": \"Anbieter\", \"untertitel\": \"Gruppen\"}, {\"id\": \"felder\", \"name\": \"Felder\", \"untertitel\": \"Schluessel/Wert\"}, {\"id\": \"rotation\", \"name\": \"Rotation\", \"untertitel\": \"neuer Wert\"}]}, {\"name\": \"Ausgabe\", \"farbe\": \"#22a06b\", \"blocks\": [{\"id\": \"download\", \"name\": \"Download\", \"untertitel\": \"Blob-URL\"}, {\"id\": \"export\", \"name\": \"Export\", \"untertitel\": \"JSON\"}, {\"id\": \"zwischenablage\", \"name\": \"Zwischenablage\", \"untertitel\": \"nur auf Klick\"}]}], \"kanten\": [{\"von\": \"passphrase\", \"nach\": \"pbkdf2-210k\", \"art\": \"fluss\"}, {\"von\": \"vault-datei\", \"nach\": \"salt-16-b\", \"art\": \"fluss\"}, {\"von\": \"neue-felder\", \"nach\": \"sha-256\", \"art\": \"fluss\"}, {\"von\": \"pbkdf2-210k\", \"nach\": \"aes-256-gcm\", \"art\": \"fluss\"}, {\"von\": \"salt-16-b\", \"nach\": \"iv-12-b\", \"art\": \"fluss\"}, {\"von\": \"sha-256\", \"nach\": \"crypto-subtle\", \"art\": \"fluss\"}, {\"von\": \"aes-256-gcm\", \"nach\": \"anbieter\", \"art\": \"fluss\"}, {\"von\": \"iv-12-b\", \"nach\": \"felder\", \"art\": \"fluss\"}, {\"von\": \"crypto-subtle\", \"nach\": \"rotation\", \"art\": \"fluss\"}, {\"von\": \"anbieter\", \"nach\": \"download\", \"art\": \"fluss\"}, {\"von\": \"felder\", \"nach\": \"export\", \"art\": \"fluss\"}, {\"von\": \"rotation\", \"nach\": \"zwischenablage\", \"art\": \"fluss\"}], \"kantenarten\": [{\"art\": \"fluss\", \"farbe\": \"#5b5bd6\", \"stil\": \"voll\", \"text\": \"Fluss von unten nach oben\"}]};"
    echo ""
    echo "  var buehne = document.getElementById(\"buehne\");"
    echo "  if (typeof THREE === \"undefined\"){"
    echo "    buehne.insertAdjacentHTML(\"beforeend\","
    echo "      '<div class=\"fehler\">three.js konnte nicht geladen werden. ' +"
    echo "      'Die Seite braucht einmalig Netzzugang zum CDN.</div>');"
    echo "    return;"
    echo "  }"
    echo ""
    echo "  // ---------------------------------------------------------------- Szene ---"
    echo "  var szene = new THREE.Scene();"
    echo "  szene.background = new THREE.Color(0x0e1420);"
    echo "  var renderer = new THREE.WebGLRenderer({antialias:true});"
    echo "  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));"
    echo "  buehne.appendChild(renderer.domElement);"
    echo ""
    echo "  var D = 26, radius = 82, aspekt = 1;"
    echo "  var kameraIso = new THREE.OrthographicCamera(-D, D, D, -D, 0.1, 600);"
    echo "  var kameraPersp = new THREE.PerspectiveCamera(42, 1, 0.1, 600);"
    echo "  var kamera = kameraIso, iso = true;"
    echo ""
    echo "  szene.add(new THREE.AmbientLight(0xffffff, 0.66));"
    echo "  var licht = new THREE.DirectionalLight(0xffffff, 0.8);"
    echo "  licht.position.set(30, 46, 26); szene.add(licht);"
    echo "  var gegen = new THREE.DirectionalLight(0x8ea2ff, 0.3);"
    echo "  gegen.position.set(-32, 16, -28); szene.add(gegen);"
    echo ""
    echo "  var raster = new THREE.GridHelper(110, 34, 0x25324a, 0x1a2333);"
    echo "  raster.position.y = -24; szene.add(raster);"
    echo ""
    echo "  // ------------------------------------------------------------ Schilder ---"
    echo "  // Text auf eine Textur, dann als Billboard — bleibt bei jeder Drehung lesbar."
    echo "  function schild(text, unter){"
    echo "    var c = document.createElement(\"canvas\"), x = c.getContext(\"2d\");"
    echo "    var f1 = \"700 40px -apple-system,Segoe UI,Roboto,sans-serif\";"
    echo "    var f2 = \"500 27px -apple-system,Segoe UI,Roboto,sans-serif\";"
    echo "    x.font = f1; var w1 = x.measureText(text).width;"
    echo "    x.font = f2; var w2 = unter ? x.measureText(unter).width : 0;"
    echo "    var w = Math.ceil(Math.max(w1, w2)) + 40, h = unter ? 96 : 62;"
    echo "    c.width = w; c.height = h;"
    echo "    x = c.getContext(\"2d\");"
    echo "    x.fillStyle = \"rgba(255,255,255,.95)\";"
    echo "    if (x.roundRect){ x.beginPath(); x.roundRect(0,0,w,h,13); x.fill(); }"
    echo "    else x.fillRect(0,0,w,h);"
    echo "    x.fillStyle = \"#16191d\"; x.font = f1; x.textBaseline = \"middle\";"
    echo "    x.fillText(text, 20, unter ? 32 : 31);"
    echo "    if (unter){ x.fillStyle = \"#5f6773\"; x.font = f2; x.fillText(unter, 20, 68); }"
    echo "    var t = new THREE.CanvasTexture(c); t.minFilter = THREE.LinearFilter;"
    echo "    var s = new THREE.Sprite(new THREE.SpriteMaterial({map:t, transparent:true, depthTest:false}));"
    echo "    s.scale.set(w/62*2.5, h/62*2.5, 1);"
    echo "    s.renderOrder = 999;"
    echo "    return s;"
    echo "  }"
    echo ""
    echo "  // -------------------------------------------------------------- Aufbau ---"
    echo "  var BW = 7.4, BD = 4.2, BH = 1.7, LUFT = 1.3, ABSTAND = 11.4, START = -17;"
    echo "  var knoten = [], nachId = {}, klickbar = [];"
    echo "  var gruppe = new THREE.Group();"
    echo ""
    echo "  SPEC.schichten.forEach(function(sch, si){"
    echo "    var y = START + si * ABSTAND;"
    echo "    var bl = sch.blocks.map(function(b){"
    echo "      return (typeof b === \"string\") ? {id:null, name:b, untertitel:\"\"} : b;"
    echo "    });"
    echo "    var spalten = Math.max(1, Math.ceil(bl.length / 2));"
    echo "    var reihen = bl.length <= 1 ? 1 : 2;"
    echo "    var gx = spalten*BW + (spalten-1)*LUFT, gz = reihen*BD + (reihen-1)*LUFT;"
    echo ""
    echo "    var platte = new THREE.Mesh("
    echo "      new THREE.BoxGeometry(gx+3, 0.6, gz+3),"
    echo "      new THREE.MeshLambertMaterial({color:new THREE.Color(sch.farbe).multiplyScalar(0.4)}));"
    echo "    platte.position.set(0, y-1.7, 0); gruppe.add(platte);"
    echo ""
    echo "    bl.forEach(function(b, i){"
    echo "      var sp = i % spalten, re = Math.floor(i / spalten);"
    echo "      var x = -gx/2 + BW/2 + sp*(BW+LUFT), z = -gz/2 + BD/2 + re*(BD+LUFT);"
    echo "      var mat = new THREE.MeshLambertMaterial({color:sch.farbe});"
    echo "      var m = new THREE.Mesh(new THREE.BoxGeometry(BW, BH, BD), mat);"
    echo "      m.position.set(x, y, z);"
    echo "      gruppe.add(m); klickbar.push(m);"
    echo "      var kante = new THREE.LineSegments(new THREE.EdgesGeometry(m.geometry),"
    echo "        new THREE.LineBasicMaterial({color:0x0e1420, transparent:true, opacity:.55}));"
    echo "      kante.position.copy(m.position); gruppe.add(kante);"
    echo ""
    echo "      var s = schild(b.name, b.untertitel);"
    echo "      s.position.set(x, y + BH/2 + (b.untertitel ? 2.1 : 1.6), z);"
    echo "      gruppe.add(s);"
    echo ""
    echo "      var id = b.id || (b.name.toLowerCase().replace(/[^a-z0-9]+/g, \"-\").replace(/^-|-\$/g, \"\"));"
    echo "      var eintrag = {id:id, name:b.name, untertitel:b.untertitel||\"\", schicht:sch.name,"
    echo "                     mesh:m, mat:mat, farbe:new THREE.Color(sch.farbe), pos:m.position};"
    echo "      m.userData.index = knoten.length;"
    echo "      knoten.push(eintrag); nachId[id] = eintrag;"
    echo "    });"
    echo "  });"
    echo ""
    echo "  // -------------------------------------------------------------- Kanten ---"
    echo "  var STIL = {};"
    echo "  (SPEC.kantenarten || []).forEach(function(a){ STIL[a.art] = a; });"
    echo ""
    echo "  (SPEC.kanten || []).forEach(function(k){"
    echo "    var a = nachId[k.von], b = nachId[k.nach];"
    echo "    if (!a || !b) return;"
    echo "    var art = STIL[k.art] || {farbe:\"#8ea2ff\", stil:\"voll\"};"
    echo "    var g = new THREE.BufferGeometry().setFromPoints(["
    echo "      a.pos.clone().setY(a.pos.y + 0.9), b.pos.clone().setY(b.pos.y - 0.9)]);"
    echo "    var linie;"
    echo "    if (art.stil === \"gestrichelt\"){"
    echo "      linie = new THREE.Line(g, new THREE.LineDashedMaterial("
    echo "        {color:art.farbe, dashSize:1.4, gapSize:1.0, transparent:true, opacity:.9}));"
    echo "      linie.computeLineDistances();"
    echo "    } else {"
    echo "      linie = new THREE.Line(g, new THREE.LineBasicMaterial("
    echo "        {color:art.farbe, transparent:true, opacity:.85}));"
    echo "    }"
    echo "    gruppe.add(linie);"
    echo "  });"
    echo ""
    echo "  szene.add(gruppe);"
    echo ""
    echo "  var leg = document.getElementById(\"legende\");"
    echo "  (SPEC.kantenarten || []).forEach(function(a){"
    echo "    var s = document.createElement(\"span\");"
    echo "    s.innerHTML = '<i class=\"strich\" style=\"border-top-color:' + a.farbe +"
    echo "                  ';border-top-style:' + (a.stil === \"gestrichelt\" ? \"dashed\" : \"solid\") +"
    echo "                  '\"></i>' + a.text;"
    echo "    leg.appendChild(s);"
    echo "  });"
    echo ""
    echo "  // ------------------------------------------------------------- Auswahl ---"
    echo "  var aktiv = -1;"
    echo "  function waehle(i){"
    echo "    if (aktiv >= 0){"
    echo "      knoten[aktiv].mat.color.copy(knoten[aktiv].farbe);"
    echo "      knoten[aktiv].mat.emissive.setHex(0x000000);"
    echo "      knoten[aktiv].mesh.scale.set(1,1,1);"
    echo "    }"
    echo "    aktiv = ((i % knoten.length) + knoten.length) % knoten.length;"
    echo "    var k = knoten[aktiv];"
    echo "    k.mat.emissive.setHex(0x333333);"
    echo "    k.mesh.scale.set(1.1, 1.5, 1.1);"
    echo "    document.getElementById(\"k-name\").textContent = k.name;"
    echo "    document.getElementById(\"k-sub\").textContent = k.untertitel || \"—\";"
    echo "    document.getElementById(\"k-schicht\").textContent = k.schicht;"
    echo "    document.getElementById(\"k-id\").textContent = k.id;"
    echo "  }"
    echo ""
    echo "  var strahl = new THREE.Raycaster(), zeiger = new THREE.Vector2();"
    echo "  renderer.domElement.addEventListener(\"click\", function(e){"
    echo "    if (gezogen) return;"
    echo "    var r = renderer.domElement.getBoundingClientRect();"
    echo "    zeiger.x = ((e.clientX - r.left) / r.width) * 2 - 1;"
    echo "    zeiger.y = -((e.clientY - r.top) / r.height) * 2 + 1;"
    echo "    strahl.setFromCamera(zeiger, kamera);"
    echo "    var treffer = strahl.intersectObjects(klickbar, false);"
    echo "    if (treffer.length) waehle(treffer[0].object.userData.index);"
    echo "  });"
    echo "  document.getElementById(\"btn-prev\").addEventListener(\"click\", function(){ waehle(aktiv - 1); });"
    echo "  document.getElementById(\"btn-next\").addEventListener(\"click\", function(){ waehle(aktiv + 1); });"
    echo ""
    echo "  // ------------------------------------------------------------- Kamera ----"
    echo "  var azimut = Math.PI/4, elevation = 0.62, rotiert = true;"
    echo "  function stelle(){"
    echo "    var x = radius*Math.cos(elevation)*Math.sin(azimut);"
    echo "    var y = radius*Math.sin(elevation);"
    echo "    var z = radius*Math.cos(elevation)*Math.cos(azimut);"
    echo "    kamera.position.set(x, y, z); kamera.lookAt(0, 0, 0);"
    echo "  }"
    echo "  var zieht = false, gezogen = false, lx = 0, ly = 0;"
    echo "  renderer.domElement.addEventListener(\"pointerdown\", function(e){"
    echo "    zieht = true; gezogen = false; lx = e.clientX; ly = e.clientY;"
    echo "  });"
    echo "  window.addEventListener(\"pointermove\", function(e){"
    echo "    if (!zieht) return;"
    echo "    if (Math.abs(e.clientX-lx) + Math.abs(e.clientY-ly) > 3){ gezogen = true; rotiert = false; }"
    echo "    azimut -= (e.clientX - lx) * 0.006;"
    echo "    elevation = Math.max(0.08, Math.min(1.45, elevation + (e.clientY - ly) * 0.005));"
    echo "    lx = e.clientX; ly = e.clientY;"
    echo "  });"
    echo "  window.addEventListener(\"pointerup\", function(){ zieht = false; setTimeout(function(){ gezogen = false; }, 0); });"
    echo ""
    echo "  function zoom(f){"
    echo "    if (iso){ D = Math.max(11, Math.min(54, D * f)); groesse(); }"
    echo "    else { radius = Math.max(32, Math.min(160, radius * f)); }"
    echo "  }"
    echo "  document.getElementById(\"btn-plus\").addEventListener(\"click\", function(){ zoom(0.85); });"
    echo "  document.getElementById(\"btn-minus\").addEventListener(\"click\", function(){ zoom(1.18); });"
    echo "  renderer.domElement.addEventListener(\"wheel\", function(e){"
    echo "    e.preventDefault(); zoom(e.deltaY > 0 ? 1.08 : 0.93);"
    echo "  }, {passive:false});"
    echo "  document.getElementById(\"btn-reset\").addEventListener(\"click\", function(){"
    echo "    azimut = Math.PI/4; elevation = 0.62; D = 26; radius = 82; rotiert = true;"
    echo "    iso = true; kamera = kameraIso;"
    echo "    document.getElementById(\"btn-iso\").setAttribute(\"aria-pressed\", \"true\");"
    echo "    document.getElementById(\"btn-iso\").textContent = \"Iso\";"
    echo "    waehle(0); groesse();"
    echo "  });"
    echo "  document.getElementById(\"btn-iso\").addEventListener(\"click\", function(){"
    echo "    iso = !iso; kamera = iso ? kameraIso : kameraPersp;"
    echo "    this.setAttribute(\"aria-pressed\", String(iso));"
    echo "    this.textContent = iso ? \"Iso\" : \"Persp\";"
    echo "    groesse();"
    echo "  });"
    echo ""
    echo "  function groesse(){"
    echo "    var w = buehne.clientWidth, h = buehne.clientHeight;"
    echo "    aspekt = w / h;"
    echo "    kameraIso.left = -D*aspekt; kameraIso.right = D*aspekt;"
    echo "    kameraIso.top = D; kameraIso.bottom = -D; kameraIso.updateProjectionMatrix();"
    echo "    kameraPersp.aspect = aspekt; kameraPersp.updateProjectionMatrix();"
    echo "    renderer.setSize(w, h, false);"
    echo "  }"
    echo "  window.addEventListener(\"resize\", groesse);"
    echo ""
    echo "  groesse();"
    echo "  waehle(0);"
    echo "  (function schleife(){"
    echo "    requestAnimationFrame(schleife);"
    echo "    if (rotiert) azimut += 0.003;"
    echo "    stelle();"
    echo "    renderer.render(szene, kamera);"
    echo "  })();"
    echo "})();"
    echo "</script>"
}

# Main execution
if [ $# -ne 1 ]; then
    echo "Usage: $0 <output-file>" >&2
    exit 1
fi

output_file="$1"
generate_html "$output_file"
echo "Generated $output_file"
