#!/bin/bash
# globals.css — portiert nach shell
# Quelle: css, Onboarding@main:app/globals.css
# Erzeugt: 2026-08-09 durch ABSTRACTIONS_MANAGER.py

set -euo pipefail

# Prüfe, ob ein Dateiname übergeben wurde
if [[ $# -ne 1 ]]; then
    echo "Verwendung: $0 <ausgabedatei>" >&2
    exit 1
fi

ausgabedatei="$1"

# Erzeuge die CSS-Datei
{
    echo '@import "tailwindcss";'
    echo
    echo ':root {'
    echo '  --bg: #faf8f4;'
    echo '  --surface: #ffffff;'
    echo '  --surface-2: #f1eee7;'
    echo '  --ink: #1b1a17;'
    echo '  --ink-2: #3c3a34;'
    echo '  --muted: #6e6a61;'
    echo '  --line: #e5e1d8;'
    echo '  --line-strong: #d4cfc3;'
    echo '  --accent: #a8542f;'
    echo '  --accent-press: #8e4526;'
    echo '  --accent-tint: #f1e5dd;'
    echo '  --on-accent: #ffffff;'
    echo '  --accent-2: #2e7d7b;'
    echo '  --accent-2-press: #225e5b;'
    echo '  --accent-3: #c77d2e;'
    echo '  --footer-bg: #191815;'
    echo '  --footer-fg: #efeae0;'
    echo '  --footer-muted: #9a958a;'
    echo '  --success: #2e7d5b;'
    echo '  --danger: #9e3f32;'
    echo '  --font-display: "Iowan Old Style", "Palatino Linotype", Georgia, "Times New Roman", serif;'
    echo '  --font-sans: "Segoe UI", Inter, system-ui, -apple-system, sans-serif;'
    echo '  --font-mono: "Cascadia Code", "SFMono-Regular", Consolas, ui-monospace, monospace;'
    echo '  --space-1: 0.25rem;'
    echo '  --space-2: 0.5rem;'
    echo '  --space-3: 0.75rem;'
    echo '  --space-4: 1rem;'
    echo '  --space-5: 1.25rem;'
    echo '  --space-6: 1.5rem;'
    echo '  --space-8: 2rem;'
    echo '  --space-10: 2.5rem;'
    echo '  --space-12: 3rem;'
    echo '  --space-16: 4rem;'
    echo '  --space-20: 5rem;'
    echo '  --space-24: 6rem;'
    echo '  --space-30: 7.5rem;'
    echo '  --radius-sm: 0.375rem;'
    echo '  --radius-md: 0.625rem;'
    echo '  --radius-lg: 1.125rem;'
    echo '  --radius-pill: 999px;'
    echo '  --shadow-sm: 0 1px 2px rgb(27 26 23 / 6%);'
    echo '  --shadow-md: 0 10px 30px -16px rgb(27 26 23 / 22%);'
    echo '  --shadow-lg: 0 34px 70px -34px rgb(27 26 23 / 32%);'
    echo '  --container: 75rem;'
    echo '  --motion-fast: 180ms;'
    echo '  --motion-base: 350ms;'
    echo '  --motion-slow: 800ms;'
    echo '  --ease-out: cubic-bezier(0.22, 0.61, 0.36, 1);'
    echo '}'
    echo
    echo '@theme inline {'
    echo '  --color-bg: var(--bg);'
    echo '  --color-surface: var(--surface);'
    echo '  --color-surface-2: var(--surface-2);'
    echo '  --color-ink: var(--ink);'
    echo '  --color-ink-2: var(--ink-2);'
    echo '  --color-muted: var(--muted);'
    echo '  --color-line: var(--line);'
    echo '  --color-line-strong: var(--line-strong);'
    echo '  --color-accent: var(--accent);'
    echo '  --color-accent-2: var(--accent-2);'
    echo '  --color-accent-3: var(--accent-3);'
    echo '  --font-display: var(--font-display);'
    echo '  --font-sans: var(--font-sans);'
    echo '  --font-mono: var(--font-mono);'
    echo '}'
    echo
    echo '* { box-sizing: border-box; }'
    echo 'html { scroll-behavior: smooth; }'
    echo 'body {'
    echo '  margin: 0;'
    echo '  background: var(--bg);'
    echo '  color: var(--ink);'
    echo '  font-family: var(--font-sans);'
    echo '  line-height: 1.5;'
    echo '  -webkit-font-smoothing: antialiased;'
    echo '}'
    echo 'a { color: inherit; }'
    echo 'button, input, textarea { font: inherit; }'
    echo '::selection { background: var(--accent-tint); color: var(--ink); }'
    echo
    echo '.display {'
    echo '  font-family: var(--font-display);'
    echo '  font-weight: 400;'
    echo '  letter-spacing: -0.022em;'
    echo '}'
    echo '.eyebrow {'
    echo '  font-family: var(--font-mono);'
    echo '  font-size: 0.75rem;'
    echo '  letter-spacing: 0.16em;'
    echo '  text-transform: uppercase;'
    echo '}'
    echo '.focus-ring:focus-visible {'
    echo '  outline: 2px solid var(--accent);'
    echo '  outline-offset: 4px;'
    echo '}'
    echo '.content-auto { content-visibility: auto; contain-intrinsic-size: 1px 800px; }'
    echo
    echo '@media (prefers-reduced-motion: reduce) {'
    echo '  html { scroll-behavior: auto; }'
    echo '  *, *::before, *::after {'
    echo '    animation-duration: 0.01ms !important;'
    echo '    animation-iteration-count: 1 !important;'
    echo '    scroll-behavior: auto !important;'
    echo '    transition-duration: 0.01ms !important;'
    echo '  }'
    echo '}'
    echo
    echo '/* Header ausblenden solange PondExperience aktiv ist (data-hero-immersive) */'
    echo 'body[data-hero-immersive="true"] > header,'
    echo 'body[data-hero-immersive="true"] header[data-site-header] {'
    echo '  opacity: 0;'
    echo '  pointer-events: none;'
    echo '  transition: opacity 0.4s ease-out;'
    echo '}'
    echo
    echo '/* Wassertropfen die frontal am Screen herunterlaufen (Splash-Overlay) */'
    echo '@keyframes dropfall {'
    echo '  0% {'
    echo '    transform: translateY(0);'
    echo '    opacity: 0;'
    echo '  }'
    echo '  10% {'
    echo '    opacity: 0.9;'
    echo '  }'
    echo '  90% {'
    echo '    opacity: 0.7;'
    echo '  }'
    echo '  100% {'
    echo '    transform: translateY(110vh);'
    echo '    opacity: 0;'
    echo '  }'
    echo '}'
} > "$ausgabedatei"
