#!/usr/bin/env tclsh
# 1781743218784_260531.js — portiert nach tcl
# Quelle: javascript, Projects@abstractions:javascript/1781743218784_260531.js
# Erzeugt: 2026-08-18 durch ABSTRACTIONS_MANAGER.py

# 1781743218784.tcl — portiert nach javascript
# Quelle: tcl, Projects@abstractions:tcl/1781743218784.tcl
# Erzeugt: 2026-08-08 durch ABSTRACTIONS_MANAGER.py

# 1781743218784.html — portiert nach tcl
# Quelle: html, Projects@secret-vault-public:secret-vault-public/versions/1781743218784.html
# Erzeugt: 2026-08-08 durch ABSTRACTIONS_MANAGER.py

# Tcl 8.6 script to generate the Secret Vault Public HTML file
# Usage: tclsh this_script.tcl output_file.html

if {$argc != 1} {
    puts "Usage: tclsh [info script] output_file.html"
    exit 1
}

set outputFile [lindex $argv 0]
set fd [open $outputFile w]

# Write DOCTYPE and main script tag
puts $fd "<!DOCTYPE html>"
puts $fd "<script type=\"application/json\" id=\"cowork-artifact-meta\">"
puts $fd ""
puts $fd "{"
puts $fd "  \"name\": \"Secret Vault Public\","
puts $fd "  \"schemaVersion\": 1,"
puts $fd "  \"description\": \"Secret-Vault Public als interaktives Browser-Artefakt: verschlüsselter Secret-Container vollständig client-seitig (WebCrypto, AES-256-GCM + PBKDF2). Öffnen/Anlegen, Anbieter/Felder ergänzen und ersetzen (Rotation), verschlüsseln und als .svpb herunterladen oder Klartext-JSON exportieren. DE/EN nach Browsersprache. Eigenes Format (nicht kompatibel mit dem scrypt-Python-Tool). Keine Secrets eingebettet.\","
puts $fd "  \"mcpTools\": [],"
puts $fd "  \"mcpServerNames\": []"
puts $fd "}"
puts $fd ""
puts $fd "</script>"

# Write HTML start and head section
puts $fd "<html lang=\"de\">"
puts $fd "<head>"
puts $fd "<meta charset=\"utf-8\">"
puts $fd "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
puts $fd "<title>Secret-Vault Public</title>"
puts $fd "<style>"
puts $fd ":root{ color-scheme:light; --ink:#1b1c1f; --muted:#6c6e75; --faint:#9a9ca3; --card:#fff; --line:#e9eaee; --accent:#5b5bd6; --accent2:#7c5cff; --ok:#22a06b; --err:#e0533d; --radius:16px; --shadow:0 1px 2px rgba(20,20,40,.04),0 6px 20px rgba(20,20,40,.06);}"
puts $fd "*{box-sizing:border-box;}"
puts $fd "body{margin:0;font-family:-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,Helvetica,Arial,sans-serif;color:var(--ink);min-height:100vh;background:radial-gradient(1100px 560px at 100% -10%,#e8ecff 0%,rgba(232,236,255,0) 55%),linear-gradient(180deg,#eef1f6,#f7f7f8 42%);background-attachment:fixed;}"
puts $fd ".wrap{max-width:820px;margin:0 auto;padding:24px 18px 70px;}"
puts $fd ".brand{display:flex;align-items:center;gap:12px;margin-bottom:4px;}"
puts $fd ".mark{width:32px;height:32px;border-radius:9px;background:linear-gradient(135deg,var(--accent),var(--accent2));box-shadow:0 4px 12px rgba(91,91,214,.35);position:relative;flex:0 0 auto;}"
puts $fd ".mark:after{content:\"\";position:absolute;inset:8px;border-radius:4px;border:2px solid rgba(255,255,255,.92);}"
puts $fd "h1{font-size:21px;margin:0;font-weight:700;}"
puts $fd ".sub{color:var(--muted);font-size:13px;margin:2px 0 16px;}"
puts $fd ".card{background:var(--card);border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow);padding:16px;margin-bottom:14px;}"
puts $fd ".card h2{font-size:14px;margin:0 0 10px;}"
puts $fd "label.lab{display:block;font-size:12px;font-weight:600;color:var(--muted);margin:8px 0 3px;}"
puts $fd "input,textarea{width:100%;font-size:13px;padding:8px 10px;border:1px solid var(--line);border-radius:9px;font-family:ui-monospace,Menlo,Consolas,monospace;background:#fff;}"
puts $fd "textarea{min-height:90px;white-space:pre;overflow:auto;}"
puts $fd ".row{display:flex;gap:8px;flex-wrap:wrap;align-items:center;}"
puts $fd ".btn{font-size:13px;font-weight:600;padding:8px 14px;border:1px solid var(--line);border-radius:10px;background:#fff;cursor:pointer;box-shadow:var(--shadow);transition:transform .1s;}"
puts $fd ".btn:hover{transform:translateY(-1px);}"
puts $fd ".btn.primary{background:linear-gradient(135deg,var(--accent),var(--accent2));color:#fff;border-color:transparent;}"
puts $fd ".btn.sm{padding:5px 9px;font-size:12px;}"
puts $fd ".msg{font-size:12px;margin-left:6px;}"
puts $fd ".msg.ok{color:var(--ok);} .msg.err{color:var(--err);}"
puts $fd ".prov{border:1px solid var(--line);border-radius:12px;padding:10px 12px;margin-bottom:10px;}"
puts $fd ".prov h3{margin:0 0 6px;font-size:13.5px;display:flex;align-items:center;gap:8px;}"
puts $fd ".kv{display:grid;grid-template-columns:180px 1fr auto;gap:6px;margin:4px 0;align-items:center;}"
puts $fd ".kv input{font-size:12px;padding:5px 7px;}"
puts $fd ".kv .k{color:var(--muted);font-weight:600;}"
puts $fd ".muted{color:var(--faint);font-size:13px;}"
puts $fd ".hide{display:none;}"
puts $fd ".foot{color:var(--faint);font-size:11.5px;text-align:center;margin-top:18px;line-height:1.5;}"
puts $fd "a{color:var(--accent);}"
puts $fd "</style>"
puts $fd "</head>"

# Write body content
puts $fd "<body>"
puts $fd "<div class=\"wrap\">"
puts $fd "  <div class=\"brand\"><div class=\"mark\"></div><h1 id=\"title\">Secret-Vault Public</h1></div>"
puts $fd "  <div class=\"sub\" id=\"sub\">Verschlüsselte Secret-Vault (AES-256-GCM, PBKDF2) — alles im Browser, kein Server.</div>"

# Card: Open or new
puts $fd ""
puts $fd "  <div class=\"card\">"
puts $fd "    <h2 id=\"h-open\">Öffnen oder neu</h2>"
puts $fd "    <label class=\"lab\" id=\"l-pass\">Passphrase</label>"
puts $fd "    <input id=\"pass\" type=\"password\" placeholder=\"Passphrase…\">"
puts $fd "    <label class=\"lab\" id=\"l-file\">Vault laden (Datei oder Base64 einfügen)</label>"
puts $fd "    <input id=\"file\" type=\"file\" accept=\".svpb,.txt,.vault,.b64\">"
puts $fd "    <textarea id=\"blob\" placeholder=\"…oder Base64 hier einfügen\"></textarea>"
puts $fd "    <div class=\"row\" style=\"margin-top:10px\">"
puts $fd "      <button class=\"btn primary\" id=\"openBtn\">Öffnen / Entschlüsseln</button>"
puts $fd "      <button class=\"btn\" id=\"newBtn\">Neuer leerer Vault</button>"
puts $fd "      <span class=\"msg\" id=\"openMsg\"></span>"
puts $fd "    </div>"
puts $fd "  </div>"
puts $fd ""

# Card: Editor (hidden by default)
puts $fd "  <div class=\"card hide\" id=\"editor\">"
puts $fd "    <h2 id=\"h-edit\">Inhalt</h2>"
puts $fd "    <div id=\"provs\"></div>"
puts $fd "    <div class=\"row\" style=\"margin-top:8px\">"
puts $fd "      <input id=\"newProv\" placeholder=\"Neuer Anbieter (Name)\" style=\"max-width:280px\">"
puts $fd "      <button class=\"btn sm\" id=\"addProvBtn\">+ Anbieter</button>"
puts $fd "    </div>"
puts $fd "  </div>"
puts $fd ""

# Card: Save/Export (hidden by default)
puts $fd "  <div class=\"card hide\" id=\"out\">"
puts $fd "    <h2 id=\"h-save\">Speichern / Export</h2>"
puts $fd "    <div class=\"row\">"
puts $fd "      <button class=\"btn primary\" id=\"encBtn\">Verschlüsseln</button>"
puts $fd "      <button class=\"btn\" id=\"dlBtn\">Als .svpb herunterladen</button>"
puts $fd "      <button class=\"btn\" id=\"expBtn\">Klartext-JSON exportieren</button>"
puts $fd "      <span class=\"msg\" id=\"saveMsg\"></span>"
puts $fd "    </div>"
puts $fd "    <label class=\"lab\" id=\"l-result\">Ergebnis (zum Kopieren/Speichern)</label>"
puts $fd "    <textarea id=\"result\" readonly></textarea>"
puts $fd "  </div>"
puts $fd ""

# Footer
puts $fd "  <div class=\"foot\" id=\"foot\"></div>"
puts $fd "</div>"

# JavaScript section
puts $fd "<script>"
puts $fd ""
puts $fd "const L = ((navigator.language||\"en\").toLowerCase().startsWith(\"de\"))?\"de\":\"en\";"
puts $fd "const T = {"
puts $fd " title:{de:\"Secret-Vault Public\",en:\"Secret-Vault Public\"},"
puts $fd " sub:{de:\"Verschlüsselte Secret-Vault (AES-256-GCM, PBKDF2) — alles im Browser, kein Server.\",en:\"Encrypted secret vault (AES-256-GCM, PBKDF2) — fully in the browser, no server.\"},"
puts $fd " hOpen:{de:\"Öffnen oder neu\",en:\"Open or new\"},"
puts $fd " pass:{de:\"Passphrase\",en:\"Passphrase\"},"
puts $fd " file:{de:\"Vault laden (Datei oder Base64 einfügen)\",en:\"Load vault (file or paste Base64)\"},"
puts $fd " blob:{de:\"…oder Base64 hier einfügen\",en:\"…or paste Base64 here\"},"
puts $fd " open:{de:\"Öffnen / Entschlüsseln\",en:\"Open / Decrypt\"},"
puts $fd " neu:{de:\"Neuer leerer Vault\",en:\"New empty vault\"},"
puts $fd " hEdit:{de:\"Inhalt\",en:\"Content\"},"
puts $fd " newProv:{de:\"Neuer Anbieter (Name)\",en:\"New provider (name)\"},"
puts $fd " addProv:{de:\"+ Anbieter\",en:\"+ Provider\"},"
puts $fd " hSave:{de:\"Speichern / Export\",en:\"Save / Export\"},"
puts $fd " enc:{de:\"Verschlüsseln\",en:\"Encrypt\"},"
puts $fd " dl:{de:\"Als .svpb herunterladen\",en:\"Download as .svpb\"},"
puts $fd " exp:{de:\"Klartext-JSON exportieren\",en:\"Export plaintext JSON\"},"
puts $fd " result:{de:\"Ergebnis (zum Kopieren/Speichern)\",en:\"Result (to copy/save)\"},"
puts $fd " foot:{de:\"Eigenes Format (PBKDF2). Nicht kompatibel mit dem scrypt-Python-Tool. Sicherheit liegt in der Passphrase; Inhalt ohne sie nicht wiederherstellbar.\",en:\"Own format (PBKDF2). Not compatible with the scrypt Python tool. Security rests on the passphrase; content is unrecoverable without it.\"},"
puts $fd " needPass:{de:\"Passphrase eingeben.\",en:\"Enter a passphrase.\"},"
puts $fd " noInput:{de:\"Datei laden oder Base64 einfügen.\",en:\"Load a file or paste Base64.\"},"
puts $fd " bad:{de:\"Falsche Passphrase oder ungültiger Vault.\",en:\"Wrong passphrase or invalid vault.\"},"
puts $fd " opened:{de:\"Geöffnet.\",en:\"Opened.\"},"
puts $fd " created:{de:\"Neuer Vault angelegt.\",en:\"New vault created.\"},"
puts $fd " encrypted:{de:\"Verschlüsselt — unten kopieren oder herunterladen.\",en:\"Encrypted — copy below or download.\"},"
puts $fd " needOpen:{de:\"Erst öffnen/anlegen.\",en:\"Open/create first.\"},"
puts $fd " field:{de:\"Feld\",en:\"field\"}, value:{de:\"Wert\",en:\"value\"},"
puts $fd " addField:{de:\"+ Feld\",en:\"+ field\"}, del:{de:\"✕\",en:\"✕\"},"
puts $fd " newField:{de:\"neues Feld\",en:\"new field\"}, newValue:{de:\"Wert\",en:\"value\"}"
puts $fd "};"
puts $fd "const tr=k=>T[k][L];"
puts $fd "// apply static i18n"
puts $fd "title.textContent=tr(\"title\"); sub.textContent=tr(\"sub\"); document.title=tr(\"title\");"
puts $fd "document.getElementById(\"h-open\").textContent=tr(\"hOpen\");"
puts $fd "document.getElementById(\"l-pass\").textContent=tr(\"pass\");"
puts $fd "document.getElementById(\"l-file\").textContent=tr(\"file\");"
puts $fd "blob.placeholder=tr(\"blob\");"
puts $fd "openBtn.textContent=tr(\"open\"); newBtn.textContent=tr(\"neu\");"
puts $fd "document.getElementById(\"h-edit\").textContent=tr(\"hEdit\");"
puts $fd "newProv.placeholder=tr(\"newProv\"); addProvBtn.textContent=tr(\"addProv\");"
puts $fd "document.getElementById(\"h-save\").textContent=tr(\"hSave\");"
puts $fd "encBtn.textContent=tr(\"enc\"); dlBtn.textContent=tr(\"dl\"); expBtn.textContent=tr(\"exp\");"
puts $fd "document.getElementById(\"l-result\").textContent=tr(\"result\");"
puts $fd "foot.textContent=tr(\"foot\");"
puts $fd ""
puts $fd "let VAULT=null; // {meta, providers:{}}"
puts $fd ""
puts $fd "const enc=new TextEncoder(), dec=new TextDecoder();"
puts $fd "function u8b64(u8){ let s=\"\"; for(let i=0;i<u8.length;i+=0x8000) s+=String.fromCharCode.apply(null,u8.subarray(i,i+0x8000)); return btoa(s); }"
puts $fd "function b64u8(b64){ const s=atob(b64.trim()); const u=new Uint8Array(s.length); for(let i=0;i<s.length;i++) u[i]=s.charCodeAt(i); return u; }"
puts $fd "async function deriveKey(pw,salt){"
puts $fd "  const km=await crypto.subtle.importKey(\"raw\",enc.encode(pw),\"PBKDF2\",false,[\"deriveKey\"]);"
puts $fd "  return crypto.subtle.deriveKey({name:\"PBKDF2\",salt,iterations:210000,hash:\"SHA-256\"},km,{name:\"AES-GCM\",length:256},false,[\"encrypt\",\"decrypt\"]);"
puts $fd "}"
puts $fd "async function encryptObj(obj,pw){"
puts $fd "  const salt=crypto.getRandomValues(new Uint8Array(16)), iv=crypto.getRandomValues(new Uint8Array(12));"
puts $fd "  const key=await deriveKey(pw,salt);"
puts $fd "  const ct=new Uint8Array(await crypto.subtle.encrypt({name:\"AES-GCM\",iv},key,enc.encode(JSON.stringify(obj,null,2))));"
puts $fd "  const magic=enc.encode(\"SVPB1\"); const out=new Uint8Array(5+16+12+ct.length);"
puts $fd "  out.set(magic,0); out.set(salt,5); out.set(iv,21); out.set(ct,33); return u8b64(out);"
puts $fd "}"
puts $fd "async function decryptB64(b64,pw){"
puts $fd "  const raw=b64u8(b64); if(dec.decode(raw.slice(0,5))!==\"SVPB1\") throw new Error(\"magic\");"
puts $fd "  const key=await deriveKey(pw,raw.slice(5,21));"
puts $fd "  const pt=await crypto.subtle.decrypt({name:\"AES-GCM\",iv:raw.slice(21,33)},key,raw.slice(33));"
puts $fd "  return JSON.parse(dec.decode(pt));"
puts $fd "}"
puts $fd "function esc(s){return (s==null?\"\":String(s)).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));}"
puts $fd ""
puts $fd "function renderEditor(){"
puts $fd "  document.getElementById(\"editor\").classList.remove(\"hide\");"
puts $fd "  document.getElementById(\"out\").classList.remove(\"hide\");"
puts $fd "  const P=VAULT.providers||{}; const root=document.getElementById(\"provs\"); root.innerHTML=\"\";"
puts $fd "  Object.keys(P).forEach(name=>{"
puts $fd "    const d=document.createElement(\"div\"); d.className=\"prov\";"
puts $fd "    let rows=\"\";"
puts $fd "    Object.keys(P[name]).forEach(k=>{ rows+=`<div class=\"kv\"><span class=\"k\">\${esc(k)}</span><input data-p=\"\${esc(name)}\" data-k=\"\${esc(k)}\" value=\"\${esc(P[name][k])}\"><button class=\"btn sm\" data-del=\"\${esc(name)}|\${esc(k)}\">\${tr(\"del\")}</button></div>`; });"
puts $fd "    d.innerHTML=`<h3>\${esc(name)} <button class=\"btn sm\" data-delp=\"\${esc(name)}\">\${tr(\"del\")}</button></h3>\${rows}"
puts $fd "      <div class=\"row\" style=\"margin-top:6px\"><input class=\"nf\" data-np=\"\${esc(name)}\" placeholder=\"\${tr(\"newField\")}\" style=\"max-width:180px\"><input class=\"nv\" data-np=\"\${esc(name)}\" placeholder=\"\${tr(\"newValue\")}\" style=\"max-width:260px\"><button class=\"btn sm\" data-addf=\"\${esc(name)}\">\${tr(\"addField\")}</button></div>`;"
puts $fd "    root.appendChild(d);"
puts $fd "  });"
puts $fd "  root.querySelectorAll(\"input[data-k]\").forEach(i=>i.onchange=()=>{ VAULT.providers[i.dataset.p][i.dataset.k]=i.value; });"
puts $fd "  root.querySelectorAll(\"button[data-del]\").forEach(b=>b.onclick=()=>{ const [p,k]=b.dataset.del.split(\"|\"); delete VAULT.providers[p][k]; renderEditor(); });"
puts $fd "  root.querySelectorAll(\"button[data-delp]\").forEach(b=>b.onclick=()=>{ delete VAULT.providers[b.dataset.delp]; renderEditor(); });"
puts $fd "  root.querySelectorAll(\"button[data-addf]\").forEach(b=>b.onclick=()=>{ const p=b.dataset.addf; const nf=root.querySelector(`.nf[data-np=\"\${CSS.escape(p)}\"]`).value.trim(); const nv=root.querySelector(`.nv[data-np=\"\${CSS.escape(p)}\"]`).value; if(nf){ VAULT.providers[p][nf]=nv; renderEditor(); } });"
puts $fd "}"
puts $fd ""
puts $fd "document.getElementById(\"file\").onchange=e=>{ const f=e.target.files[0]; if(!f)return; const r=new FileReader(); r.onload=()=>{ blob.value=r.result.trim(); }; r.readAsText(f); };"
puts $fd "openBtn.onclick=async()=>{"
puts $fd "  const m=document.getElementById(\"openMsg\"); m.className=\"msg\"; m.textContent=\"\";"
puts $fd "  if(!pass.value){ m.className=\"msg err\"; m.textContent=tr(\"needPass\"); return; }"
puts $fd "  if(!blob.value.trim()){ m.className=\"msg err\"; m.textContent=tr(\"noInput\"); return; }"
puts $fd "  try{ VAULT=await decryptB64(blob.value,pass.value); if(!VAULT.providers)VAULT.providers={}; renderEditor(); m.className=\"msg ok\"; m.textContent=tr(\"opened\"); }"
puts $fd "  catch(err){ m.className=\"msg err\"; m.textContent=tr(\"bad\"); }"
puts $fd "};"
puts $fd "newBtn.onclick=()=>{"
puts $fd "  const m=document.getElementById(\"openMsg\");"
puts $fd "  if(!pass.value){ m.className=\"msg err\"; m.textContent=tr(\"needPass\"); return; }"
puts $fd "  VAULT={meta:{created:new Date().toISOString().slice(0,10),format:\"SVPB1\"},providers:{}}; renderEditor();"
puts $fd "  m.className=\"msg ok\"; m.textContent=tr(\"created\");"
puts $fd "};"
puts $fd "addProvBtn.onclick=()=>{ if(!VAULT){ return; } const n=newProv.value.trim(); if(n){ VAULT.providers[n]=VAULT.providers[n]||{}; newProv.value=\"\"; renderEditor(); } };"
puts $fd "encBtn.onclick=async()=>{"
puts $fd "  const m=document.getElementById(\"saveMsg\"); m.className=\"msg\";"
puts $fd "  if(!VAULT){ m.className=\"msg err\"; m.textContent=tr(\"needOpen\"); return; }"
puts $fd "  if(!pass.value){ m.className=\"msg err\"; m.textContent=tr(\"needPass\"); return; }"
puts $fd "  result.value=await encryptObj(VAULT,pass.value); m.className=\"msg ok\"; m.textContent=tr(\"encrypted\");"
puts $fd "};"
puts $fd "dlBtn.onclick=()=>{ if(!result.value)return; try{ const b=new Blob([result.value],{type:\"text/plain\"}); const u=URL.createObjectURL(b); const a=document.createElement(\"a\"); a.href=u; a.download=\"vault.svpb\"; document.body.appendChild(a); a.click(); a.remove(); setTimeout(()=>URL.revokeObjectURL(u),1500);}catch(e){} };"
puts $fd "expBtn.onclick=()=>{ if(!VAULT)return; result.value=JSON.stringify(VAULT,null,2); };"
puts $fd ""
puts $fd "</script>"
puts $fd "</body>"
puts $fd "</html>"

close $fd

puts "HTML file generated: $outputFile"
