#!/usr/bin/env tclsh
# 3d.html — portiert nach tcl
# Quelle: html, Projects@tiktok-monitor:public/3d.html
# Erzeugt: 2026-08-09 durch ABSTRACTIONS_MANAGER.py

package require Tcl 8.6

# Create HTML document structure
proc create_html {} {
    set html "<!DOCTYPE html>\n"
    append html "<html lang=\"de\">\n"
    append html "<head>\n"
    append html "<meta charset=\"utf-8\">\n"
    append html "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    append html "<title>tt-live — Interaktive Architektur</title>\n"
    append html "<meta name=\"description\" content=\"Vom @handle zum Ereignis: Auflösung, Prüfung, Daemon — drehen, zoomen, Knoten auswählen.\">\n"
    append html "<meta name=\"theme-color\" content=\"#fe2c55\">\n"
    append html "<style>\n"
    append html "  :root{\n"
    append html "    --bg:#fbfaf7; --panel:#fff; --line:#e6e3dc; --text:#16191d; --muted:#5f6773;\n"
    append html "    --ac:#fe2c55; --buehne:#0e1420; --buehne-line:#1d2739;\n"
    append html "    color-scheme: light;\n"
    append html "  }\n"
    append html "  @media (prefers-color-scheme: dark){\n"
    append html "    :root{ --bg:#0f1115; --panel:#171a21; --line:#262b36; --text:#f2f4f8; --muted:#9aa3b2;\n"
    append html "           color-scheme: dark; }\n"
    append html "  }\n"
    append html "  *{box-sizing:border-box}\n"
    append html "  body{margin:0;background:var(--bg);color:var(--text);\n"
    append html "       font:15px/1.55 -apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,sans-serif}\n"
    append html "  .wrap{max-width:1240px;margin:0 auto;padding:34px 22px 60px}\n"
    append html "  .technik{font-size:12px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;\n"
    append html "           color:var(--ac);margin:0 0 10px}\n"
    append html "  h1{font-size:clamp(30px,5vw,52px);line-height:1.05;margin:0 0 14px;letter-spacing:-.03em}\n"
    append html "  .lede{font-size:16.5px;color:var(--muted);max-width:62ch;margin:0 0 26px}\n"
    append html "  .raster{display:grid;grid-template-columns:minmax(0,1fr) 288px;gap:18px;align-items:start}\n"
    append html "  @media (max-width:880px){ .raster{grid-template-columns:1fr} }\n"
    append html "  .buehne{position:relative;background:var(--buehne);border-radius:14px;overflow:hidden;\n"
    append html "          min-height:520px;aspect-ratio:16/11}\n"
    append html "  .buehne canvas{display:block;width:100%;height:100%}\n"
    append html "  .knoepfe{position:absolute;top:14px;right:14px;display:flex;gap:8px;z-index:2}\n"
    append html "  button{font:inherit;font-size:14px;font-weight:650;padding:9px 14px;border-radius:9px;\n"
    append html "         border:1px solid var(--line);background:var(--panel);color:var(--text);cursor:pointer}\n"
    append html "  button:hover{border-color:var(--ac)}\n"
    append html "  button[aria-pressed=\"true\"]{background:var(--ac);border-color:var(--ac);color:#fff}\n"
    append html "  .karte{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:20px}\n"
    append html "  .karte h2{font-size:11px;font-weight:700;letter-spacing:.09em;text-transform:uppercase;\n"
    append html "            color:var(--muted);margin:0 0 12px}\n"
    append html "  .karte h3{font-size:23px;margin:0 0 4px;letter-spacing:-.02em}\n"
    append html "  .karte .sub{color:var(--muted);margin:0 0 18px;font-size:14.5px}\n"
    append html "  .feld{border-top:1px solid var(--line);padding:12px 0 0;margin:0 0 12px}\n"
    append html "  .feld dt{font-size:11px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;\n"
    append html "           color:var(--muted);margin:0 0 3px}\n"
    append html "  .feld dd{margin:0;font-weight:650}\n"
    append html "  .blaettern{display:flex;gap:8px;margin-top:16px}\n"
    append html "  .blaettern button{flex:1;text-align:center;line-height:1.25;padding:11px 8px}\n"
    append html "  .legende{display:flex;gap:22px;flex-wrap:wrap;margin:16px 0 0;font-size:13.5px;color:var(--muted)}\n"
    append html "  .legende span{display:inline-flex;align-items:center;gap:9px}\n"
    append html "  .strich{width:30px;height:0;border-top-width:3px;border-top-style:solid;display:inline-block}\n"
    append html "  .fuss{margin:14px 0 0;font-size:13px;color:var(--muted);max-width:80ch}\n"
    append html "  .fehler{padding:40px;text-align:center;color:var(--muted)}\n"
    append html "  a{color:var(--ac)}\n"
    append html "</style>\n"
    append html "</head>\n"
    append html "<body>\n"
    append html "<div class=\"wrap\">\n"
    append html "\n"
    append html "  <p class=\"technik\">three.js · r128</p>\n"
    append html "  <h1>tt-live</h1>\n"
    append html "  <p class=\"lede\">Vom @handle zum Ereignis: Auflösung, Prüfung, Daemon — drehen, zoomen, Knoten auswählen.</p>\n"
    append html "\n"
    append html "  <div class=\"raster\">\n"
    append html "    <div class=\"buehne\" id=\"buehne\">\n"
    append html "      <div class=\"knoepfe\">\n"
    append html "        <button id=\"btn-plus\" title=\"Näher\">+</button>\n"
    append html "        <button id=\"btn-minus\" title=\"Weiter weg\">−</button>\n"
    append html "        <button id=\"btn-reset\">Zurücksetzen</button>\n"
    append html "        <button id=\"btn-iso\" aria-pressed=\"true\" title=\"Isometrisch oder perspektivisch\">Iso</button>\n"
    append html "      </div>\n"
    append html "    </div>\n"
    append html "\n"
    append html "    <aside class=\"karte\">\n"
    append html "      <h2>Ausgewählter Knoten</h2>\n"
    append html "      <h3 id=\"k-name\">—</h3>\n"
    append html "      <p class=\"sub\" id=\"k-sub\">Knoten anklicken oder durchblättern</p>\n"
    append html "      <dl class=\"feld\"><dt>Schicht</dt><dd id=\"k-schicht\">—</dd></dl>\n"
    append html "      <dl class=\"feld\"><dt>ID</dt><dd id=\"k-id\">—</dd></dl>\n"
    append html "      <div class=\"blaettern\">\n"
    append html "        <button id=\"btn-prev\">←<br>Vorheriger</button>\n"
    append html "        <button id=\"btn-next\">Nächster<br>→</button>\n"
    append html "      </div>\n"
    append html "    </aside>\n"
    append html "  </div>\n"
    append html "\n"
    append html "  <div class=\"legende\" id=\"legende\"></div>\n"
    append html "  <p class=\"fuss\">Schematische Dokumentationsansicht — Blockgrößen messen weder Datenmenge noch Leistung. Keine Telemetrie, keine Fernabfragen: Die Seite lädt einmalig three.js vom CDN und rechnet danach ausschließlich lokal.</p>\n"
    append html "\n"
    append html "</div>\n"
    append html "\n"
    append html "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js\"></script>\n"
    append html "<script>\n"
    append html "(function(){\n"
    append html "  \"use strict\";\n"
    append html "  var SPEC = {\"schichten\": [{\"name\": \"Quellen\", \"farbe\": \"#5f6773\", \"blocks\": [{\"id\": \"tiktok-com-user\", \"name\": \"tiktok.com/@user\", \"untertitel\": \"oeffentlich\"}, {\"id\": \"room-id\", \"name\": \"room_id\", \"untertitel\": \"aufgeloest\"}, {\"id\": \"m3u8\", \"name\": \"m3u8\", \"untertitel\": \"Stream-URL\"}]}, {\"name\": \"Werkzeuge\", \"farbe\": \"#2481cc\", \"blocks\": [{\"id\": \"get-room-id-py\", \"name\": \"get_room_id.py\", \"untertitel\": \"handle -> id\"}, {\"id\": \"check-alive-py\", \"name\": \"check_alive.py\", \"untertitel\": \"live ja/nein\"}, {\"id\": \"tt-live-py\", \"name\": \"tt_live.py\", \"untertitel\": \"alles plus Daemon\"}]}, {\"name\": \"Einstieg\", \"farbe\": \"#6d5bd0\", \"blocks\": [{\"id\": \"tt-live-sh\", \"name\": \"tt-live.sh\", \"untertitel\": \"Einstieg\"}, {\"id\": \"tt-live-json\", \"name\": \"tt-live.json\", \"untertitel\": \"Aufrufe\"}]}, {\"name\": \"Daemon\", \"farbe\": \"#b45309\", \"blocks\": [{\"id\": \"zeitfenster\", \"name\": \"Zeitfenster\", \"untertitel\": \"Dauer + Abstand\"}, {\"id\": \"zustandsspeicher\", \"name\": \"Zustandsspeicher\", \"untertitel\": \"letzter Stand\"}, {\"id\": \"abstand\", \"name\": \"Abstand\", \"untertitel\": \"Takt\"}]}, {\"name\": \"Ereignisse\", \"farbe\": \"#fe2c55\", \"blocks\": [{\"id\": \"go-live\", \"name\": \"go_live\", \"untertitel\": \"Wechsel\"}, {\"id\": \"go-offline\", \"name\": \"go_offline\", \"untertitel\": \"Wechsel\"}, {\"id\": \"rename-detected\", \"name\": \"rename_detected\", \"untertitel\": \"Namenswechsel\"}]}], \"kanten\": [{\"von\": \"tiktok-com-user\", \"nach\": \"get-room-id-py\", \"art\": \"fluss\"}, {\"von\": \"room-id\", \"nach\": \"check-alive-py\", \"art\": \"fluss\"}, {\"von\": \"m3u8\", \"nach\": \"tt-live-py\", \"art\": \"fluss\"}, {\"von\": \"get-room-id-py\", \"nach\": \"tt-live-sh\", \"art\": \"fluss\"}, {\"von\": \"check-alive-py\", \"nach\": \"tt-live-json\", \"art\": \"fluss\"}, {\"von\": \"tt-live-py\", \"nach\": \"tt-live-sh\", \"art\": \"fluss\"}, {\"von\": \"tt-live-sh\", \"nach\": \"zeitfenster\", \"art\": \"fluss\"}, {\"von\": \"tt-live-json\", \"nach\": \"zustandsspeicher\", \"art\": \"fluss\"}, {\"von\": \"zeitfenster\", \"nach\": \"go-live\", \"art\": \"fluss\"}, {\"von\": \"zustandsspeicher\", \"nach\": \"go-offline\", \"art\": \"fluss\"}, {\"von\": \"abstand\", \"nach\": \"rename-detected\", \"art\": \"fluss\"}], \"kantenarten\": [{\"art\": \"fluss\", \"farbe\": \"#fe2c55\", \"stil\": \"voll\", \"text\": \"Fluss von unten nach oben\"}]};\n"
    append html "\n"
    append html "  var buehne = document.getElementById(\"buehne\");\n"
    append html "  if (typeof THREE === \"undefined\"){\n"
    append html "    buehne.insertAdjacentHTML(\"beforeend\",\n"
    append html "      '<div class=\"fehler\">three.js konnte nicht geladen werden. ' +\n"
    append html "      'Die Seite braucht einmalig Netzzugang zum CDN.</div>');\n"
    append html "    return;\n"
    append html "  }\n"
    append html "\n"
    append html "  // ---------------------------------------------------------------- Szene ---\n"
    append html "  var szene = new THREE.Scene();\n"
    append html "  szene.background = new THREE.Color(0x0e1420);\n"
    append html "  var renderer = new THREE.WebGLRenderer({antialias:true});\n"
    append html "  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));\n"
    append html "  buehne.appendChild(renderer.domElement);\n"
    append html "\n"
    append html "  var D = 26, radius = 82, aspekt = 1;\n"
    append html "  var kameraIso = new THREE.OrthographicCamera(-D, D, D, -D, 0.1, 600);\n"
    append html "  var kameraPersp = new THREE.PerspectiveCamera(42, 1, 0.1, 600);\n"
    append html "  var kamera = kameraIso, iso = true;\n"
    append html "\n"
    append html "  szene.add(new THREE.AmbientLight(0xffffff, 0.66));\n"
    append html "  var licht = new THREE.DirectionalLight(0xffffff, 0.8);\n"
    append html "  licht.position.set(30, 46, 26); szene.add(licht);\n"
    append html "  var gegen = new THREE.DirectionalLight(0x8ea2ff, 0.3);\n"
    append html "  gegen.position.set(-32, 16, -28); szene.add(gegen);\n"
    append html "\n"
    append html "  var raster = new THREE.GridHelper(110, 34, 0x25324a, 0x1a2333);\n"
    append html "  raster.position.y = -24; szene.add(raster);\n"
    append html "\n"
    append html "  // ------------------------------------------------------------ Schilder ---\n"
    append html "  // Text auf eine Textur, dann als Billboard — bleibt bei jeder Drehung lesbar.\n"
    append html "  function schild(text, unter){\n"
    append html "    var c = document.createElement(\"canvas\"), x = c.getContext(\"2d\");\n"
    append html "    var f1 = \"700 40px -apple-system,Segoe UI,Roboto,sans-serif\";\n"
    append html "    var f2 = \"500 27px -apple-system,Segoe UI,Roboto,sans-serif\";\n"
    append html "    x.font = f1; var w1 = x.measureText(text).width;\n"
    append html "    x.font = f2; var w2 = unter ? x.measureText(unter).width : 0;\n"
    append html "    var w = Math.ceil(Math.max(w1, w2)) + 40, h = unter ? 96 : 62;\n"
    append html "    c.width = w; c.height = h;\n"
    append html "    x = c.getContext(\"2d\");\n"
    append html "    x.fillStyle = \"rgba(255,255,255,.95)\";\n"
    append html "    if (x.roundRect){ x.beginPath(); x.roundRect(0,0,w,h,13); x.fill(); }\n"
    append html "    else x.fillRect(0,0,w,h);\n"
    append html "    x.fillStyle = \"#16191d\"; x.font = f1; x.textBaseline = \"middle\";\n"
    append html "    x.fillText(text, 20, unter ? 32 : 31);\n"
    append html "    if (unter){ x.fillStyle = \"#5f6773\"; x.font = f2; x.fillText(unter, 20, 68); }\n"
    append html "    var t = new THREE.CanvasTexture(c); t.minFilter = THREE.LinearFilter;\n"
    append html "    var s = new THREE.Sprite(new THREE.SpriteMaterial({map:t, transparent:true, depthTest:false}));\n"
    append html "    s.scale.set(w/62*2.5, h/62*2.5, 1);\n"
    append html "    s.renderOrder = 999;\n"
    append html "    return s;\n"
    append html "  }\n"
    append html "\n"
    append html "  // -------------------------------------------------------------- Aufbau ---\n"
    append html "  var BW = 7.4, BD = 4.2, BH = 1.7, LUFT = 1.3, ABSTAND = 11.4, START = -17;\n"
    append html "  var knoten = [], nachId = {}, klickbar = [];\n"
    append html "  var gruppe = new THREE.Group();\n"
    append html "\n"
    append html "  SPEC.schichten.forEach(function(sch, si){\n"
    append html "    var y = START + si * ABSTAND;\n"
    append html "    var bl = sch.blocks.map(function(b){\n"
    append html "      return (typeof b === \"string\") ? {id:null, name:b, untertitel:\"\"} : b;\n"
    append html "    });\n"
    append html "    var spalten = Math.max(1, Math.ceil(bl.length / 2));\n"
    append html "    var reihen = bl.length <= 1 ? 1 : 2;\n"
    append html "    var gx = spalten*BW + (spalten-1)*LUFT, gz = reihen*BD + (reihen-1)*LUFT;\n"
    append html "\n"
    append html "    var platte = new THREE.Mesh(\n"
    append html "      new THREE.BoxGeometry(gx+3, 0.6, gz+3),\n"
    append html "      new THREE.MeshLambertMaterial({color:new THREE.Color(sch.farbe).multiplyScalar(0.4)}));\n"
    append html "    platte.position.set(0, y-1.7, 0); gruppe.add(platte);\n"
    append html "\n"
    append html "    bl.forEach(function(b, i){\n"
    append html "      var sp = i % spalten, re = Math.floor(i / spalten);\n"
    append html "      var x = -gx/2 + BW/2 + sp*(BW+LUFT), z = -gz/2 + BD/2 + re*(BD+LUFT);\n"
    append html "      var mat = new THREE.MeshLambertMaterial({color:sch.farbe});\n"
    append html "      var m = new THREE.Mesh(new THREE.BoxGeometry(BW, BH, BD), mat);\n"
    append html "      m.position.set(x, y, z);\n"
    append html "      gruppe.add(m); klickbar.push(m);\n"
    append html "      var kante = new THREE.LineSegments(new THREE.EdgesGeometry(m.geometry),\n"
    append html "        new THREE.LineBasicMaterial({color:0x0e1420, transparent:true, opacity:.55}));\n"
    append html "      kante.position.copy(m.position); gruppe.add(kante);\n"
    append html "\n"
    append html "      var s = schild(b.name, b.untertitel);\n"
    append html "      s.position.set(x, y + BH/2 + (b.untertitel ? 2.1 : 1.6), z);\n"
    append html "      gruppe.add(s);\n"
    append html "\n"
    append html "      var id = b.id || (b.name.toLowerCase().replace(/[^a-z0-9]+/g, \"-\").replace(/^-|-$/g, \"\"));\n"
    append html "      var eintrag = {id:id, name:b.name, untertitel:b.untertitel||\"\", schicht:sch.name,\n"
    append html "                     mesh:m, mat:mat, farbe:new THREE.Color(sch.farbe), pos:m.position};\n"
    append html "      m.userData.index = knoten.length;\n"
    append html "      knoten.push(eintrag); nachId[id] = eintrag;\n"
    append html "    });\n"
    append html "  });\n"
    append html "\n"
    append html "  // -------------------------------------------------------------- Kanten ---\n"
    append html "  var STIL = {};\n"
    append html "  (SPEC.kantenarten || []).forEach(function(a){ STIL[a.art] = a; });\n"
    append html "\n"
    append html "  (SPEC.kanten || []).forEach(function(k){\n"
    append html "    var a = nachId[k.von], b = nachId[k.nach];\n"
    append html "    if (!a || !b) return;\n"
    append html "    var art = STIL[k.art] || {farbe:\"#8ea2ff\", stil:\"voll\"};\n"
    append html "    var g = new THREE.BufferGeometry().setFromPoints([\n"
    append html "      a.pos.clone().setY(a.pos.y + 0.9), b.pos.clone().setY(b.pos.y - 0.9)]);\n"
    append html "    var linie;\n"
    append html "    if (art.stil === \"gestrichelt\"){\n"
    append html "      linie = new THREE.Line(g, new THREE.LineDashedMaterial(\n"
    append html "        {color:art.farbe, dashSize:1.4, gapSize:1.0, transparent:true, opacity:.9}));\n"
    append html "      linie.computeLineDistances();\n"
    append html "    } else {\n"
    append html "      linie = new THREE.Line(g, new THREE.LineBasicMaterial(\n"
    append html "        {color:art.farbe, transparent:true, opacity:.85}));\n"
    append html "    }\n"
    append html "    gruppe.add(linie);\n"
    append html "  });\n"
    append html "\n"
    append html "  szene.add(gruppe);\n"
    append html "\n"
    append html "  var leg = document.getElementById(\"legende\");\n"
    append html "  (SPEC.kantenarten || []).forEach(function(a){\n"
    append html "    var s = document.createElement(\"span\");\n"
    append html "    s.innerHTML = '<i class=\"strich\" style=\"border-top-color:' + a.farbe +\n"
    append html "                  ';border-top-style:' + (a.stil === \"gestrichelt\" ? \"dashed\" : \"solid\") +\n"
    append html "                  '\"></i>' + a.text;\n"
    append html "    leg.appendChild(s);\n"
    append html "  });\n"
    append html "\n"
    append html "  // ------------------------------------------------------------- Auswahl ---\n"
    append html "  var aktiv = -1;\n"
    append html "  function waehle(i){\n"
    append html "    if (aktiv >= 0){\n"
    append html "      knoten[aktiv].mat.color.copy(knoten[aktiv].farbe);\n"
    append html "      knoten[aktiv].mat.emissive.setHex(0x000000);\n"
    append html "      knoten[aktiv].mesh.scale.set(1,1,1);\n"
    append html "    }\n"
    append html "    aktiv = ((i % knoten.length) + knoten.length) % knoten.length;\n"
    append html "    var k = knoten[aktiv];\n"
    append html "    k.mat.emissive.setHex(0x333333);\n"
    append html "    k.mesh.scale.set(1.1, 1.5, 1.1);\n"
    append html "    document.getElementById(\"k-name\").textContent = k.name;\n"
    append html "    document.getElementById(\"k-sub\").textContent = k.untertitel || \"—\";\n"
    append html "    document.getElementById(\"k-schicht\").textContent = k.schicht;\n"
    append html "    document.getElementById(\"k-id\").textContent = k.id;\n"
    append html "  }\n"
    append html "\n"
    append html "  var strahl = new THREE.Raycaster(), zeiger = new THREE.Vector2();\n"
    append html "  renderer.domElement.addEventListener(\"click\", function(e){\n"
    append html "    if (gezogen) return;\n"
    append html "    var r = renderer.domElement.getBoundingClientRect();\n"
    append html "    zeiger.x = ((e.clientX - r.left) / r.width) * 2 - 1;\n"
    append html "    zeiger.y = -((e.clientY - r.top) / r.height) * 2 + 1;\n"
    append html "    strahl.setFromCamera(zeiger, kamera);\n"
    append html "    var treffer = strahl.intersectObjects(klickbar, false);\n"
    append html "    if (treffer.length) waehle(treffer[0].object.userData.index);\n"
    append html "  });\n"
    append html "  document.getElementById(\"btn-prev\").addEventListener(\"click\", function(){ waehle(aktiv - 1); });\n"
    append html "  document.getElementById(\"btn-next\").addEventListener(\"click\", function(){ waehle(aktiv + 1); });\n"
    append html "\n"
    append html "  // ------------------------------------------------------------- Kamera ----\n"
    append html "  var azimut = Math.PI/4, elevation = 0.62, rotiert = true;\n"
    append html "  function stelle(){\n"
    append html "    var x = radius*Math.cos(elevation)*Math.sin(azimut);\n"
    append html "    var y = radius*Math.sin(elevation);\n"
    append html "    var z = radius*Math.cos(elevation)*Math.cos(azimut);\n"
    append html "    kamera.position.set(x, y, z); kamera.lookAt(0, 0, 0);\n"
    append html "  }\n"
    append html "  var zieht = false, gezogen = false, lx = 0, ly = 0;\n"
    append html "  renderer.domElement.addEventListener(\"pointerdown\", function(e){\n"
    append html "    zieht = true; gezogen = false; lx = e.clientX; ly = e.clientY;\n"
    append html "  });\n"
    append html "  window.addEventListener(\"pointermove\", function(e){\n"
    append html "    if (!zieht) return;\n"
    append html "    if (Math.abs(e.clientX-lx) + Math.abs(e.clientY-ly) > 3){ gezogen = true; rotiert = false; }\n"
    append html "    azimut -= (e.clientX - lx) * 0.006;\n"
    append html "    elevation = Math.max(0.08, Math.min(1.45, elevation + (e.clientY - ly) * 0.005));\n"
    append html "    lx = e.clientX; ly = e.clientY;\n"
    append html "  });\n"
    append html "  window.addEventListener(\"pointerup\", function(){ zieht = false; setTimeout(function(){ gezogen = false; }, 0); });\n"
    append html "\n"
    append html "  function zoom(f){\n"
    append html "    if (iso){ D = Math.max(11, Math.min(54, D * f)); groesse(); }\n"
    append html "    else { radius = Math.max(32, Math.min(160, radius * f)); }\n"
    append html "  }\n"
    append html "  document.getElementById(\"btn-plus\").addEventListener(\"click\", function(){ zoom(0.85); });\n"
    append html "  document.getElementById(\"btn-minus\").addEventListener(\"click\", function(){ zoom(1.18); });\n"
    append html "  renderer.domElement.addEventListener(\"wheel\", function(e){\n"
    append html "    e.preventDefault(); zoom(e.deltaY > 0 ? 1.08 : 0.93);\n"
    append html "  }, {passive:false});\n"
    append html "  document.getElementById(\"btn-reset\").addEventListener(\"click\", function(){\n"
    append html "    azimut = Math.PI/4; elevation = 0.62; D = 26; radius = 82; rotiert = true;\n"
    append html "    iso = true; kamera = kameraIso;\n"
    append html "    document.getElementById(\"btn-iso\").setAttribute(\"aria-pressed\", \"true\");\n"
    append html "    document.getElementById(\"btn-iso\").textContent = \"Iso\";\n"
    append html "    waehle(0); groesse();\n"
    append html "  });\n"
    append html "  document.getElementById(\"btn-iso\").addEventListener(\"click\", function(){\n"
    append html "    iso = !iso; kamera = iso ? kameraIso : kameraPersp;\n"
    append html "    this.setAttribute(\"aria-pressed\", String(iso));\n"
    append html "    this.textContent = iso ? \"Iso\" : \"Persp\";\n"
    append html "    groesse();\n"
    append html "  });\n"
    append html "\n"
    append html "  function groesse(){\n"
    append html "    var w = buehne.clientWidth, h = buehne.clientHeight;\n"
    append html "    aspekt = w / h;\n"
    append html "    kameraIso.left = -D*aspekt; kameraIso.right = D*aspekt;\n"
    append html "    kameraIso.top = D; kameraIso.bottom = -D; kameraIso.updateProjectionMatrix();\n"
    append html "    kameraPersp.aspect = aspekt; kameraPersp.updateProjectionMatrix();\n"
    append html "    renderer.setSize(w, h, false);\n"
    append html "  }\n"
    append html "  window.addEventListener(\"resize\", groesse);\n"
    append html "\n"
    append html "  groesse();\n"
    append html "  waehle(0);\n"
    append html "  (function schleife(){\n"
    append html "    requestAnimationFrame(schleife);\n"
    append html "    if (rotiert) azimut += 0.003;\n"
    append html "    stelle();\n"
    append html "    renderer.render(szene, kamera);\n"
    append html "  })();\n"
    append html "})();\n"
    append html "</script>\n"
    append html "</body>\n"
    append html "</html>\n"
    return $html
}

# Main execution
if {$argc != 1} {
    puts "Usage: $argv0 <output-file>"
    exit 1
}

set output_file [lindex $argv 0]
set html_content [create_html]

if {[catch {open $output_file w} fd]} {
    puts "Error: Could not open file $output_file for writing"
    exit 1
}

puts -nonewline $fd $html_content
close $fd

puts "HTML file generated successfully: $output_file"
