#!/usr/bin/env tclsh
# style.css — portiert nach tcl
# Quelle: css, Projects@Vision-Check:Vision-Check/app/css/style.css
# Erzeugt: 2026-08-09 durch ABSTRACTIONS_MANAGER.py

# ═══════════════════════════════════════════════════════════
# Vision-Check — Design System
# Dark-Tech Theme | Analyse-Board Layout
# ═══════════════════════════════════════════════════════════

proc generateCSS {} {
    set css ""

    # Root variables
    append css "/* ═══════════════════════════════════════════════════════════\n"
    append css "   Vision-Check — Design System\n"
    append css "   Dark-Tech Theme | Analyse-Board Layout\n"
    append css "═══════════════════════════════════════════════════════════ */\n\n"
    
    append css ":root {\n"
    append css "  /* Farben */\n"
    append css "  --bg-deep:      #0a0f1e;\n"
    append css "  --bg-surface:   #111827;\n"
    append css "  --bg-card:      #1a2235;\n"
    append css "  --bg-hover:     #1f2d45;\n"
    append css "  --border:       rgba(99, 179, 237, 0.15);\n"
    append css "  --border-glow:  rgba(99, 179, 237, 0.4);\n\n"
    append css "  --accent:       #63b3ed;\n"
    append css "  --accent-2:     #4fd1c5;\n"
    append css "  --accent-warn:  #fbd38d;\n"
    append css "  --accent-ok:    #68d391;\n"
    append css "  --accent-err:   #fc8181;\n\n"
    append css "  --text-primary: #e2e8f0;\n"
    append css "  --text-muted:   #718096;\n"
    append css "  --text-dim:     #4a5568;\n\n"
    append css "  /* Schicht-Farben */\n"
    append css "  --layer-0: #805ad5; /* iNaturalist */\n"
    append css "  --layer-1: #4fd1c5; /* TensorFlow lokal */\n"
    append css "  --layer-2: #fbd38d; /* Canvas Filter */\n"
    append css "  --layer-3-gpt:    #68d391;\n"
    append css "  --layer-3-gemini: #63b3ed;\n"
    append css "  --layer-3-claude: #fc8181;\n\n"
    append css "  /* Spacing */\n"
    append css "  --radius:  8px;\n"
    append css "  --radius-l: 14px;\n"
    append css "  --gap:     12px;\n"
    append css "}\n\n"

    # Reset & Basis
    append css "/* ── Reset & Basis ── */\n"
    append css "*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\n\n"
    append css "html, body {\n"
    append css "  height: 100%;\n"
    append css "  background: var(--bg-deep);\n"
    append css "  color: var(--text-primary);\n"
    append css "  font-family: 'Inter', system-ui, -apple-system, sans-serif;\n"
    append css "  font-size: 14px;\n"
    append css "  line-height: 1.5;\n"
    append css "  overflow: hidden;\n"
    append css "}\n\n"

    # Header
    append css "/* ── Header ── */\n"
    append css "#app-header {\n"
    append css "  display: flex;\n"
    append css "  align-items: center;\n"
    append css "  justify-content: space-between;\n"
    append css "  padding: 10px 16px;\n"
    append css "  background: var(--bg-surface);\n"
    append css "  border-bottom: 1px solid var(--border);\n"
    append css "  height: 52px;\n"
    append css "  flex-shrink: 0;\n"
    append css "  z-index: 100;\n"
    append css "}\n\n"
    
    append css ".header-brand {\n"
    append css "  display: flex;\n"
    append css "  align-items: center;\n"
    append css "  gap: 8px;\n"
    append css "}\n\n"
    
    append css ".header-brand svg {\n"
    append css "  width: 28px; height: 28px;\n"
    append css "  color: var(--accent);\n"
    append css "}\n\n"
    
    append css ".header-brand h1 {\n"
    append css "  font-size: 16px;\n"
    append css "  font-weight: 700;\n"
    append css "  background: linear-gradient(90deg, var(--accent), var(--accent-2));\n"
    append css "  -webkit-background-clip: text;\n"
    append css "  -webkit-text-fill-color: transparent;\n"
    append css "  background-clip: text;\n"
    append css "}\n\n"
    
    append css ".header-controls {\n"
    append css "  display: flex;\n"
    append css "  align-items: center;\n"
    append css "  gap: 8px;\n"
    append css "}\n\n"

    # App Layout
    append css "/* ── App Layout (Board) ── */\n"
    append css "#app {\n"
    append css "  display: flex;\n"
    append css "  flex-direction: column;\n"
    append css "  height: 100vh;\n"
    append css "}\n\n"
    
    append css "#board {\n"
    append css "  display: grid;\n"
    append css "  grid-template-columns: 1fr 320px;\n"
    append css "  grid-template-rows: 1fr auto;\n"
    append css "  gap: var(--gap);\n"
    append css "  padding: var(--gap);\n"
    append css "  flex: 1;\n"
    append css "  overflow: hidden;\n"
    append css "}\n\n"

    # Kamera-Panel
    append css "/* ── Kamera-Panel (links, groß) ── */\n"
    append css "#camera-panel {\n"
    append css "  grid-column: 1;\n"
    append css "  grid-row: 1;\n"
    append css "  background: var(--bg-card);\n"
    append css "  border: 1px solid var(--border);\n"
    append css "  border-radius: var(--radius-l);\n"
    append css "  display: flex;\n"
    append css "  flex-direction: column;\n"
    append css "  overflow: hidden;\n"
    append css "  position: relative;\n"
    append css "}\n\n"
    
    append css ".panel-header {\n"
    append css "  display: flex;\n"
    append css "  align-items: center;\n"
    append css "  justify-content: space-between;\n"
    append css "  padding: 10px 14px;\n"
    append css "  border-bottom: 1px solid var(--border);\n"
    append css "  background: var(--bg-surface);\n"
    append css "  flex-shrink: 0;\n"
    append css "}\n\n"
    
    append css ".panel-title {\n"
    append css "  font-size: 12px;\n"
    append css "  font-weight: 600;\n"
    append css "  text-transform: uppercase;\n"
    append css "  letter-spacing: 0.08em;\n"
    append css "  color: var(--text-muted);\n"
    append css "}\n\n"
    
    append css ".badge {\n"
    append css "  display: inline-flex;\n"
    append css "  align-items: center;\n"
    append css "  gap: 4px;\n"
    append css "  padding: 2px 8px;\n"
    append css "  border-radius: 20px;\n"
    append css "  font-size: 10px;\n"
    append css "  font-weight: 600;\n"
    append css "  text-transform: uppercase;\n"
    append css "}\n\n"
    
    append css ".badge-live { background: rgba(104, 211, 145, 0.15); color: var(--accent-ok); }\n"
    append css ".badge-idle { background: rgba(113, 128, 150, 0.15); color: var(--text-muted); }\n"
    append css ".badge-loading { background: rgba(251, 211, 141, 0.15); color: var(--accent-warn); }\n\n"

    # Kamera-Viewport
    append css "/* Kamera-Viewport */\n"
    append css "#camera-viewport {\n"
    append css "  flex: 1;\n"
    append css "  display: flex;\n"
    append css "  align-items: center;\n"
    append css "  justify-content: center;\n"
    append css "  position: relative;\n"
    append css "  background: #000;\n"
    append css "  overflow: hidden;\n"
    append css "}\n\n"
    
    append css "#video {\n"
    append css "  width: 100%;\n"
    append css "  height: 100%;\n"
    append css "  object-fit: contain;\n"
    append css "  display: block;\n"
    append css "}\n\n"
    
    append css "#canvas-overlay {\n"
    append css "  position: absolute;\n"
    append css "  top: 0; left: 0;\n"
    append css "  width: 100%; height: 100%;\n"
    append css "  pointer-events: none;\n"
    append css "}\n\n"
    
    append css "#snap-canvas {\n"
    append css "  display: none;\n"
    append css "}\n\n"

    # Zoom-Lupe
    append css "/* Zoom-Lupe */\n"
    append css "#pixel-loupe {\n"
    append css "  position: absolute;\n"
    append css "  bottom: 16px;\n"
    append css "  right: 16px;\n"
    append css "  width: 160px;\n"
    append css "  height: 160px;\n"
    append css "  border: 2px solid var(--accent);\n"
    append css "  border-radius: var(--radius);\n"
    append css "  overflow: hidden;\n"
    append css "  background: #000;\n"
    append css "  display: none;\n"
    append css "  box-shadow: 0 0 20px rgba(99, 179, 237, 0.3);\n"
    append css "}\n\n"
    
    append css "#loupe-canvas {\n"
    append css "  width: 100%;\n"
    append css "  height: 100%;\n"
    append css "}\n\n"
    
    append css "#loupe-info {\n"
    append css "  position: absolute;\n"
    append css "  bottom: 0; left: 0; right: 0;\n"
    append css "  background: rgba(0,0,0,0.8);\n"
    append css "  padding: 4px 6px;\n"
    append css "  font-size: 10px;\n"
    append css "  font-family: 'JetBrains Mono', monospace;\n"
    append css "  color: var(--accent);\n"
    append css "  text-align: center;\n"
    append css "}\n\n"

    # Kamera-Steuerleiste
    append css "/* Kamera-Steuerleiste */\n"
    append css "#camera-controls {\n"
    append css "  padding: 10px 14px;\n"
    append css "  border-top: 1px solid var(--border);\n"
    append css "  display: flex;\n"
    append css "  align-items: center;\n"
    append css "  gap: 8px;\n"
    append css "  flex-wrap: wrap;\n"
    append css "  background: var(--bg-surface);\n"
    append css "  flex-shrink: 0;\n"
    append css "}\n\n"

    # Rechtes Panel
    append css "/* ── Rechtes Panel ── */\n"
    append css "#right-panel {\n"
    append css "  grid-column: 2;\n"
    append css "  grid-row: 1 / 3;\n"
    append css "  display: flex;\n"
    append css "  flex-direction: column;\n"
    append css "  gap: var(--gap);\n"
    append css "  overflow-y: auto;\n"
    append css "  padding-right: 2px;\n"
    append css "}\n\n"
    
    append css "#right-panel::-webkit-scrollbar { width: 4px; }\n"
    append css "#right-panel::-webkit-scrollbar-track { background: transparent; }\n"
    append css "#right-panel::-webkit-scrollbar-thumb { background: var(--border); border-radius: 2px; }\n\n"

    # Cards
    append css "/* ── Cards ── */\n"
    append css ".card {\n"
    append css "  background: var(--bg-card);\n"
    append css "  border: 1px solid var(--border);\n"
    append css "  border-radius: var(--radius-l);\n"
    append css "  overflow: hidden;\n"
    append css "}\n\n"
    
    append css ".card-body {\n"
    append css "  padding: 12px 14px;\n"
    append css "}\n\n"

    # Filter-Panel
    append css "/* ── Filter-Panel ── */\n"
    append css ".slider-row {\n"
    append css "  display: flex;\n"
    append css "  align-items: center;\n"
    append css "  gap: 8px;\n"
    append css "  margin-bottom: 10px;\n"
    append css "}\n\n"
    
    append css ".slider-row:last-child { margin-bottom: 0; }\n\n"
    
    append css ".slider-label {\n"
    append css "  width: 90px;\n"
    append css "  font-size: 11px;\n"
    append css "  color: var(--text-muted);\n"
    append css "  flex-shrink: 0;\n"
    append css "}\n\n"
    
    append css ".slider-row input[type=\"range\"] {\n"
    append css "  flex: 1;\n"
    append css "  -webkit-appearance: none;\n"
    append css "  height: 4px;\n"
    append css "  border-radius: 2px;\n"
    append css "  background: var(--bg-deep);\n"
    append css "  outline: none;\n"
    append css "  cursor: pointer;\n"
    append css "}\n\n"
    
    append css ".slider-row input[type=\"range\"]::-webkit-slider-thumb {\n"
    append css "  -webkit-appearance: none;\n"
    append css "  width: 14px;\n"
    append css "  height: 14px;\n"
    append css "  border-radius: 50%;\n"
    append css "  background: var(--accent);\n"
    append css "  border: 2px solid var(--bg-card);\n"
    append css "  cursor: pointer;\n"
    append css "  transition: transform 0.15s;\n"
    append css "}\n\n"
    
    append css ".slider-row input[type=\"range\"]::-webkit-slider-thumb:hover {\n"
    append css "  transform: scale(1.2);\n"
    append css "}\n\n"
    
    append css ".slider-value {\n"
    append css "  width: 32px;\n"
    append css "  font-size: 11px;\n"
    append css "  color: var(--accent);\n"
    append css "  font-family: monospace;\n"
    append css "  text-align: right;\n"
    append css "  flex-shrink: 0;\n"
    append css "}\n\n"

    # Analyse-Results
    append css "/* ── Analyse-Results ── */\n"
    append css ".result-block {\n"
    append css "  margin-bottom: 12px;\n"
    append css "  padding: 10px;\n"
    append css "  background: var(--bg-surface);\n"
    append css "  border: 1px solid var(--border);\n"
    append css "  border-radius: var(--radius);\n"
    append css "}\n\n"
    
    append css ".result-block:last-child { margin-bottom: 0; }\n\n"
    
    append css ".result-header {\n"
    append css "  display: flex;\n"
    append css "  align-items: center;\n"
    append css "  justify-content: space-between;\n"
    append css "  margin-bottom: 6px;\n"
    append css "}\n\n"
    
    append css ".layer-tag {\n"
    append css "  display: inline-flex;\n"
    append css "  align-items: center;\n"
    append css "  gap: 5px;\n"
    append css "  font-size: 10px;\n"
    append css "  font-weight: 700;\n"
    append css "  text-transform: uppercase;\n"
    append css "  letter-spacing: 0.06em;\n"
    append css "}\n\n"
    
    append css ".result-text {\n"
    append css "  font-size: 12px;\n"
    append css "  color: var(--text-primary);\n"
    append css "  line-height: 1.6;\n"
    append css "  white-space: pre-wrap;\n"
    append css "}\n\n"
    
    append css ".detection-item {\n"
    append css "  display: flex;\n"
    append css "  align-items: center;\n"
    append css "  justify-content: space-between;\n"
    append css "  padding: 4px 0;\n"
    append css "  border-bottom: 1px solid var(--border);\n"
    append css "  font-size: 12px;\n"
    append css "}\n\n"
    
    append css ".detection-item:last-child { border-bottom: none; }\n\n"
    
    append css ".detection-class {\n"
    append css "  font-weight: 600;\n"
    append css "  color: var(--layer-1);\n"
    append css "}\n\n"
    
    append css ".confidence-bar {\n"
    append css "  display: flex;\n"
    append css "  align-items: center;\n"
    append css "  gap: 6px;\n"
    append css "}\n\n"
    
    append css ".confidence-track {\n"
    append css "  width: 60px;\n"
    append css "  height: 4px;\n"
    append css "  background: var(--bg-deep);\n"
    append css "  border-radius: 2px;\n"
    append css "  overflow: hidden;\n"
    append css "}\n\n"
    
    append css ".confidence-fill {\n"
    append css "  height: 100%;\n"
    append css "  background: var(--accent-ok);\n"
    append css "  border-radius: 2px;\n"
    append css "  transition: width 0.3s;\n"
    append css "}\n\n"
    
    append css ".confidence-pct {\n"
    append css "  font-size: 10px;\n"
    append css "  color: var(--text-muted);\n"
    append css "  width: 32px;\n"
    append css "  text-align: right;\n"
    append css "}\n\n"

    # Pixel-Inspector
    append css "/* ── Pixel-Inspector ── */\n"
    append css "#pixel-info {\n"
    append css "  display: flex;\n"
    append css "  gap: 8px;\n"
    append css "  align-items: center;\n"
    append css "}\n\n"
    
    append css ".pixel-swatch {\n"
    append css "  width: 36px;\n"
    append css "  height: 36px;\n"
    append css "  border-radius: var(--radius);\n"
    append css "  border: 2px solid var(--border);\n"
    append css "  flex-shrink: 0;\n"
    append css "}\n\n"
    
    append css ".pixel-values {\n"
    append css "  display: flex;\n"
    append css "  flex-direction: column;\n"
    append css "  gap: 2px;\n"
    append css "}\n\n"
    
    append css ".pixel-values span {\n"
    append css "  font-size: 11px;\n"
    append css "  font-family: 'JetBrains Mono', monospace;\n"
    append css "  color: var(--text-primary);\n"
    append css "}\n\n"

    # Buttons
    append css "/* ── Buttons ── */\n"
    append css ".btn {\n"
    append css "  display: inline-flex;\n"
    append css "  align-items: center;\n"
    append css "  gap: 6px;\n"
    append css "  padding: 7px 14px;\n"
    append css "  border: 1px solid var(--border);\n"
    append css "  border-radius: var(--radius);\n"
    append css "  background: var(--bg-surface);\n"
    append css "  color: var(--text-primary);\n"
    append css "  font-size: 12px;\n"
    append css "  font-weight: 500;\n"
    append css "  cursor: pointer;\n"
    append css "  transition: all 0.2s;\n"
    append css "  white-space: nowrap;\n"
    append css "}\n\n"
    
    append css ".btn:hover {\n"
    append css "  background: var(--bg-hover);\n"
    append css "  border-color: var(--border-glow);\n"
    append css "}\n\n"
    
    append css ".btn:disabled {\n"
    append css "  opacity: 0.4;\n"
    append css "  cursor: not-allowed;\n"
    append css "}\n\n"
    
    append css ".btn-primary {\n"
    append css "  background: rgba(99, 179, 237, 0.15);\n"
    append css "  border-color: var(--accent);\n"
    append css "  color: var(--accent);\n"
    append css "}\n\n"
    
    append css ".btn-primary:hover {\n"
    append css "  background: rgba(99, 179, 237, 0.25);\n"
    append css "}\n\n"
    
    append css ".btn-snap {\n"
    append css "  background: rgba(104, 211, 145, 0.15);\n"
    append css "  border-color: var(--accent-ok);\n"
    append css "  color: var(--accent-ok);\n"
    append css "  padding: 9px 20px;\n"
    append css "  font-size: 13px;\n"
    append css "  font-weight: 600;\n"
    append css "}\n\n"
    
    append css ".btn-snap:hover {\n"
    append css "  background: rgba(104, 211, 145, 0.25);\n"
    append css "}\n\n"
    
    append css ".btn-danger {\n"
    append css "  background: rgba(252, 129, 129, 0.1);\n"
    append css "  border-color: var(--accent-err);\n"
    append css "  color: var(--accent-err);\n"
    append css "}\n\n"
    
    append css ".btn-sm {\n"
    append css "  padding: 4px 10px;\n"
    append css "  font-size: 11px;\n"
    append css "}\n\n"
    
    append css ".btn-icon {\n"
    append css "  padding: 7px;\n"
    append css "  border-radius: var(--radius);\n"
    append css "}\n\n"

    # Select
    append css "/* ── Select ── */\n"
    append css "select {\n"
    append css "  background: var(--bg-surface);\n"
    append css "  border: 1px solid var(--border);\n"
    append css "  color: var(--text-primary);\n"
    append css "  border-radius: var(--radius);\n"
    append css "  padding: 6px 10px;\n"
    append css "  font-size: 12px;\n"
    append css "  cursor: pointer;\n"
    append css "  outline: none;\n"
    append css "  transition: border-color 0.2s;\n"
    append css "}\n\n"
    
    append css "select:hover, select:focus {\n"
    append css "  border-color: var(--border-glow);\n"
    append css "}\n\n"

    # Spinner
    append css "/* ── Spinner ── */\n"
    append css ".spinner {\n"
    append css "  width: 16px;\n"
    append css "  height: 16px;\n"
    append css "  border: 2px solid var(--border);\n"
    append css "  border-top-color: var(--accent);\n"
    append css "  border-radius: 50%;\n"
    append css "  animation: spin 0.7s linear infinite;\n"
    append css "  flex-shrink: 0;\n"
    append css "}\n\n"
    
    append css "@keyframes spin { to { transform: rotate(360deg); } }\n\n"

    # Settings Modal
    append css "/* ── Settings Modal ── */\n"
    append css "#settings-modal {\n"
    append css "  display: none;\n"
    append css "  position: fixed;\n"
    append css "  inset: 0;\n"
    append css "  background: rgba(0,0,0,0.7);\n"
    append css "  z-index: 200;\n"
    append css "  align-items: center;\n"
    append css "  justify-content: center;\n"
    append css "  backdrop-filter: blur(4px);\n"
    append css "}\n\n"
    
    append css "#settings-modal.open {\n"
    append css "  display: flex;\n"
    append css "}\n\n"
    
    append css ".modal-box {\n"
    append css "  background: var(--bg-card);\n"
    append css "  border: 1px solid var(--border-glow);\n"
    append css "  border-radius: var(--radius-l);\n"
    append css "  padding: 24px;\n"
    append css "  width: 480px;\n"
    append css "  max-width: calc(100vw - 32px);\n"
    append css "  max-height: 80vh;\n"
    append css "  overflow-y: auto;\n"
    append css "}\n\n"
    
    append css ".modal-title {\n"
    append css "  font-size: 16px;\n"
    append css "  font-weight: 700;\n"
    append css "  color: var(--accent);\n"
    append css "  margin-bottom: 20px;\n"
    append css "}\n\n"
    
    append css ".settings-section {\n"
    append css "  margin-bottom: 20px;\n"
    append css "}\n\n"
    
    append css ".settings-label {\n"
    append css "  display: block;\n"
    append css "  font-size: 11px;\n"
    append css "  font-weight: 600;\n"
    append css "  text-transform: uppercase;\n"
    append css "  letter-spacing: 0.08em;\n"
    append css "  color: var(--text-muted);\n"
    append css "  margin-bottom: 6px;\n"
    append css "}\n\n"
    
    append css ".settings-input {\n"
    append css "  width: 100%;\n"
    append css "  background: var(--bg-deep);\n"
    append css "  border: 1px solid var(--border);\n"
    append css "  color: var(--text-primary);\n"
    append css "  border-radius: var(--radius);\n"
    append css "  padding: 8px 12px;\n"
    append css "  font-size: 12px;\n"
    append css "  font-family: 'JetBrains Mono', monospace;\n"
    append css "  outline: none;\n"
    append css "  transition: border-color 0.2s;\n"
    append css "}\n\n"
    
    append css ".settings-input:focus {\n"
    append css "  border-color: var(--accent);\n"
    append css "}\n\n"
    
    append css ".settings-hint {\n"
    append css "  font-size: 10px;\n"
    append css "  color: var(--text-dim);\n"
    append css "  margin-top: 4px;\n"
    append css "}\n\n"
    
    append css ".settings-section-title {\n"
    append css "  font-size: 13px;\n"
    append css "  font-weight: 600;\n"
    append css "  color: var(--text-primary);\n"
    append css "  margin-bottom: 12px;\n"
    append css "  padding-bottom: 8px;\n"
    append css "  border-bottom: 1px solid var(--border);\n"
    append css "}\n\n"

    # Snapshot Preview
    append css "/* ── Snapshot Preview ── */\n"
    append css "#snapshot-area {\n"
    append css "  display: none;\n"
    append css "}\n\n"
    
    append css "#snapshot-preview {\n"
    append css "  width: 100%;\n"
    append css "  border-radius: var(--radius);\n"
    append css "  border: 1px solid var(--border);\n"
    append css "}\n\n"

    # Bottom-Statusleiste
    append css "/* ── Bottom-Statusleiste ── */\n"
    append css "#status-bar {\n"
    append css "  grid-column: 1;\n"
    append css "  grid-row: 2;\n"
    append css "  background: var(--bg-surface);\n"
    append css "  border: 1px solid var(--border);\n"
    append css "  border-radius: var(--radius);\n"
    append css "  padding: 6px 12px;\n"
    append css "  display: flex;\n"
    append css "  align-items: center;\n"
    append css "  gap: 12px;\n"
    append css "  font-size: 11px;\n"
    append css "  color: var(--text-muted);\n"
    append css "  flex-shrink: 0;\n"
    append css "}\n\n"
    
    append css ".status-dot {\n"
    append css "  width: 6px;\n"
    append css "  height: 6px;\n"
    append css "  border-radius: 50%;\n"
    append css "  background: var(--text-dim);\n"
    append css "  flex-shrink: 0;\n"
    append css "}\n\n"
    
    append css ".status-dot.ok { background: var(--accent-ok); box-shadow: 0 0 6px var(--accent-ok); }\n"
    append css ".status-dot.warn { background: var(--accent-warn); }\n"
    append css ".status-dot.err { background: var(--accent-err); }\n\n"
    
    append css "#status-text { flex: 1; }\n\n"

    # Layer-Indicator
    append css "/* ── Layer-Indicator ── */\n"
    append css ".layer-indicator {\n"
    append css "  display: flex;\n"
    append css "  gap: 4px;\n"
    append css "  align-items: center;\n"
    append css "}\n\n"
    
    append css ".layer-dot {\n"
    append css "  width: 8px;\n"
    append css "  height: 8px;\n"
    append css "  border-radius: 50%;\n"
    append css "  opacity: 0.3;\n"
    append css "  transition: opacity 0.3s, box-shadow 0.3s;\n"
    append css "}\n\n"
    
    append css ".layer-dot.active {\n"
    append css "  opacity: 1;\n"
    append css "  box-shadow: 0 0 6px currentColor;\n"
    append css "}\n\n"

    # Analyse-Tabs
    append css "/* ── Analyse-Tabs ── */\n"
    append css ".tab-bar {\n"
    append css "  display: flex;\n"
    append css "  gap: 2px;\n"
    append css "  padding: 8px 14px;\n"
    append css "  border-bottom: 1px solid var(--border);\n"
    append css "  background: var(--bg-surface
