#!/usr/bin/env tclsh
# viewer.html — portiert nach tcl
# Quelle: html, Projects@Telegram-Monitor:plugin/extension/viewer.html
# Erzeugt: 2026-08-19 durch ABSTRACTIONS_MANAGER.py

# Portierung von viewer.html nach Tcl 8.6
# Erzeugt das HTML-Dokument dynamisch und schreibt es in eine Datei

proc generate_html {} {
    set html {}

    # DOCTYPE und HTML-Grundstruktur
    append html "<!DOCTYPE html>\n"
    append html "<html lang=\"de\">\n"
    append html "<head>\n"
    append html "<meta charset=\"utf-8\">\n"
    append html "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    append html "<title>TikTok Live Companion — Viewer</title>\n"
    
    # CSS Styles
    append html "<style>\n"
    append html "  :root{\n"
    append html "    --bg:#0f1115; --card:#171a21; --line:#262b36; --text:#f2f4f8; --muted:#9aa3b2;\n"
    append html "    --tt:#fe2c55; --ok:#22c55e; --warn:#f59e0b;\n"
    append html "    color-scheme: dark;\n"
    append html "  }\n"
    append html "  @media (prefers-color-scheme: light){\n"
    append html "    :root{ --bg:#f6f7f9; --card:#fff; --line:#e3e6ea; --text:#16191d; --muted:#6b7280; }\n"
    append html "  }\n"
    append html "  *{box-sizing:border-box}\n"
    append html "  body{margin:0;background:var(--bg);color:var(--text);\n"
    append html "       font:15px/1.5 -apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,sans-serif}\n"
    append html "  .wrap{max-width:1180px;margin:0 auto;padding:16px}\n"
    append html "  header{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin-bottom:12px}\n"
    append html "  h1{font-size:17px;margin:0;font-weight:650}\n"
    append html "  .badge{display:inline-flex;align-items:center;gap:6px;font-size:11.5px;font-weight:700;\n"
    append html "         padding:3px 10px;border-radius:99px;background:#2a2f3a;color:var(--muted)}\n"
    append html "  .badge.live{background:var(--tt);color:#fff}\n"
    append html "  .badge .dot{width:6px;height:6px;border-radius:50%;background:currentColor}\n"
    append html "  .badge.live .dot{animation:pulse 1.6s infinite}\n"
    append html "  @keyframes pulse{0%,100%{opacity:1}50%{opacity:.25}}\n"
    append html "  input,select,button{font:inherit;border-radius:8px;border:1px solid var(--line);\n"
    append html "                      background:var(--card);color:var(--text);padding:9px 12px}\n"
    append html "  input{min-width:220px}\n"
    append html "  button{cursor:pointer;font-weight:600}\n"
    append html "  button.primary{background:var(--tt);border-color:var(--tt);color:#fff}\n"
    append html "  .row{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin-bottom:10px}\n"
    append html "  .grid{display:grid;grid-template-columns:minmax(0,2fr) minmax(280px,1fr);gap:14px}\n"
    append html "  @media (max-width:900px){ .grid{grid-template-columns:1fr} }\n"
    append html "  .card{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:14px}\n"
    append html "  .player{position:relative;width:100%;aspect-ratio:9/16;max-height:80vh;background:#000;\n"
    append html "          border-radius:12px;overflow:hidden;border:1px solid var(--line)}\n"
    append html "  .player iframe{position:absolute;inset:0;width:100%;height:100%;border:0}\n"
    append html "  .ph{position:absolute;inset:0;display:flex;flex-direction:column;gap:10px;\n"
    append html "      align-items:center;justify-content:center;color:var(--muted);text-align:center;padding:26px}\n"
    append html "  h2{font-size:11.5px;text-transform:uppercase;letter-spacing:.05em;color:var(--muted);\n"
    append html "     margin:0 0 8px;font-weight:650}\n"
    append html "  .meta{color:var(--muted);font-size:13px}\n"
    append html "  .strong{color:var(--text);font-weight:600}\n"
    append html "  .stream{display:flex;gap:10px;padding:6px 0;border-bottom:1px solid var(--line);font-size:13px}\n"
    append html "  .stream:last-child{border-bottom:0}\n"
    append html "  .stream .when{color:var(--muted);white-space:nowrap;font-variant-numeric:tabular-nums}\n"
    append html "  .stream .t{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}\n"
    append html "  .stream.now{color:var(--tt);font-weight:650}\n"
    append html "  .hint{font-size:12.5px;color:var(--muted);line-height:1.45;margin-top:10px}\n"
    append html "  a{color:var(--tt)} a:hover{text-decoration:underline}\n"
    append html "  code{background:rgba(127,127,127,.15);padding:1px 5px;border-radius:4px;font-size:12.5px;\n"
    append html "       font-family:ui-monospace,SFMono-Regular,Menlo,monospace}\n"
    append html "</style>\n"
    append html "</head>\n"
    append html "<body>\n"
    append html "<div class=\"wrap\">\n"
    append html "  <header>\n"
    append html "    <h1>TikTok Live Companion — Viewer</h1>\n"
    append html "    <span class=\"badge\" id=\"badge\"><span class=\"dot\"></span><span id=\"badgeText\">bereit</span></span>\n"
    append html "    <span class=\"meta\" id=\"checked\"></span>\n"
    append html "  </header>\n"
    append html "\n"
    append html "  <div class=\"row\">\n"
    append html "    <input id=\"user\" placeholder=\"@name eingeben — beliebiges öffentliches Konto\" autofocus>\n"
    append html "    <button class=\"primary\" id=\"go\">Anzeigen</button>\n"
    append html "    <button id=\"clear\">Leeren</button>\n"
    append html "    <select id=\"every\">\n"
    append html "      <option value=\"0\" selected>Status: nur manuell</option>\n"
    append html "      <option value=\"60\">Status alle 60 s</option>\n"
    append html "      <option value=\"120\">alle 2 min</option>\n"
    append html "      <option value=\"300\">alle 5 min</option>\n"
    append html "    </select>\n"
    append html "    <input id=\"api\" placeholder=\"Monitor, z. B. http://127.0.0.1:8765 (optional)\" style=\"min-width:270px\">\n"
    append html "  </div>\n"
    append html "\n"
    append html "  <div class=\"grid\">\n"
    append html "    <div>\n"
    append html "      <div class=\"player\" id=\"player\">\n"
    append html "        <div class=\"ph\" id=\"ph\">\n"
    append html "          <div style=\"font-size:34px\">📺</div>\n"
    append html "          <div id=\"phText\">Namen eintragen und „Anzeigen“ drücken —<br>der Player startet sofort.</div>\n"
    append html "        </div>\n"
    append html "      </div>\n"
    append html "      <p class=\"hint\">\n"
    append html "        Eingebettet wird der offizielle TikTok-Live-Player\n"
    append html "        <code id=\"curUrl\">tiktok.com/embed/live/@name</code> — <b>keine Anmeldung,\n"
    append html "        keine Geschenk- oder Kauf-Oberfläche</b>. Ist das Konto offline, zeigt der\n"
    append html "        Rahmen eine Fehlerseite von TikTok; das ist das Offline-Zeichen.\n"
    append html "      </p>\n"
    append html "    </div>\n"
    append html "\n"
    append html "    <div>\n"
    append html "      <div class=\"card\">\n"
    append html "        <h2>Aufruf</h2>\n"
    append html "        <div class=\"meta\" id=\"links\">noch kein Konto gewählt</div>\n"
    append html "      </div>\n"
    append html "\n"
    append html "      <div class=\"card\" style=\"margin-top:12px\">\n"
    append html "        <h2>Status</h2>\n"
    append html "        <div class=\"meta\" id=\"status\">\n"
    append html "          Läuft gerade / seit wann / letzte Sendungen kommen aus dem lokalen Monitor.\n"
    append html "          Ohne ihn zeigt diese Seite nur den Player — eine lokale Datei darf im\n"
    append html "          Browser keine fremden Server abfragen.\n"
    append html "        </div>\n"
    append html "        <div class=\"hint\">\n"
    append html "          Monitor starten: <code>python server.py --poll-interval 120</code> im\n"
    append html "          Projektordner, dann oben <code>http://127.0.0.1:8765</code> eintragen\n"
    append html "          und „Anzeigen“ drücken.\n"
    append html "        </div>\n"
    append html "      </div>\n"
    append html "\n"
    append html "      <div class=\"card\" style=\"margin-top:12px\">\n"
    append html "        <h2>Letzte Sendungen</h2>\n"
    append html "        <div class=\"meta\" id=\"streams\">—</div>\n"
    append html "      </div>\n"
    append html "    </div>\n"
    append html "  </div>\n"
    append html "</div>\n"
    append html "\n"
    
    # JavaScript
    append html "<script>\n"
    append html "const \$ = s => document.querySelector(s);\n"
    append html "const esc = s => String(s ?? '').replace(/[&<>\"']/g, c =>\n"
    append html "  ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));\n"
    append html "const num = n => n == null ? '?' : Number(n).toLocaleString('de-DE');\n"
    append html "const clean = s => String(s || '').trim()\n"
    append html "  .replace(/^https?:\\/\\/(www\\.)?tiktok\\.com\\/@@?/i, '')\n"
    append html "  .replace(/\\/live.*\$/i, '').replace(/^@@/, '').trim();\n"
    append html "\n"
    append html "let timer = null;\n"
    append html "\n"
    append html "function embedUrl(user){\n"
    append html "  return 'https://www.tiktok.com/embed/live/@@' + encodeURIComponent(user);\n"
    append html "}\n"
    append html "\n"
    append html "/* Player sofort einbetten — ohne jede Statusabfrage. */\n"
    append html "function mount(user){\n"
    append html "  const holder = \$('#player');\n"
    append html "  holder.querySelectorAll('iframe').forEach(f => f.remove());\n"
    append html "  const f = document.createElement('iframe');\n"
    append html "  f.src = embedUrl(user);\n"
    append html "  f.allow = 'autoplay; encrypted-media; picture-in-picture; fullscreen';\n"
    append html "  f.referrerPolicy = 'origin';\n"
    append html "  f.title = 'TikTok Live von @@' + user;\n"
    append html "  holder.appendChild(f);\n"
    append html "  \$('#ph').style.display = 'none';\n"
    append html "  \$('#curUrl').textContent = 'tiktok.com/embed/live/@@' + user;\n"
    append html "  \$('#links').innerHTML =\n"
    append html "    '<div class=\"strong\">@@' + esc(user) + '</div>' +\n"
    append html "    '<div style=\"margin-top:6px\">' +\n"
    append html "    '<a href=\"https://www.tiktok.com/@@' + esc(user) + '/live\" target=\"_blank\" rel=\"noopener\">Live-Seite</a> · ' +\n"
    append html "    '<a href=\"https://www.tiktok.com/@@' + esc(user) + '\" target=\"_blank\" rel=\"noopener\">Profil</a> · ' +\n"
    append html "    '<a href=\"' + esc(embedUrl(user)) + '\" target=\"_blank\" rel=\"noopener\">Player einzeln</a></div>';\n"
    append html "}\n"
    append html "\n"
    append html "function setBadge(live){\n"
    append html "  \$('#badge').className = 'badge' + (live === true ? ' live' : '');\n"
    append html "  \$('#badgeText').textContent = live === true ? 'LIVE'\n"
    append html "    : (live === false ? 'offline' : 'Status unbekannt');\n"
    append html "}\n"
    append html "\n"
    append html "/* Status nur, wenn ein Monitor eingetragen ist. */\n"
    append html "async function fetchStatus(user){\n"
    append html "  const base = \$('#api').value.trim().replace(/\\/+\$/, '');\n"
    append html "  if(!base){ setBadge(null); return; }\n"
    append html "  try{\n"
    append html "    const r = await fetch(base + '/api/tiktok/status?users=' + encodeURIComponent(user),\n"
    append html "                          { cache: 'no-store' });\n"
    append html "    if(!r.ok) throw new Error('HTTP ' + r.status);\n"
    append html "    const d = await r.json();\n"
    append html "    const st = (d.accounts || [])[0];\n"
    append html "    if(!st) throw new Error('keine Daten');\n"
    append html "    render(st);\n"
    append html "  }catch(e){\n"
    append html "    setBadge(null);\n"
    append html "    \$('#status').innerHTML = '<span style=\"color:var(--warn)\">Monitor nicht erreichbar (' +\n"
    append html "      esc(e.message) + ').</span><br>Der Player oben läuft davon unabhängig weiter.';\n"
    append html "  }\n"
    append html "}\n"
    append html "\n"
    append html "function render(st){\n"
    append html "  setBadge(st.live);\n"
    append html "  \$('#checked').textContent = st.checked_at\n"
    append html "    ? 'geprüft ' + new Date(st.checked_at).toLocaleTimeString('de-DE') : '';\n"
    append html "  \$('#status').innerHTML =\n"
    append html "    (st.title ? '<div class=\"strong\">' + esc(st.title) + '</div>' : '') +\n"
    append html "    (st.started_at ? '<div>Beginn ' + esc(st.started_at.replace('T',' ')) +\n"
    append html "      (st.since ? ' · seit ca. ' + esc(st.since) : '') + '</div>' : '') +\n"
    append html "    (st.last_seen ? '<div>zuletzt gesehen ' + esc(st.last_seen) + '</div>' : '') +\n"
    append html "    (st.streams_total ? '<div>' + num(st.streams_total) + ' Sendungen · ' +\n"
    append html "      esc(st.airtime || '') + ' · ' + num(st.active_days) + ' aktive Tage</div>' : '');\n"
    append html "  \$('#streams').innerHTML = (st.streams || []).length\n"
    append html "    ? st.streams.slice(0, 12).map(s =>\n"
    append html "        '<div class=\"stream' + (s.is_live ? ' now' : '') + '\">' +\n"
    append html "        '<span class=\"when\">' + esc(String(s.day).slice(5)) + ' ' + esc(s.time || '') + '</span>' +\n"
    append html "        '<span class=\"t\">' + esc(s.title || '(ohne Titel)') + '</span>' +\n"
    append html "        '<span class=\"when\">' + esc(s.duration || '') + '</span></div>').join('')\n"
    append html "    : 'keine Daten';\n"
    append html "}\n"
    append html "\n"
    append html "function start(){\n"
    append html "  const user = clean(\$('#user').value);\n"
    append html "  if(!user){ \$('#user').focus(); return; }\n"
    append html "  \$('#user').value = user;\n"
    append html "  try{\n"
    append html "    localStorage.setItem('ttv.user', user);\n"
    append html "    localStorage.setItem('ttv.api', \$('#api').value.trim());\n"
    append html "  }catch(e){}\n"
    append html "  mount(user);\n"
    append html "  fetchStatus(user);\n"
    append html "  if(timer) clearInterval(timer);\n"
    append html "  const every = parseInt(\$('#every').value, 10);\n"
    append html "  if(every > 0) timer = setInterval(() => fetchStatus(user), every * 1000);\n"
    append html "}\n"
    append html "\n"
    append html "\$('#go').onclick = start;\n"
    append html "\$('#user').addEventListener('keydown', e => { if(e.key === 'Enter') start(); });\n"
    append html "\$('#every').addEventListener('change', start);\n"
    append html "\$('#clear').onclick = () => {\n"
    append html "  if(timer) clearInterval(timer);\n"
    append html "  document.querySelectorAll('#player iframe').forEach(f => f.remove());\n"
    append html "  \$('#ph').style.display = '';\n"
    append html "  \$('#user').value = '';\n"
    append html "  \$('#links').textContent = 'noch kein Konto gewählt';\n"
    append html "  \$('#streams').textContent = '—';\n"
    append html "  \$('#curUrl').textContent = 'tiktok.com/embed/live/@@name';\n"
    append html "  setBadge(null);\n"
    append html "  try{ localStorage.removeItem('ttv.user'); }catch(e){}\n"
    append html "  \$('#user').focus();\n"
    append html "};\n"
    append html "\n"
    append html "/* Nichts fest eingebaut — nur das zuletzt selbst eingegebene Konto. */\n"
    append html "try{\n"
    append html "  const savedApi = localStorage.getItem('ttv.api');\n"
    append html "  if(savedApi) \$('#api').value = savedApi;\n"
    append html "  const savedUser = localStorage.getItem('ttv.user');\n"
    append html "  if(savedUser){ \$('#user').value = savedUser; start(); }\n"
    append html "}catch(e){}\n"
    append html "</script>\n"
    append html "</body>\n"
    append html "</html>\n"
    
    return $html
}

# Hauptprogramm
if {$argc != 1} {
    puts "Verwendung: $argv0 <ausgabedatei>"
    exit 1
}

set output_file [lindex $argv 0]
set html_content [generate_html]

# Schreibe HTML in Datei
if {[catch {open $output_file w} fid]} {
    puts "Fehler beim Öffnen der Datei $output_file: $fid"
    exit 1
}

puts -nonewline $fid $html_content
close $fid

puts "HTML-Datei erfolgreich erstellt: $output_file"
