name: TikTokLiveCompanion
options:
  bundleIdPrefix: app.tiktoklivecompanion
  deploymentTarget:
    iOS: "15.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "0.8.2"
    CURRENT_PROJECT_VERSION: 10
targets:
  TikTokLiveCompanion:
    type: application
    platform: iOS
    sources:
      - path: TikTokLiveCompanion
      - path: Resources
        buildPhase: resources
    info:
      path: TikTokLiveCompanion/Info.plist
    entitlements:
      path: TikTokLiveCompanion/TikTokLiveCompanion.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.tiktoklivecompanion.ios
        SWIFT_OBJC_BRIDGING_HEADER: TikTokLiveCompanion/TikTokLiveCompanion-Bridging-Header.h
        CLANG_ENABLE_OBJC_ARC: YES
  TikTokLiveCompanionTests:
    type: bundle.unit-test
    platform: iOS
    sources: [TikTokLiveCompanionTests]
    dependencies:
      - target: TikTokLiveCompanion
