#!/usr/bin/env pwsh
# 1781743218784_260531_209208.py — portiert nach powershell
# Quelle: python, Projects@abstractions:python/1781743218784_260531_209208.py
# Erzeugt: 2026-08-21 durch ABSTRACTIONS_MANAGER.py

# 1781743218784_260531.pl — portiert nach python
# Quelle: perl5, Projects@abstractions:perl5/1781743218784_260531.pl
# Erzeugt: 2026-08-18 durch ABSTRACTIONS_MANAGER.py

# 1781743218784.html — portiert nach tcl
# Quelle: html, Projects@secret-vault-public:secret-vault-public/versions/1781743218784.html
# Erzeugt: 2026-08-08 durch ABSTRACTIONS_MANAGER.py

# Tcl 8.6 script to generate the Secret Vault Public HTML file
# Usage: tclsh this_script.tcl output_file.html

param(
    [Parameter(Mandatory=$true)]
    [string]$OutputFile
)

try {
    $fp = [System.IO.File]::CreateText($OutputFile)
} catch {
    Write-Host "Could not open file '$OutputFile' $($_.Exception.Message)"
    exit 1
}

# Write DOCTYPE and main script tag
$fp.WriteLine('<!DOCTYPE html>')
$fp.WriteLine('<script type="application/json" id="cowork-artifact-meta">')
$fp.WriteLine('{')
$fp.WriteLine('  "name": "Secret Vault Public",')
$fp.WriteLine('  "schemaVersion": 1,')
$fp.WriteLine('  "description": "Secret-Vault Public als interaktives Browser-Artefakt: verschlüsselter Secret-Container vollständig client-seitig (WebCrypto, AES-256-GCM + PBKDF2). Öffnen/Anlegen, Anbieter/Felder ergänzen und ersetzen (Rotation), verschlüsseln und als .svpb herunterladen oder Klartext-JSON exportieren. DE/EN nach Browsersprache. Eigenes Format (nicht kompatibel mit dem scrypt-Python-Tool). Keine Secrets eingebettet.",')
$fp.WriteLine('  "mcpTools": [],')
$fp.WriteLine('  "mcpServerNames": []')
$fp.WriteLine('}')
$fp.WriteLine('</script>')

# Write HTML start and head section
$fp.WriteLine('<html lang="de">')
$fp.WriteLine('<head>')
$fp.WriteLine('<meta charset="utf-8">')
$fp.WriteLine('<meta name="viewport" content="width=device-width, initial-scale=1">')
$fp.WriteLine('<title>Secret-Vault Public</title>')
$fp.WriteLine('<style>')
$fp.WriteLine(':root{ color-scheme:light; --ink:#1b1c1f; --muted:#6c6e75; --faint:#9a9ca3; --card:#fff; --line:#e9eaee; --accent:#5b5bd6; --accent2:#7c5cff; --ok:#22a06b; --err:#e0533d; --radius:16px; --shadow:0 1px 2px rgba(20,20,40,.04),0 6px 20px rgba(20,20,40,.06);}')
$fp.WriteLine('*{box-sizing:border-box;}')
$fp.WriteLine('body{margin:0;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;color:var(--ink);min-height:100vh;background:radial-gradient(1100px 560px at 100% -10%,#e8ecff 0%,rgba(232,236,255,0) 55%),linear-gradient(180deg,#eef1f6,#f7f7f8 42%);background-attachment:fixed;}')
$fp.WriteLine('.wrap{max-width:820px;margin:0 auto;padding:24px 18px 70px;}')
$fp.WriteLine('.brand{display:flex;align-items:center;gap:12px;margin-bottom:4px;}')
$fp.WriteLine('.mark{width:32px;height:32px;border-radius:9px;background:linear-gradient(135deg,var(--accent),var(--accent2));box-shadow:0 4px 12px rgba(91,91,214,.35);position:relative;flex:0 0 auto;}')
$fp.WriteLine('.mark:after{content:"";position:absolute;inset:8px;border-radius:4px;border:2px solid rgba(255,255,255,.92);}')
$fp.WriteLine('h1{font-size:21px;margin:0;font-weight:700;}')
$fp.WriteLine('.sub{color:var(--muted);font-size:13px;margin:2px 0 16px;}')
$fp.WriteLine('.card{background:var(--card);border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow);padding:16px;margin-bottom:14px;}')
$fp.WriteLine('.card h2{font-size:14px;margin:0 0 10px;}')
$fp.WriteLine('label.lab{display:block;font-size:12px;font-weight:600;color:var(--muted);margin:8px 0 3px;}')
$fp.WriteLine('input,textarea{width:100%;font-size:13px;padding:8px 10px;border:1px solid var(--line);border-radius:9px;font-family:ui-monospace,Menlo,Consolas,monospace;background:#fff;}')
$fp.WriteLine('textarea{min-height:90px;white-space:pre;overflow:auto;}')
$fp.WriteLine('.row{display:flex;gap:8px;flex-wrap:wrap;align-items:center;}')
$fp.WriteLine('.btn{font-size:13px;font-weight:600;padding:8px 14px;border:1px solid var(--line);border-radius:10px;background:#fff;cursor:pointer;box-shadow:var(--shadow);transition:transform .1s;}')
$fp.WriteLine('.btn:hover{transform:translateY(-1px);}')
$fp.WriteLine('.btn.primary{background:linear-gradient(135deg,var(--accent),var(--accent2));color:#fff;border-color:transparent;}')
$fp.WriteLine('.btn.sm{padding:5px 9px;font-size:12px;}')
$fp.WriteLine('.msg{font-size:12px;margin-left:6px;}')
$fp.WriteLine('.msg.ok{color:var(--ok);} .msg.err{color:var(--err);}')
$fp.WriteLine('.prov{border:1px solid var(--line);border-radius:12px;padding:10px 12px;margin-bottom:10px;}')
$fp.WriteLine('.prov h3{margin:0 0 6px;font-size:13.5px;display:flex;align-items:center;gap:8px;}')
$fp.WriteLine('.kv{display:grid;grid-template-columns:180px 1fr auto;gap:6px;margin:4px 0;align-items:center;}')
$fp.WriteLine('.kv input{font-size:12px;padding:5px 7px;}')
$fp.WriteLine('.kv .k{color:var(--muted);font-weight:600;}')
$fp.WriteLine('.muted{color:var(--faint);font-size:13px;}')
$fp.WriteLine('.hide{display:none;}')
$fp.WriteLine('.foot{color:var(--faint);font-size:11.5px;text-align:center;margin-top:18px;line-height:1.5;}')
$fp.WriteLine('a{color:var(--accent);}')
$fp.WriteLine('</style>')
$fp.WriteLine('</head>')

# Write body content
$fp.WriteLine('<body>')
$fp.WriteLine('<div class="wrap">')
$fp.WriteLine('  <div class="brand"><div class="mark"></div><h1 id="title">Secret-Vault Public</h1></div>')
$fp.WriteLine('  <div class="sub" id="sub">Verschlüsselte Secret-Vault (AES-256-GCM, PBKDF2) — alles im Browser, kein Server.</div>')
$fp.WriteLine('')
$fp.WriteLine('  <div class="card">')
$fp.WriteLine('    <h2 id="h-open">Öffnen oder neu</h2>')
$fp.WriteLine('    <label class="lab" id="l-pass">Passphrase</label>')
$fp.WriteLine('    <input id="pass" type="password" placeholder="Passphrase…">')
$fp.WriteLine('    <label class="lab" id="l-file">Vault laden (Datei oder Base64 einfügen)</label>')
$fp.WriteLine('    <input id="file" type="file" accept=".svpb,.txt,.vault,.b64">')
$fp.WriteLine('    <textarea id="blob" placeholder="…oder Base64 hier einfügen"></textarea>')
$fp.WriteLine('    <div class="row" style="margin-top:10px">')
$fp.WriteLine('      <button class="btn primary" id="openBtn">Öffnen / Entschlüsseln</button>')
$fp.WriteLine('      <button class="btn" id="newBtn">Neuer leerer Vault</button>')
$fp.WriteLine('      <span class="msg" id="openMsg"></span>')
$fp.WriteLine('    </div>')
$fp.WriteLine('  </div>')
$fp.WriteLine('')
$fp.WriteLine('  <div class="card hide" id="editor">')
$fp.WriteLine('    <h2 id="h-edit">Inhalt</h2>')
$fp.WriteLine('    <div id="provs"></div>')
$fp.WriteLine('    <div class="row" style="margin-top:8px">')
$fp.WriteLine('      <input id="newProv" placeholder="Neuer Anbieter (Name)" style="max-width:280px">')
$fp.WriteLine('      <button class="btn sm" id="addProvBtn">+ Anbieter</button>')
$fp.WriteLine('    </div>')
$fp.WriteLine('  </div>')
$fp.WriteLine('')
$fp.WriteLine('  <div class="card hide" id="out">')
$fp.WriteLine('    <h2 id="h-save">Speichern / Export</h2>')
$fp.WriteLine('    <div class="row">')
$fp.WriteLine('      <button class="btn primary" id="encBtn">Verschlüsseln</button>')
$fp.WriteLine('      <button class="btn" id="dlBtn">Als .svpb herunterladen</button>')
$fp.WriteLine('      <button class="btn" id="expBtn">Klartext-JSON exportieren</button>')
$fp.WriteLine('      <span class="msg" id="saveMsg"></span>')
$fp.WriteLine('    </div>')
$fp.WriteLine('    <label class="lab" id="l-result">Ergebnis (zum Kopieren/Speichern)</label>')
$fp.WriteLine('    <textarea id="result" readonly></textarea>')
$fp.WriteLine('  </div>')
$fp.WriteLine('')
$fp.WriteLine('  <div class="foot" id="foot"></div>')
$fp.WriteLine('</div>')

# JavaScript section
$fp.WriteLine('<script>')
$fp.WriteLine('const L = ((navigator.language||"en").toLowerCase().startsWith("de"))?"de":"en";')
$fp.WriteLine('const T = {')
$fp.WriteLine(' title:{de:"Secret-Vault Public",en:"Secret-Vault Public"},')
$fp.WriteLine(' sub:{de:"Verschlüsselte Secret-Vault (AES-256-GCM, PBKDF2) — alles im Browser, kein Server.",en:"Encrypted secret vault (AES-256-GCM, PBKDF2) — fully in the browser, no server."},')
$fp.WriteLine(' hOpen:{de:"Öffnen oder neu",en:"Open or new"},')
$fp.WriteLine(' pass:{de:"Passphrase",en:"Passphrase"},')
$fp.WriteLine(' file:{de:"Vault laden (Datei oder Base64 einfügen)",en:"Load vault (file or paste Base64)"},')
$fp.WriteLine(' blob:{de:"…oder Base64 hier einfügen",en:"…or paste Base64 here"},')
$fp.WriteLine(' open:{de:"Öffnen / Entschlüsseln",en:"Open / Decrypt"},')
$fp.WriteLine(' neu:{de:"Neuer leerer Vault",en:"New empty vault"},')
$fp.WriteLine(' hEdit:{de:"Inhalt",en:"Content"},')
$fp.WriteLine(' newProv:{de:"Neuer Anbieter (Name)",en:"New provider (name)"},')
$fp.WriteLine(' addProv:{de:"+ Anbieter",en:"+ Provider"},')
$fp.WriteLine(' hSave:{de:"Speichern / Export",en:"Save / Export"},')
$fp.WriteLine(' enc:{de:"Verschlüsseln",en:"Encrypt"},')
$fp.WriteLine(' dl:{de:"Als .svpb herunterladen",en:"Download as .svpb"},')
$fp.WriteLine(' exp:{de:"Klartext-JSON exportieren",en:"Export plaintext JSON"},')
$fp.WriteLine(' result:{de:"Ergebnis (zum Kopieren/Speichern)",en:"Result (to copy/save)"},')
$fp.WriteLine(' foot:{de:"Eigenes Format (PBKDF2). Nicht kompatibel mit dem scrypt-Python-Tool. Sicherheit liegt in der Passphrase; Inhalt ohne sie nicht wiederherstellbar.",en:"Own format (PBKDF2). Not compatible with the scrypt Python tool. Security rests on the passphrase; content is unrecoverable without it."},')
$fp.WriteLine(' needPass:{de:"Passphrase eingeben.",en:"Enter a passphrase."},')
$fp.WriteLine(' noInput:{de:"Datei laden oder Base64 einfügen.",en:"Load a file or paste Base64."},')
$fp.WriteLine(' bad:{de:"Falsche Passphrase oder ungültiger Vault.",en:"Wrong passphrase or invalid vault."},')
$fp.WriteLine(' opened:{de:"Geöffnet.",en:"Opened."},')
$fp.WriteLine(' created:{de:"Neuer Vault angelegt.",en:"New vault created."},')
$fp.WriteLine(' encrypted:{de:"Verschlüsselt — unten kopieren oder herunterladen.",en:"Encrypted — copy below or download."},')
$fp.WriteLine(' needOpen:{de:"Erst öffnen/anlegen.",en:"Open/create first."},')
$fp.WriteLine(' field:{de:"Feld",en:"field"}, value:{de:"Wert",en:"value"},')
$fp.WriteLine(' addField:{de:"+ Feld",en:"+ field"}, del:{de:"✕",en:"✕"},')
$fp.WriteLine(' newField:{de:"neues Feld",en:"new field"}, newValue:{de:"Wert",en:"value"}')
$fp.WriteLine('};')
$fp.WriteLine('const tr=k=>T[k][L];')
$fp.WriteLine('// apply static i18n')
$fp.WriteLine('title.textContent=tr("title"); sub.textContent=tr("sub"); document.title=tr("title");')
$fp.WriteLine('document.getElementById("h-open").textContent=tr("hOpen");')
$fp.WriteLine('document.getElementById("l-pass").textContent=tr("pass");')
$fp.WriteLine('document.getElementById("l-file").textContent=tr("file");')
$fp.WriteLine('blob.placeholder=tr("blob");')
$fp.WriteLine('openBtn.textContent=tr("open"); newBtn.textContent=tr("neu");')
$fp.WriteLine('document.getElementById("h-edit").textContent=tr("hEdit");')
$fp.WriteLine('newProv.placeholder=tr("newProv"); addProvBtn.textContent=tr("addProv");')
$fp.WriteLine('document.getElementById("h-save").textContent=tr("hSave");')
$fp.WriteLine('encBtn.textContent=tr("enc"); dlBtn.textContent=tr("dl"); expBtn.textContent=tr("exp");')
$fp.WriteLine('document.getElementById("l-result").textContent=tr("result");')
$fp.WriteLine('foot.textContent=tr("foot");')
$fp.WriteLine('')
$fp.WriteLine('let VAULT=null; // {meta, providers:{}}')
$fp.WriteLine('')
$fp.WriteLine('const enc=new TextEncoder(), dec=new TextDecoder();')
$fp.WriteLine('function u8b64(u8){ let s=""; for(let i=0;i<u8.length;i+=0x8000) s+=String.fromCharCode.apply(null,u8.subarray(i,i+0x8000)); return btoa(s); }')
$fp.WriteLine('function b64u8(b64){ const s=atob(b64.trim()); const u=new Uint8Array(s.length); for(let i=0;i<s.length;i++) u[i]=s.charCodeAt(i); return u; }')
$fp.WriteLine('async function deriveKey(pw,salt){')
$fp.WriteLine('  const km=await crypto.subtle.importKey("raw",enc.encode(pw),"PBKDF2",false,["deriveKey"]);')
$fp.WriteLine('  return crypto.subtle.deriveKey({name:"PBKDF2",salt,iterations:210000,hash:"SHA-256"},km,{name:"AES-GCM",length:256},false,["encrypt","decrypt"]);')
$fp.WriteLine('}')
$fp.WriteLine('async function encryptObj(obj,pw){')
$fp.WriteLine('  const salt=crypto.getRandomValues(new Uint8Array(16)), iv=crypto.getRandomValues(new Uint8Array(12));')
$fp.WriteLine('  const key=await deriveKey(pw,salt);')
$fp.WriteLine('  const ct=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv},key,enc.encode(JSON.stringify(obj,null,2))));')
$fp.WriteLine('  const magic=enc.encode("SVPB1"); const out=new Uint8Array(5+16+12+ct.length);')
$fp.WriteLine('  out.set(magic,0); out.set(salt,5); out.set(iv,21); out.set(ct,33); return u8b64(out);')
$fp.WriteLine('}')
$fp.WriteLine('async function decryptB64(b64,pw){')
$fp.WriteLine('  const raw=b64u8(b64); if(dec.decode(raw.slice(0,5))!=="SVPB1") throw new Error("magic");')
$fp.WriteLine('  const key=await deriveKey(pw,raw.slice(5,21));')
$fp.WriteLine('  const pt=await crypto.subtle.decrypt({name:"AES-GCM",iv:raw.slice(21,33)},key,raw.slice(33));')
$fp.WriteLine('  return JSON.parse(dec.decode(pt));')
$fp.WriteLine('}')
$fp.WriteLine('function esc(s){return (s==null?"":String(s)).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",""":""quot;"}[c]));}')
$fp.WriteLine('')
$fp.WriteLine('function renderEditor(){')
$fp.WriteLine('  document.getElementById("editor").classList.remove("hide");')
$fp.WriteLine('  document.getElementById("out").classList.remove("hide");')
$fp.WriteLine('  const P=VAULT.providers||{}; const root=document.getElementById("provs"); root.innerHTML="";')
$fp.WriteLine('  Object.keys(P).forEach(name=>{')
$fp.WriteLine('    const d=document.createElement("div"); d.className="prov";')
$fp.WriteLine('    let rows="";')
$fp.WriteLine('    Object.keys(P[name]).forEach(k=>{ rows+=`<div class="kv"><span class="k">${esc(k)}</span><input data-p="${esc(name)}" data-k="${esc(k)}" value="${esc(P[name][k])}"><button class="btn sm" data-del="${esc(name)}|${esc(k)}">${tr("del")}</button></div>`; });')
$fp.WriteLine('    d.innerHTML=`<h3>${esc(name)} <button class="btn sm" data-delp="${esc(name)}">${tr("del")}</button></h3>${rows}')
$fp.WriteLine('      <div class="row" style="margin-top:6px"><input class="nf" data-np="${esc(name)}" placeholder="${tr("newField")}" style="max-width:180px"><input class="nv" data-np="${esc(name)}" placeholder="${tr("newValue")}" style="max-width:260px"><button class="btn sm" data-addf="${esc(name)}">${tr("addField")}</button></div>`;')
$fp.WriteLine('    root.appendChild(d);')
$fp.WriteLine('  });')
$fp.WriteLine('  root.querySelectorAll("input[data-k]").forEach(i=>i.onchange=()=>{ VAULT.providers[i.dataset.p][i.dataset.k]=i.value; });')
$fp.WriteLine('  root.querySelectorAll("button[data-del]").forEach(b=>b.onclick=()=>{ const [p,k]=b.dataset.del.split("|"); delete VAULT.providers[p][k]; renderEditor(); });')
$fp.WriteLine('  root.querySelectorAll("button[data-delp]").forEach(b=>b.onclick=()=>{ delete VAULT.providers[b.dataset.delp]; renderEditor(); });')
$fp.WriteLine('  root.querySelectorAll("button[data-addf]").forEach(b=>b.onclick=()=>{ const p=b.dataset.addf; const nf=root.querySelector(`.nf[data-np="${CSS.escape(p)}"]`).value.trim(); const nv=root.querySelector(`.nv[data-np="${CSS.escape(p)}"]`).value; if(nf){ VAULT.providers[p][nf]=nv; renderEditor(); } });')
$fp.WriteLine('}')
$fp.WriteLine('')
$fp.WriteLine('document.getElementById("file").onchange=e=>{ const f=e.target.files[0]; if(!f)return; const r=new FileReader(); r.onload=()=>{ blob.value=r.result.trim(); }; r.readAsText(f); };')
$fp.WriteLine('openBtn.onclick=async()=>{')
$fp.WriteLine('  const m=document.getElementById("openMsg"); m.className="msg"; m.textContent="";')
$fp.WriteLine('  if(!pass.value){ m.className="msg err"; m.textContent=tr("needPass"); return; }')
$fp.WriteLine('  if(!blob.value.trim()){ m.className="msg err"; m.textContent=tr("noInput"); return; }')
$fp.WriteLine('  try{ VAULT=await decryptB64(blob.value,pass.value); if(!VAULT.providers)VAULT.providers={}; renderEditor(); m.className="msg ok"; m.textContent=tr("opened"); }')
$fp.WriteLine('  catch(err){ m.className="msg err"; m.textContent=tr("bad"); }')
$fp.WriteLine('};')
$fp.WriteLine('newBtn.onclick=()=>{')
$fp.WriteLine('  const m=document.getElementById("openMsg");')
$fp.WriteLine('  if(!pass.value){ m.className="msg err"; m.textContent=tr("needPass"); return; }')
$fp.WriteLine('  VAULT={meta:{created:new Date().toISOString().slice(0,10),format:"SVPB1"},providers:{}}; renderEditor();')
$fp.WriteLine('  m.className="msg ok"; m.textContent=tr("created");')
$fp.WriteLine('};')
$fp.WriteLine('addProvBtn.onclick=()=>{ if(!VAULT){ return; } const n=newProv.value.trim(); if(n){ VAULT.providers[n]=VAULT.providers[n]||{}; newProv.value=""; renderEditor(); } };')
$fp.WriteLine('encBtn.onclick=async()=>{')
$fp.WriteLine('  const m=document.getElementById("saveMsg"); m.className="msg";')
$fp.WriteLine('  if(!VAULT){ m.className="msg err"; m.textContent=tr("needOpen"); return; }')
$fp.WriteLine('  if(!pass.value){ m.className="msg err"; m.textContent=tr("needPass"); return; }')
$fp.WriteLine('  result.value=await encryptObj(VAULT,pass.value); m.className="msg ok"; m.textContent=tr("encrypted");')
$fp.WriteLine('};')
$fp.WriteLine('dlBtn.onclick=()=>{ if(!result.value)return; try{ const b=new Blob([result.value],{type:"text/plain"}); const u=URL.createObjectURL(b); const a=document.createElement("a"); a.href=u; a.download="vault.svpb"; document.body.appendChild(a); a.click(); a.remove(); setTimeout(()=>URL.revokeObjectURL(u),1500);}catch(e){} };')
$fp.WriteLine('expBtn.onclick=()=>{ if(!VAULT)return; result.value=JSON.stringify(VAULT,null,2); };')
$fp.WriteLine('}')
$fp.WriteLine('</script>')

$fp.WriteLine('</body>')
$fp.WriteLine('</html>')

$fp.Close()

Write-Host "HTML file generated: $OutputFile"
