#!/usr/bin/env pwsh
# 1781743218784_260531.js — portiert nach powershell
# Quelle: javascript, Projects@abstractions:javascript/1781743218784_260531.js
# Erzeugt: 2026-08-18 durch ABSTRACTIONS_MANAGER.py

# 1781743218784.tcl — portiert nach javascript
# Quelle: tcl, Projects@abstractions:tcl/1781743218784.tcl
# Erzeugt: 2026-08-08 durch ABSTRACTIONS_MANAGER.py

# 1781743218784.html — portiert nach tcl
# Quelle: html, Projects@secret-vault-public:secret-vault-public/versions/1781743218784.html
# Erzeugt: 2026-08-08 durch ABSTRACTIONS_MANAGER.py

# Tcl 8.6 script to generate the Secret Vault Public HTML file
# Usage: tclsh this_script.tcl output_file.html

param(
    [Parameter(Mandatory=$true)]
    [string]$OutputFile
)

try {
    $fd = [System.IO.File]::CreateText($OutputFile)
    
    # Write DOCTYPE and main script tag
    $fd.WriteLine("<!DOCTYPE html>")
    $fd.WriteLine("<script type=""application/json"" id=""cowork-artifact-meta"">")
    $fd.WriteLine("")
    $fd.WriteLine("{")
    $fd.WriteLine("  ""name"": ""Secret Vault Public"",")
    $fd.WriteLine("  ""schemaVersion"": 1,")
    $fd.WriteLine("  ""description"": ""Secret-Vault Public als interaktives Browser-Artefakt: verschlüsselter Secret-Container vollständig client-seitig (WebCrypto, AES-256-GCM + PBKDF2). Öffnen/Anlegen, Anbieter/Felder ergänzen und ersetzen (Rotation), verschlüsseln und als .svpb herunterladen oder Klartext-JSON exportieren. DE/EN nach Browsersprache. Eigenes Format (nicht kompatibel mit dem scrypt-Python-Tool). Keine Secrets eingebettet."",")
    $fd.WriteLine("  ""mcpTools"": [],")
    $fd.WriteLine("  ""mcpServerNames"": []")
    $fd.WriteLine("}")
    $fd.WriteLine("")
    $fd.WriteLine("</script>")
    
    # Write HTML start and head section
    $fd.WriteLine("<html lang=""de"">")
    $fd.WriteLine("<head>")
    $fd.WriteLine("<meta charset=""utf-8"">")
    $fd.WriteLine("<meta name=""viewport"" content=""width=device-width, initial-scale=1"">")
    $fd.WriteLine("<title>Secret-Vault Public</title>")
    $fd.WriteLine("<style>")
    $fd.WriteLine(":root{ color-scheme:light; --ink:#1b1c1f; --muted:#6c6e75; --faint:#9a9ca3; --card:#fff; --line:#e9eaee; --accent:#5b5bd6; --accent2:#7c5cff; --ok:#22a06b; --err:#e0533d; --radius:16px; --shadow:0 1px 2px rgba(20,20,40,.04),0 6px 20px rgba(20,20,40,.06);}")
    $fd.WriteLine("*{box-sizing:border-box;}")
    $fd.WriteLine("body{margin:0;font-family:-apple-system,BlinkMacSystemFont,""Segoe UI"",Roboto,Helvetica,Arial,sans-serif;color:var(--ink);min-height:100vh;background:radial-gradient(1100px 560px at 100% -10%,#e8ecff 0%,rgba(232,236,255,0) 55%),linear-gradient(180deg,#eef1f6,#f7f7f8 42%);background-attachment:fixed;}")
    $fd.WriteLine(".wrap{max-width:820px;margin:0 auto;padding:24px 18px 70px;}")
    $fd.WriteLine(".brand{display:flex;align-items:center;gap:12px;margin-bottom:4px;}")
    $fd.WriteLine(".mark{width:32px;height:32px;border-radius:9px;background:linear-gradient(135deg,var(--accent),var(--accent2));box-shadow:0 4px 12px rgba(91,91,214,.35);position:relative;flex:0 0 auto;}")
    $fd.WriteLine(".mark:after{content:"""";position:absolute;inset:8px;border-radius:4px;border:2px solid rgba(255,255,255,.92);}")
    $fd.WriteLine("h1{font-size:21px;margin:0;font-weight:700;}")
    $fd.WriteLine(".sub{color:var(--muted);font-size:13px;margin:2px 0 16px;}")
    $fd.WriteLine(".card{background:var(--card);border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow);padding:16px;margin-bottom:14px;}")
    $fd.WriteLine(".card h2{font-size:14px;margin:0 0 10px;}")
    $fd.WriteLine("label.lab{display:block;font-size:12px;font-weight:600;color:var(--muted);margin:8px 0 3px;}")
    $fd.WriteLine("input,textarea{width:100%;font-size:13px;padding:8px 10px;border:1px solid var(--line);border-radius:9px;font-family:ui-monospace,Menlo,Consolas,monospace;background:#fff;}")
    $fd.WriteLine("textarea{min-height:90px;white-space:pre;overflow:auto;}")
    $fd.WriteLine(".row{display:flex;gap:8px;flex-wrap:wrap;align-items:center;}")
    $fd.WriteLine(".btn{font-size:13px;font-weight:600;padding:8px 14px;border:1px solid var(--line);border-radius:10px;background:#fff;cursor:pointer;box-shadow:var(--shadow);transition:transform .1s;}")
    $fd.WriteLine(".btn:hover{transform:translateY(-1px);}")
    $fd.WriteLine(".btn.primary{background:linear-gradient(135deg,var(--accent),var(--accent2));color:#fff;border-color:transparent;}")
    $fd.WriteLine(".btn.sm{padding:5px 9px;font-size:12px;}")
    $fd.WriteLine(".msg{font-size:12px;margin-left:6px;}")
    $fd.WriteLine(".msg.ok{color:var(--ok);} .msg.err{color:var(--err);}")
    $fd.WriteLine(".prov{border:1px solid var(--line);border-radius:12px;padding:10px 12px;margin-bottom:10px;}")
    $fd.WriteLine(".prov h3{margin:0 0 6px;font-size:13.5px;display:flex;align-items:center;gap:8px;}")
    $fd.WriteLine(".kv{display:grid;grid-template-columns:180px 1fr auto;gap:6px;margin:4px 0;align-items:center;}")
    $fd.WriteLine(".kv input{font-size:12px;padding:5px 7px;}")
    $fd.WriteLine(".kv .k{color:var(--muted);font-weight:600;}")
    $fd.WriteLine(".muted{color:var(--faint);font-size:13px;}")
    $fd.WriteLine(".hide{display:none;}")
    $fd.WriteLine(".foot{color:var(--faint);font-size:11.5px;text-align:center;margin-top:18px;line-height:1.5;}")
    $fd.WriteLine("a{color:var(--accent);}")
    $fd.WriteLine("</style>")
    $fd.WriteLine("</head>")
    
    # Write body content
    $fd.WriteLine("<body>")
    $fd.WriteLine("<div class=""wrap"">")
    $fd.WriteLine("  <div class=""brand""><div class=""mark""></div><h1 id=""title"">Secret-Vault Public</h1></div>")
    $fd.WriteLine("  <div class=""sub"" id=""sub"">Verschlüsselte Secret-Vault (AES-256-GCM, PBKDF2) — alles im Browser, kein Server.</div>")
    
    # Card: Open or new
    $fd.WriteLine("")
    $fd.WriteLine("  <div class=""card"">")
    $fd.WriteLine("    <h2 id=""h-open"">Öffnen oder neu</h2>")
    $fd.WriteLine("    <label class=""lab"" id=""l-pass"">Passphrase</label>")
    $fd.WriteLine("    <input id=""pass"" type=""password"" placeholder=""Passphrase…"">")
    $fd.WriteLine("    <label class=""lab"" id=""l-file"">Vault laden (Datei oder Base64 einfügen)</label>")
    $fd.WriteLine("    <input id=""file"" type=""file"" accept="".svpb,.txt,.vault,.b64"">")
    $fd.WriteLine("    <textarea id=""blob"" placeholder=""…oder Base64 hier einfügen""></textarea>")
    $fd.WriteLine("    <div class=""row"" style=""margin-top:10px"">")
    $fd.WriteLine("      <button class=""btn primary"" id=""openBtn"">Öffnen / Entschlüsseln</button>")
    $fd.WriteLine("      <button class=""btn"" id=""newBtn"">Neuer leerer Vault</button>")
    $fd.WriteLine("      <span class=""msg"" id=""openMsg""></span>")
    $fd.WriteLine("    </div>")
    $fd.WriteLine("  </div>")
    $fd.WriteLine("")
    
    # Card: Editor (hidden by default)
    $fd.WriteLine("  <div class=""card hide"" id=""editor"">")
    $fd.WriteLine("    <h2 id=""h-edit"">Inhalt</h2>")
    $fd.WriteLine("    <div id=""provs""></div>")
    $fd.WriteLine("    <div class=""row"" style=""margin-top:8px"">")
    $fd.WriteLine("      <input id=""newProv"" placeholder=""Neuer Anbieter (Name)"" style=""max-width:280px"">")
    $fd.WriteLine("      <button class=""btn sm"" id=""addProvBtn"">+ Anbieter</button>")
    $fd.WriteLine("    </div>")
    $fd.WriteLine("  </div>")
    $fd.WriteLine("")
    
    # Card: Save/Export (hidden by default)
    $fd.WriteLine("  <div class=""card hide"" id=""out"">")
    $fd.WriteLine("    <h2 id=""h-save"">Speichern / Export</h2>")
    $fd.WriteLine("    <div class=""row"">")
    $fd.WriteLine("      <button class=""btn primary"" id=""encBtn"">Verschlüsseln</button>")
    $fd.WriteLine("      <button class=""btn"" id=""dlBtn"">Als .svpb herunterladen</button>")
    $fd.WriteLine("      <button class=""btn"" id=""expBtn"">Klartext-JSON exportieren</button>")
    $fd.WriteLine("      <span class=""msg"" id=""saveMsg""></span>")
    $fd.WriteLine("    </div>")
    $fd.WriteLine("    <label class=""lab"" id=""l-result"">Ergebnis (zum Kopieren/Speichern)</label>")
    $fd.WriteLine("    <textarea id=""result"" readonly></textarea>")
    $fd.WriteLine("  </div>")
    $fd.WriteLine("")
    
    # Footer
    $fd.WriteLine("  <div class=""foot"" id=""foot""></div>")
    $fd.WriteLine("</div>")
    
    # JavaScript section
    $fd.WriteLine("<script>")
    $fd.WriteLine("")
    $fd.WriteLine("const L = ((navigator.language||""en"").toLowerCase().startsWith(""de""))?""de"":""en"";")
    $fd.WriteLine("const T = {")
    $fd.WriteLine(" title:{de:""Secret-Vault Public"",en:""Secret-Vault Public""},")
    $fd.WriteLine(" sub:{de:""Verschlüsselte Secret-Vault (AES-256-GCM, PBKDF2) — alles im Browser, kein Server."",en:""Encrypted secret vault (AES-256-GCM, PBKDF2) — fully in the browser, no server.""},")
    $fd.WriteLine(" hOpen:{de:""Öffnen oder neu"",en:""Open or new""},")
    $fd.WriteLine(" pass:{de:""Passphrase"",en:""Passphrase""},")
    $fd.WriteLine(" file:{de:""Vault laden (Datei oder Base64 einfügen)"",en:""Load vault (file or paste Base64)""},")
    $fd.WriteLine(" blob:{de:""…oder Base64 hier einfügen"",en:""…or paste Base64 here""},")
    $fd.WriteLine(" open:{de:""Öffnen / Entschlüsseln"",en:""Open / Decrypt""},")
    $fd.WriteLine(" neu:{de:""Neuer leerer Vault"",en:""New empty vault""},")
    $fd.WriteLine(" hEdit:{de:""Inhalt"",en:""Content""},")
    $fd.WriteLine(" newProv:{de:""Neuer Anbieter (Name)"",en:""New provider (name)""},")
    $fd.WriteLine(" addProv:{de:""+ Anbieter"",en:""+ Provider""},")
    $fd.WriteLine(" hSave:{de:""Speichern / Export"",en:""Save / Export""},")
    $fd.WriteLine(" enc:{de:""Verschlüsseln"",en:""Encrypt""},")
    $fd.WriteLine(" dl:{de:""Als .svpb herunterladen"",en:""Download as .svpb""},")
    $fd.WriteLine(" exp:{de:""Klartext-JSON exportieren"",en:""Export plaintext JSON""},")
    $fd.WriteLine(" result:{de:""Ergebnis (zum Kopieren/Speichern)"",en:""Result (to copy/save)""},")
    $fd.WriteLine(" foot:{de:""Eigenes Format (PBKDF2). Nicht kompatibel mit dem scrypt-Python-Tool. Sicherheit liegt in der Passphrase; Inhalt ohne sie nicht wiederherstellbar."",en:""Own format (PBKDF2). Not compatible with the scrypt Python tool. Security rests on the passphrase; content is unrecoverable without it.""},")
    $fd.WriteLine(" needPass:{de:""Passphrase eingeben."",en:""Enter a passphrase.""},")
    $fd.WriteLine(" noInput:{de:""Datei laden oder Base64 einfügen."",en:""Load a file or paste Base64.""},")
    $fd.WriteLine(" bad:{de:""Falsche Passphrase oder ungültiger Vault."",en:""Wrong passphrase or invalid vault.""},")
    $fd.WriteLine(" opened:{de:""Geöffnet."",en:""Opened.""},")
    $fd.WriteLine(" created:{de:""Neuer Vault angelegt."",en:""New vault created.""},")
    $fd.WriteLine(" encrypted:{de:""Verschlüsselt — unten kopieren oder herunterladen."",en:""Encrypted — copy below or download.""},")
    $fd.WriteLine(" needOpen:{de:""Erst öffnen/anlegen."",en:""Open/create first.""},")
    $fd.WriteLine(" field:{de:""Feld"",en:""field""}, value:{de:""Wert"",en:""value""},")
    $fd.WriteLine(" addField:{de:""+ Feld"",en:""+ field""}, del:{de:""✕"",en:""✕""},")
    $fd.WriteLine(" newField:{de:""neues Feld"",en:""new field""}, newValue:{de:""Wert"",en:""value""}")
    $fd.WriteLine("};")
    $fd.WriteLine("const tr=k=>T[k][L];")
    $fd.WriteLine("// apply static i18n")
    $fd.WriteLine("title.textContent=tr(""title""); sub.textContent=tr(""sub""); document.title=tr(""title"");")
    $fd.WriteLine("document.getElementById(""h-open"").textContent=tr(""hOpen"");")
    $fd.WriteLine("document.getElementById(""l-pass"").textContent=tr(""pass"");")
    $fd.WriteLine("document.getElementById(""l-file"").textContent=tr(""file"");")
    $fd.WriteLine("blob.placeholder=tr(""blob"");")
    $fd.WriteLine("openBtn.textContent=tr(""open""); newBtn.textContent=tr(""neu"");")
    $fd.WriteLine("document.getElementById(""h-edit"").textContent=tr(""hEdit"");")
    $fd.WriteLine("newProv.placeholder=tr(""newProv""); addProvBtn.textContent=tr(""addProv"");")
    $fd.WriteLine("document.getElementById(""h-save"").textContent=tr(""hSave"");")
    $fd.WriteLine("encBtn.textContent=tr(""enc""); dlBtn.textContent=tr(""dl""); expBtn.textContent=tr(""exp"");")
    $fd.WriteLine("document.getElementById(""l-result"").textContent=tr(""result"");")
    $fd.WriteLine("foot.textContent=tr(""foot"");")
    $fd.WriteLine("")
    $fd.WriteLine("let VAULT=null; // {meta, providers:{}}")
    $fd.WriteLine("")
    $fd.WriteLine("const enc=new TextEncoder(), dec=new TextDecoder();")
    $fd.WriteLine("function u8b64(u8){ let s=""""; for(let i=0;i<u8.length;i+=0x8000) s+=String.fromCharCode.apply(null,u8.subarray(i,i+0x8000)); return btoa(s); }")
    $fd.WriteLine("function b64u8(b64){ const s=atob(b64.trim()); const u=new Uint8Array(s.length); for(let i=0;i<s.length;i++) u[i]=s.charCodeAt(i); return u; }")
    $fd.WriteLine("async function deriveKey(pw,salt){")
    $fd.WriteLine("  const km=await crypto.subtle.importKey(""raw"",enc.encode(pw),""PBKDF2"",false,[""deriveKey""]);")
    $fd.WriteLine("  return crypto.subtle.deriveKey({name:""PBKDF2"",salt,iterations:210000,hash:""SHA-256""},km,{name:""AES-GCM"",length:256},false,[""encrypt"",""decrypt""]);")
    $fd.WriteLine("}")
    $fd.WriteLine("async function encryptObj(obj,pw){")
    $fd.WriteLine("  const salt=crypto.getRandomValues(new Uint8Array(16)), iv=crypto.getRandomValues(new Uint8Array(12));")
    $fd.WriteLine("  const key=await deriveKey(pw,salt);")
    $fd.WriteLine("  const ct=new Uint8Array(await crypto.subtle.encrypt({name:""AES-GCM"",iv},key,enc.encode(JSON.stringify(obj,null,2))));")
    $fd.WriteLine("  const magic=enc.encode(""SVPB1""); const out=new Uint8Array(5+16+12+ct.length);")
    $fd.WriteLine("  out.set(magic,0); out.set(salt,5); out.set(iv,21); out.set(ct,33); return u8b64(out);")
    $fd.WriteLine("}")
    $fd.WriteLine("async function decryptB64(b64,pw){")
    $fd.WriteLine("  const raw=b64u8(b64); if(dec.decode(raw.slice(0,5))!==""SVPB1"") throw new Error(""magic"");")
    $fd.WriteLine("  const key=await deriveKey(pw,raw.slice(5,21));")
    $fd.WriteLine("  const pt=await crypto.subtle.decrypt({name:""AES-GCM"",iv:raw.slice(21,33)},key,raw.slice(33));")
    $fd.WriteLine("  return JSON.parse(dec.decode(pt));")
    $fd.WriteLine("}")
    $fd.WriteLine("function esc(s){return (s==null?"""":String(s)).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','""':'&quot;'}[c]));}")
    $fd.WriteLine("")
    $fd.WriteLine("function renderEditor(){")
    $fd.WriteLine("  document.getElementById(""editor"").classList.remove(""hide"");")
    $fd.WriteLine("  document.getElementById(""out"").classList.remove(""hide"");")
    $fd.WriteLine("  const P=VAULT.providers||{}; const root=document.getElementById(""provs""); root.innerHTML="""";")
    $fd.WriteLine("  Object.keys(P).forEach(name=>{")
    $fd.WriteLine("    const d=document.createElement(""div""); d.className=""prov"";")
    $fd.WriteLine("    let rows="""";")
    $fd.WriteLine("    Object.keys(P[name]).forEach(k=>{ rows+=`<div class=""kv""><span class=""k"">${esc(k)}</span><input data-p=""${esc(name)}"" data-k=""${esc(k)}"" value=""${esc(P[name][k])}""><button class=""btn sm"" data-del=""${esc(name)}|${esc(k)}"">${tr(""del"")}</button></div>`; });")
    $fd.WriteLine("    d.innerHTML=`<h3>${esc(name)} <button class=""btn sm"" data-delp=""${esc(name)}"">${tr(""del"")}</button></h3>${rows}")
    $fd.WriteLine("      <div class=""row"" style=""margin-top:6px""><input class=""nf"" data-np=""${esc(name)}"" placeholder=""${tr(""newField"")}"" style=""max-width:180px""><input class=""nv"" data-np=""${esc(name)}"" placeholder=""${tr(""newValue"")}"" style=""max-width:260px""><button class=""btn sm"" data-addf=""${esc(name)}"">${tr(""addField"")}</button></div>`;")
    $fd.WriteLine("    root.appendChild(d);")
    $fd.WriteLine("  });")
    $fd.WriteLine("  root.querySelectorAll(""input[data-k]"").forEach(i=>i.onchange=()=>{ VAULT.providers[i.dataset.p][i.dataset.k]=i.value; });")
    $fd.WriteLine("  root.querySelectorAll(""button[data-del]"").forEach(b=>b.onclick=()=>{ const [p,k]=b.dataset.del.split(""|""); delete VAULT.providers[p][k]; renderEditor(); });")
    $fd.WriteLine("  root.querySelectorAll(""button[data-delp]"").forEach(b=>b.onclick=()=>{ delete VAULT.providers[b.dataset.delp]; renderEditor(); });")
    $fd.WriteLine("  root.querySelectorAll(""button[data-addf]"").forEach(b=>b.onclick=()=>{ const p=b.dataset.addf; const nf=root.querySelector(`.nf[data-np=""${CSS.escape(p)}""]`).value.trim(); const nv=root.querySelector(`.nv[data-np=""${CSS.escape(p)}""]`).value; if(nf){ VAULT.providers[p][nf]=nv; renderEditor(); } });")
    $fd.WriteLine("}")
    $fd.WriteLine("")
    $fd.WriteLine("document.getElementById(""file"").onchange=e=>{ const f=e.target.files[0]; if(!f)return; const r=new FileReader(); r.onload=()=>{ blob.value=r.result.trim(); }; r.readAsText(f); };")
    $fd.WriteLine("openBtn.onclick=async()=>{")
    $fd.WriteLine("  const m=document.getElementById(""openMsg""); m.className=""msg""; m.textContent="""";")
    $fd.WriteLine("  if(!pass.value){ m.className=""msg err""; m.textContent=tr(""needPass""); return; }")
    $fd.WriteLine("  if(!blob.value.trim()){ m.className=""msg err""; m.textContent=tr(""noInput""); return; }")
    $fd.WriteLine("  try{ VAULT=await decryptB64(blob.value,pass.value); if(!VAULT.providers)VAULT.providers={}; renderEditor(); m.className=""msg ok""; m.textContent=tr(""opened""); }")
    $fd.WriteLine("  catch(err){ m.className=""msg err""; m.textContent=tr(""bad""); }")
    $fd.WriteLine("};")
    $fd.WriteLine("newBtn.onclick=()=>{")
    $fd.WriteLine("  const m=document.getElementById(""openMsg"");")
    $fd.WriteLine("  if(!pass.value){ m.className=""msg err""; m.textContent=tr(""needPass""); return; }")
    $fd.WriteLine("  VAULT={meta:{created:new Date().toISOString().slice(0,10),format:""SVPB1""},providers:{}}; renderEditor();")
    $fd.WriteLine("  m.className=""msg ok""; m.textContent=tr(""created"");")
    $fd.WriteLine("};")
    $fd.WriteLine("addProvBtn.onclick=()=>{ if(!VAULT){ return; } const n=newProv.value.trim(); if(n){ VAULT.providers[n]=VAULT.providers[n]||{}; newProv.value=""""; renderEditor(); } };")
    $fd.WriteLine("encBtn.onclick=async()=>{")
    $fd.WriteLine("  const m=document.getElementById(""saveMsg""); m.className=""msg"";")
    $fd.WriteLine("  if(!VAULT){ m.className=""msg err""; m.textContent=tr(""needOpen""); return; }")
    $fd.WriteLine("  if(!pass.value){ m.className=""msg err""; m.textContent=tr(""needPass""); return; }")
    $fd.WriteLine("  result.value=await encryptObj(VAULT,pass.value); m.className=""msg ok""; m.textContent=tr(""encrypted"");")
    $fd.WriteLine("};")
    $fd.WriteLine("dlBtn.onclick=()=>{ if(!result.value)return; try{ const b=new Blob([result.value],{type:""text/plain""}); const u=URL.createObjectURL(b); const a=document.createElement(""a""); a.href=u; a.download=""vault.svpb""; document.body.appendChild(a); a.click(); a.remove(); setTimeout(()=>URL.revokeObjectURL(u),1500);}catch(e){} };")
    $fd.WriteLine("expBtn.onclick=()=>{ if(!VAULT)return; result.value=JSON.stringify(VAULT,null,2); };")
    $fd.WriteLine("")
    $fd.WriteLine("</script>")
    $fd.WriteLine("</body>")
    $fd.WriteLine("</html>")
    
    $fd.Close()
    
    Write-Host "HTML file generated: $OutputFile"
}
catch {
    Write-Error "Error generating HTML file: $_"
    exit 1
}
