#!/usr/bin/env python3
# 1781743218784_260531.js — portiert nach python
# Quelle: javascript, Projects@abstractions:javascript/1781743218784_260531.js
# Erzeugt: 2026-08-18 durch ABSTRACTIONS_MANAGER.py

# 1781743218784.tcl — portiert nach javascript
# Quelle: tcl, Projects@abstractions:tcl/1781743218784.tcl
# Erzeugt: 2026-08-08 durch ABSTRACTIONS_MANAGER.py

# 1781743218784.html — portiert nach tcl
# Quelle: html, Projects@secret-vault-public:secret-vault-public/versions/1781743218784.html
# Erzeugt: 2026-08-08 durch ABSTRACTIONS_MANAGER.py

# Tcl 8.6 script to generate the Secret Vault Public HTML file
# Usage: tclsh this_script.tcl output_file.html

import sys

if len(sys.argv) != 2:
    print("Usage: python3 " + sys.argv[0] + " output_file.html")
    sys.exit(1)

outputFile = sys.argv[1]

with open(outputFile, 'w') as fd:
    # Write DOCTYPE and main script tag
    fd.write("<!DOCTYPE html>\n")
    fd.write("<script type=\"application/json\" id=\"cowork-artifact-meta\">\n")
    fd.write("\n")
    fd.write("{\n")
    fd.write("  \"name\": \"Secret Vault Public\",\n")
    fd.write("  \"schemaVersion\": 1,\n")
    fd.write("  \"description\": \"Secret-Vault Public als interaktives Browser-Artefakt: verschlüsselter Secret-Container vollständig client-seitig (WebCrypto, AES-256-GCM + PBKDF2). Öffnen/Anlegen, Anbieter/Felder ergänzen und ersetzen (Rotation), verschlüsseln und als .svpb herunterladen oder Klartext-JSON exportieren. DE/EN nach Browsersprache. Eigenes Format (nicht kompatibel mit dem scrypt-Python-Tool). Keine Secrets eingebettet.\",\n")
    fd.write("  \"mcpTools\": [],\n")
    fd.write("  \"mcpServerNames\": []\n")
    fd.write("}\n")
    fd.write("\n")
    fd.write("</script>\n")

    # Write HTML start and head section
    fd.write("<html lang=\"de\">\n")
    fd.write("<head>\n")
    fd.write("<meta charset=\"utf-8\">\n")
    fd.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
    fd.write("<title>Secret-Vault Public</title>\n")
    fd.write("<style>\n")
    fd.write(":root{ color-scheme:light; --ink:#1b1c1f; --muted:#6c6e75; --faint:#9a9ca3; --card:#fff; --line:#e9eaee; --accent:#5b5bd6; --accent2:#7c5cff; --ok:#22a06b; --err:#e0533d; --radius:16px; --shadow:0 1px 2px rgba(20,20,40,.04),0 6px 20px rgba(20,20,40,.06);}\n")
    fd.write("*{box-sizing:border-box;}\n")
    fd.write("body{margin:0;font-family:-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,Helvetica,Arial,sans-serif;color:var(--ink);min-height:100vh;background:radial-gradient(1100px 560px at 100% -10%,#e8ecff 0%,rgba(232,236,255,0) 55%),linear-gradient(180deg,#eef1f6,#f7f7f8 42%);background-attachment:fixed;}\n")
    fd.write(".wrap{max-width:820px;margin:0 auto;padding:24px 18px 70px;}\n")
    fd.write(".brand{display:flex;align-items:center;gap:12px;margin-bottom:4px;}\n")
    fd.write(".mark{width:32px;height:32px;border-radius:9px;background:linear-gradient(135deg,var(--accent),var(--accent2));box-shadow:0 4px 12px rgba(91,91,214,.35);position:relative;flex:0 0 auto;}\n")
    fd.write(".mark:after{content:\"\";position:absolute;inset:8px;border-radius:4px;border:2px solid rgba(255,255,255,.92);}\n")
    fd.write("h1{font-size:21px;margin:0;font-weight:700;}\n")
    fd.write(".sub{color:var(--muted);font-size:13px;margin:2px 0 16px;}\n")
    fd.write(".card{background:var(--card);border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow);padding:16px;margin-bottom:14px;}\n")
    fd.write(".card h2{font-size:14px;margin:0 0 10px;}\n")
    fd.write("label.lab{display:block;font-size:12px;font-weight:600;color:var(--muted);margin:8px 0 3px;}\n")
    fd.write("input,textarea{width:100%;font-size:13px;padding:8px 10px;border:1px solid var(--line);border-radius:9px;font-family:ui-monospace,Menlo,Consolas,monospace;background:#fff;}\n")
    fd.write("textarea{min-height:90px;white-space:pre;overflow:auto;}\n")
    fd.write(".row{display:flex;gap:8px;flex-wrap:wrap;align-items:center;}\n")
    fd.write(".btn{font-size:13px;font-weight:600;padding:8px 14px;border:1px solid var(--line);border-radius:10px;background:#fff;cursor:pointer;box-shadow:var(--shadow);transition:transform .1s;}\n")
    fd.write(".btn:hover{transform:translateY(-1px);}\n")
    fd.write(".btn.primary{background:linear-gradient(135deg,var(--accent),var(--accent2));color:#fff;border-color:transparent;}\n")
    fd.write(".btn.sm{padding:5px 9px;font-size:12px;}\n")
    fd.write(".msg{font-size:12px;margin-left:6px;}\n")
    fd.write(".msg.ok{color:var(--ok);} .msg.err{color:var(--err);}\n")
    fd.write(".prov{border:1px solid var(--line);border-radius:12px;padding:10px 12px;margin-bottom:10px;}\n")
    fd.write(".prov h3{margin:0 0 6px;font-size:13.5px;display:flex;align-items:center;gap:8px;}\n")
    fd.write(".kv{display:grid;grid-template-columns:180px 1fr auto;gap:6px;margin:4px 0;align-items:center;}\n")
    fd.write(".kv input{font-size:12px;padding:5px 7px;}\n")
    fd.write(".kv .k{color:var(--muted);font-weight:600;}\n")
    fd.write(".muted{color:var(--faint);font-size:13px;}\n")
    fd.write(".hide{display:none;}\n")
    fd.write(".foot{color:var(--faint);font-size:11.5px;text-align:center;margin-top:18px;line-height:1.5;}\n")
    fd.write("a{color:var(--accent);}\n")
    fd.write("</style>\n")
    fd.write("</head>\n")

    # Write body content
    fd.write("<body>\n")
    fd.write("<div class=\"wrap\">\n")
    fd.write("  <div class=\"brand\"><div class=\"mark\"></div><h1 id=\"title\">Secret-Vault Public</h1></div>\n")
    fd.write("  <div class=\"sub\" id=\"sub\">Verschlüsselte Secret-Vault (AES-256-GCM, PBKDF2) — alles im Browser, kein Server.</div>\n")

    # Card: Open or new
    fd.write("\n")
    fd.write("  <div class=\"card\">\n")
    fd.write("    <h2 id=\"h-open\">Öffnen oder neu</h2>\n")
    fd.write("    <label class=\"lab\" id=\"l-pass\">Passphrase</label>\n")
    fd.write("    <input id=\"pass\" type=\"password\" placeholder=\"Passphrase…\">\n")
    fd.write("    <label class=\"lab\" id=\"l-file\">Vault laden (Datei oder Base64 einfügen)</label>\n")
    fd.write("    <input id=\"file\" type=\"file\" accept=\".svpb,.txt,.vault,.b64\">\n")
    fd.write("    <textarea id=\"blob\" placeholder=\"…oder Base64 hier einfügen\"></textarea>\n")
    fd.write("    <div class=\"row\" style=\"margin-top:10px\">\n")
    fd.write("      <button class=\"btn primary\" id=\"openBtn\">Öffnen / Entschlüsseln</button>\n")
    fd.write("      <button class=\"btn\" id=\"newBtn\">Neuer leerer Vault</button>\n")
    fd.write("      <span class=\"msg\" id=\"openMsg\"></span>\n")
    fd.write("    </div>\n")
    fd.write("  </div>\n")
    fd.write("\n")

    # Card: Editor (hidden by default)
    fd.write("  <div class=\"card hide\" id=\"editor\">\n")
    fd.write("    <h2 id=\"h-edit\">Inhalt</h2>\n")
    fd.write("    <div id=\"provs\"></div>\n")
    fd.write("    <div class=\"row\" style=\"margin-top:8px\">\n")
    fd.write("      <input id=\"newProv\" placeholder=\"Neuer Anbieter (Name)\" style=\"max-width:280px\">\n")
    fd.write("      <button class=\"btn sm\" id=\"addProvBtn\">+ Anbieter</button>\n")
    fd.write("    </div>\n")
    fd.write("  </div>\n")
    fd.write("\n")

    # Card: Save/Export (hidden by default)
    fd.write("  <div class=\"card hide\" id=\"out\">\n")
    fd.write("    <h2 id=\"h-save\">Speichern / Export</h2>\n")
    fd.write("    <div class=\"row\">\n")
    fd.write("      <button class=\"btn primary\" id=\"encBtn\">Verschlüsseln</button>\n")
    fd.write("      <button class=\"btn\" id=\"dlBtn\">Als .svpb herunterladen</button>\n")
    fd.write("      <button class=\"btn\" id=\"expBtn\">Klartext-JSON exportieren</button>\n")
    fd.write("      <span class=\"msg\" id=\"saveMsg\"></span>\n")
    fd.write("    </div>\n")
    fd.write("    <label class=\"lab\" id=\"l-result\">Ergebnis (zum Kopieren/Speichern)</label>\n")
    fd.write("    <textarea id=\"result\" readonly></textarea>\n")
    fd.write("  </div>\n")
    fd.write("\n")

    # Footer
    fd.write("  <div class=\"foot\" id=\"foot\"></div>\n")
    fd.write("</div>\n")

    # JavaScript section
    fd.write("<script>\n")
    fd.write("\n")
    fd.write("const L = ((navigator.language||\"en\").toLowerCase().startsWith(\"de\"))?\"de\":\"en\";\n")
    fd.write("const T = {\n")
    fd.write(" title:{de:\"Secret-Vault Public\",en:\"Secret-Vault Public\"},\n")
    fd.write(" sub:{de:\"Verschlüsselte Secret-Vault (AES-256-GCM, PBKDF2) — alles im Browser, kein Server.\",en:\"Encrypted secret vault (AES-256-GCM, PBKDF2) — fully in the browser, no server.\"},\n")
    fd.write(" hOpen:{de:\"Öffnen oder neu\",en:\"Open or new\"},\n")
    fd.write(" pass:{de:\"Passphrase\",en:\"Passphrase\"},\n")
    fd.write(" file:{de:\"Vault laden (Datei oder Base64 einfügen)\",en:\"Load vault (file or paste Base64)\"},\n")
    fd.write(" blob:{de:\"…oder Base64 hier einfügen\",en:\"…or paste Base64 here\"},\n")
    fd.write(" open:{de:\"Öffnen / Entschlüsseln\",en:\"Open / Decrypt\"},\n")
    fd.write(" neu:{de:\"Neuer leerer Vault\",en:\"New empty vault\"},\n")
    fd.write(" hEdit:{de:\"Inhalt\",en:\"Content\"},\n")
    fd.write(" newProv:{de:\"Neuer Anbieter (Name)\",en:\"New provider (name)\"},\n")
    fd.write(" addProv:{de:\"+ Anbieter\",en:\"+ Provider\"},\n")
    fd.write(" hSave:{de:\"Speichern / Export\",en:\"Save / Export\"},\n")
    fd.write(" enc:{de:\"Verschlüsseln\",en:\"Encrypt\"},\n")
    fd.write(" dl:{de:\"Als .svpb herunterladen\",en:\"Download as .svpb\"},\n")
    fd.write(" exp:{de:\"Klartext-JSON exportieren\",en:\"Export plaintext JSON\"},\n")
    fd.write(" result:{de:\"Ergebnis (zum Kopieren/Speichern)\",en:\"Result (to copy/save)\"},\n")
    fd.write(" foot:{de:\"Eigenes Format (PBKDF2). Nicht kompatibel mit dem scrypt-Python-Tool. Sicherheit liegt in der Passphrase; Inhalt ohne sie nicht wiederherstellbar.\",en:\"Own format (PBKDF2). Not compatible with the scrypt Python tool. Security rests on the passphrase; content is unrecoverable without it.\"},\n")
    fd.write(" needPass:{de:\"Passphrase eingeben.\",en:\"Enter a passphrase.\"},\n")
    fd.write(" noInput:{de:\"Datei laden oder Base64 einfügen.\",en:\"Load a file or paste Base64.\"},\n")
    fd.write(" bad:{de:\"Falsche Passphrase oder ungültiger Vault.\",en:\"Wrong passphrase or invalid vault.\"},\n")
    fd.write(" opened:{de:\"Geöffnet.\",en:\"Opened.\"},\n")
    fd.write(" created:{de:\"Neuer Vault angelegt.\",en:\"New vault created.\"},\n")
    fd.write(" encrypted:{de:\"Verschlüsselt — unten kopieren oder herunterladen.\",en:\"Encrypted — copy below or download.\"},\n")
    fd.write(" needOpen:{de:\"Erst öffnen/anlegen.\",en:\"Open/create first.\"},\n")
    fd.write(" field:{de:\"Feld\",en:\"field\"}, value:{de:\"Wert\",en:\"value\"},\n")
    fd.write(" addField:{de:\"+ Feld\",en:\"+ field\"}, del:{de:\"✕\",en:\"✕\"},\n")
    fd.write(" newField:{de:\"neues Feld\",en:\"new field\"}, newValue:{de:\"Wert\",en:\"value\"}\n")
    fd.write("};\n")
    fd.write("const tr=k=>T[k][L];\n")
    fd.write("// apply static i18n\n")
    fd.write("title.textContent=tr(\"title\"); sub.textContent=tr(\"sub\"); document.title=tr(\"title\");\n")
    fd.write("document.getElementById(\"h-open\").textContent=tr(\"hOpen\");\n")
    fd.write("document.getElementById(\"l-pass\").textContent=tr(\"pass\");\n")
    fd.write("document.getElementById(\"l-file\").textContent=tr(\"file\");\n")
    fd.write("blob.placeholder=tr(\"blob\");\n")
    fd.write("openBtn.textContent=tr(\"open\"); newBtn.textContent=tr(\"neu\");\n")
    fd.write("document.getElementById(\"h-edit\").textContent=tr(\"hEdit\");\n")
    fd.write("newProv.placeholder=tr(\"newProv\"); addProvBtn.textContent=tr(\"addProv\");\n")
    fd.write("document.getElementById(\"h-save\").textContent=tr(\"hSave\");\n")
    fd.write("encBtn.textContent=tr(\"enc\"); dlBtn.textContent=tr(\"dl\"); expBtn.textContent=tr(\"exp\");\n")
    fd.write("document.getElementById(\"l-result\").textContent=tr(\"result\");\n")
    fd.write("foot.textContent=tr(\"foot\");\n")
    fd.write("\n")
    fd.write("let VAULT=null; // {meta, providers:{}}\n")
    fd.write("\n")
    fd.write("const enc=new TextEncoder(), dec=new TextDecoder();\n")
    fd.write("function u8b64(u8){ let s=\"\"; for(let i=0;i<u8.length;i+=0x8000) s+=String.fromCharCode.apply(null,u8.subarray(i,i+0x8000)); return btoa(s); }\n")
    fd.write("function b64u8(b64){ const s=atob(b64.trim()); const u=new Uint8Array(s.length); for(let i=0;i<s.length;i++) u[i]=s.charCodeAt(i); return u; }\n")
    fd.write("async function deriveKey(pw,salt){\n")
    fd.write("  const km=await crypto.subtle.importKey(\"raw\",enc.encode(pw),\"PBKDF2\",false,[\"deriveKey\"]);\n")
    fd.write("  return crypto.subtle.deriveKey({name:\"PBKDF2\",salt,iterations:210000,hash:\"SHA-256\"},km,{name:\"AES-GCM\",length:256},false,[\"encrypt\",\"decrypt\"]);\n")
    fd.write("}\n")
    fd.write("async function encryptObj(obj,pw){\n")
    fd.write("  const salt=crypto.getRandomValues(new Uint8Array(16)), iv=crypto.getRandomValues(new Uint8Array(12));\n")
    fd.write("  const key=await deriveKey(pw,salt);\n")
    fd.write("  const ct=new Uint8Array(await crypto.subtle.encrypt({name:\"AES-GCM\",iv},key,enc.encode(JSON.stringify(obj,null,2))));\n")
    fd.write("  const magic=enc.encode(\"SVPB1\"); const out=new Uint8Array(5+16+12+ct.length);\n")
    fd.write("  out.set(magic,0); out.set(salt,5); out.set(iv,21); out.set(ct,33); return u8b64(out);\n")
    fd.write("}\n")
    fd.write("async function decryptB64(b64,pw){\n")
    fd.write("  const raw=b64u8(b64); if(dec.decode(raw.slice(0,5))!==\"SVPB1\") throw new Error(\"magic\");\n")
    fd.write("  const key=await deriveKey(pw,raw.slice(5,21));\n")
    fd.write("  const pt=await crypto.subtle.decrypt({name:\"AES-GCM\",iv:raw.slice(21,33)},key,raw.slice(33));\n")
    fd.write("  return JSON.parse(dec.decode(pt));\n")
    fd.write("}\n")
    fd.write("function esc(s){return (s==null?\"\":String(s)).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));}\n")
    fd.write("\n")
    fd.write("function renderEditor(){\n")
    fd.write("  document.getElementById(\"editor\").classList.remove(\"hide\");\n")
    fd.write("  document.getElementById(\"out\").classList.remove(\"hide\");\n")
    fd.write("  const P=VAULT.providers||{}; const root=document.getElementById(\"provs\"); root.innerHTML=\"\";\n")
    fd.write("  Object.keys(P).forEach(name=>{\n")
    fd.write("    const d=document.createElement(\"div\"); d.className=\"prov\";\n")
    fd.write("    let rows=\"\";\n")
    fd.write("    Object.keys(P[name]).forEach(k=>{ rows+=`<div class=\"kv\"><span class=\"k\">${esc(k)}</span><input data-p=\"${esc(name)}\" data-k=\"${esc(k)}\" value=\"${esc(P[name][k])}\"><button class=\"btn sm\" data-del=\"${esc(name)}|${esc(k)}\">${tr(\"del\")}</button></div>`; });\n")
    fd.write("    d.innerHTML=`<h3>${esc(name)} <button class=\"btn sm\" data-delp=\"${esc(name)}\">${tr(\"del\")}</button></h3>${rows}\n")
    fd.write("      <div class=\"row\" style=\"margin-top:6px\"><input class=\"nf\" data-np=\"${esc(name)}\" placeholder=\"${tr(\"newField\")}\" style=\"max-width:180px\"><input class=\"nv\" data-np=\"${esc(name)}\" placeholder=\"${tr(\"newValue\")}\" style=\"max-width:260px\"><button class=\"btn sm\" data-addf=\"${esc(name)}\">${tr(\"addField\")}</button></div>`;\n")
    fd.write("    root.appendChild(d);\n")
    fd.write("  });\n")
    fd.write("  root.querySelectorAll(\"input[data-k]\").forEach(i=>i.onchange=()=>{ VAULT.providers[i.dataset.p][i.dataset.k]=i.value; });\n")
    fd.write("  root.querySelectorAll(\"button[data-del]\").forEach(b=>b.onclick=()=>{ const [p,k]=b.dataset.del.split(\"|\"); delete VAULT.providers[p][k]; renderEditor(); });\n")
    fd.write("  root.querySelectorAll(\"button[data-delp]\").forEach(b=>b.onclick=()=>{ delete VAULT.providers[b.dataset.delp]; renderEditor(); });\n")
    fd.write("  root.querySelectorAll(\"button[data-addf]\").forEach(b=>b.onclick=()=>{ const p=b.dataset.addf; const nf=root.querySelector(`.nf[data-np=\"${CSS.escape(p)}\"]`).value.trim(); const nv=root.querySelector(`.nv[data-np=\"${CSS.escape(p)}\"]`).value; if(nf){ VAULT.providers[p][nf]=nv; renderEditor(); } });\n")
    fd.write("}\n")
    fd.write("\n")
    fd.write("document.getElementById(\"file\").onchange=e=>{ const f=e.target.files[0]; if(!f)return; const r=new FileReader(); r.onload=()=>{ blob.value=r.result.trim(); }; r.readAsText(f); };\n")
    fd.write("openBtn.onclick=async()=>{\n")
    fd.write("  const m=document.getElementById(\"openMsg\"); m.className=\"msg\"; m.textContent=\"\";\n")
    fd.write("  if(!pass.value){ m.className=\"msg err\"; m.textContent=tr(\"needPass\"); return; }\n")
    fd.write("  if(!blob.value.trim()){ m.className=\"msg err\"; m.textContent=tr(\"noInput\"); return; }\n")
    fd.write("  try{ VAULT=await decryptB64(blob.value,pass.value); if(!VAULT.providers)VAULT.providers={}; renderEditor(); m.className=\"msg ok\"; m.textContent=tr(\"opened\"); }\n")
    fd.write("  catch(err){ m.className=\"msg err\"; m.textContent=tr(\"bad\"); }\n")
    fd.write("};\n")
    fd.write("newBtn.onclick=()=>{\n")
    fd.write("  const m=document.getElementById(\"openMsg\");\n")
    fd.write("  if(!pass.value){ m.className=\"msg err\"; m.textContent=tr(\"needPass\"); return; }\n")
    fd.write("  VAULT={meta:{created:new Date().toISOString().slice(0,10),format:\"SVPB1\"},providers:{}}; renderEditor();\n")
    fd.write("  m.className=\"msg ok\"; m.textContent=tr(\"created\");\n")
    fd.write("};\n")
    fd.write("addProvBtn.onclick=()=>{ if(!VAULT){ return; } const n=newProv.value.trim(); if(n){ VAULT.providers[n]=VAULT.providers[n]||{}; newProv.value=\"\"; renderEditor(); } };\n")
    fd.write("encBtn.onclick=async()=>{\n")
    fd.write("  const m=document.getElementById(\"saveMsg\"); m.className=\"msg\";\n")
    fd.write("  if(!VAULT){ m.className=\"msg err\"; m.textContent=tr(\"needOpen\"); return; }\n")
    fd.write("  if(!pass.value){ m.className=\"msg err\"; m.textContent=tr(\"needPass\"); return; }\n")
    fd.write("  result.value=await encryptObj(VAULT,pass.value); m.className=\"msg ok\"; m.textContent=tr(\"encrypted\");\n")
    fd.write("};\n")
    fd.write("dlBtn.onclick=()=>{ if(!result.value)return; try{ const b=new Blob([result.value],{type:\"text/plain\"}); const u=URL.createObjectURL(b); const a=document.createElement(\"a\"); a.href=u; a.download=\"vault.svpb\"; document.body.appendChild(a); a.click(); a.remove(); setTimeout(()=>URL.revokeObjectURL(u),1500);}catch(e){} };\n")
    fd.write("expBtn.onclick=()=>{ if(!VAULT)return; result.value=JSON.stringify(VAULT,null,2); };\n")
    fd.write("\n")
    fd.write("</script>\n")
    fd.write("</body>\n")
    fd.write("</html>\n")

print("HTML file generated: " + outputFile)
