#!/usr/bin/env python3
# 1781743218784.tcl — portiert nach python
# Quelle: tcl, Projects@abstractions:tcl/1781743218784.tcl
# Erzeugt: 2026-08-08 durch ABSTRACTIONS_MANAGER.py

import sys
import json

def main():
    if len(sys.argv) != 2:
        print("Usage: {} output_file.html".format(sys.argv[0]))
        sys.exit(1)

    output_file = sys.argv[1]

    with open(output_file, 'w', encoding='utf-8') as fp:
        # Write DOCTYPE and main script tag
        fp.write('<!DOCTYPE html>\n')
        fp.write('<script type="application/json" id="cowork-artifact-meta">\n')
        fp.write('{\n')
        fp.write('  "name": "Secret Vault Public",\n')
        fp.write('  "schemaVersion": 1,\n')
        fp.write('  "description": "Secret-Vault Public als interaktives Browser-Artefakt: verschlüsselter Secret-Container vollständig client-seitig (WebCrypto, AES-256-GCM + PBKDF2). Öffnen/Anlegen, Anbieter/Felder ergänzen und ersetzen (Rotation), verschlüsseln und als .svpb herunterladen oder Klartext-JSON exportieren. DE/EN nach Browsersprache. Eigenes Format (nicht kompatibel mit dem scrypt-Python-Tool). Keine Secrets eingebettet.",\n')
        fp.write('  "mcpTools": [],\n')
        fp.write('  "mcpServerNames": []\n')
        fp.write('}\n')
        fp.write('</script>\n')

        # Write HTML start and head section
        fp.write('<html lang="de">\n')
        fp.write('<head>\n')
        fp.write('<meta charset="utf-8">\n')
        fp.write('<meta name="viewport" content="width=device-width, initial-scale=1">\n')
        fp.write('<title>Secret-Vault Public</title>\n')
        fp.write('<style>\n')
        fp.write(':root{ color-scheme:light; --ink:#1b1c1f; --muted:#6c6e75; --faint:#9a9ca3; --card:#fff; --line:#e9eaee; --accent:#5b5bd6; --accent2:#7c5cff; --ok:#22a06b; --err:#e0533d; --radius:16px; --shadow:0 1px 2px rgba(20,20,40,.04),0 6px 20px rgba(20,20,40,.06);}\n')
        fp.write('*{box-sizing:border-box;}\n')
        fp.write('body{margin:0;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;color:var(--ink);min-height:100vh;background:radial-gradient(1100px 560px at 100% -10%,#e8ecff 0%,rgba(232,236,255,0) 55%),linear-gradient(180deg,#eef1f6,#f7f7f8 42%);background-attachment:fixed;}\n')
        fp.write('.wrap{max-width:820px;margin:0 auto;padding:24px 18px 70px;}\n')
        fp.write('.brand{display:flex;align-items:center;gap:12px;margin-bottom:4px;}\n')
        fp.write('.mark{width:32px;height:32px;border-radius:9px;background:linear-gradient(135deg,var(--accent),var(--accent2));box-shadow:0 4px 12px rgba(91,91,214,.35);position:relative;flex:0 0 auto;}\n')
        fp.write('.mark:after{content:"";position:absolute;inset:8px;border-radius:4px;border:2px solid rgba(255,255,255,.92);}\n')
        fp.write('h1{font-size:21px;margin:0;font-weight:700;}\n')
        fp.write('.sub{color:var(--muted);font-size:13px;margin:2px 0 16px;}\n')
        fp.write('.card{background:var(--card);border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow);padding:16px;margin-bottom:14px;}\n')
        fp.write('.card h2{font-size:14px;margin:0 0 10px;}\n')
        fp.write('label.lab{display:block;font-size:12px;font-weight:600;color:var(--muted);margin:8px 0 3px;}\n')
        fp.write('input,textarea{width:100%;font-size:13px;padding:8px 10px;border:1px solid var(--line);border-radius:9px;font-family:ui-monospace,Menlo,Consolas,monospace;background:#fff;}\n')
        fp.write('textarea{min-height:90px;white-space:pre;overflow:auto;}\n')
        fp.write('.row{display:flex;gap:8px;flex-wrap:wrap;align-items:center;}\n')
        fp.write('.btn{font-size:13px;font-weight:600;padding:8px 14px;border:1px solid var(--line);border-radius:10px;background:#fff;cursor:pointer;box-shadow:var(--shadow);transition:transform .1s;}\n')
        fp.write('.btn:hover{transform:translateY(-1px);}\n')
        fp.write('.btn.primary{background:linear-gradient(135deg,var(--accent),var(--accent2));color:#fff;border-color:transparent;}\n')
        fp.write('.btn.sm{padding:5px 9px;font-size:12px;}\n')
        fp.write('.msg{font-size:12px;margin-left:6px;}\n')
        fp.write('.msg.ok{color:var(--ok);} .msg.err{color:var(--err);}\n')
        fp.write('.prov{border:1px solid var(--line);border-radius:12px;padding:10px 12px;margin-bottom:10px;}\n')
        fp.write('.prov h3{margin:0 0 6px;font-size:13.5px;display:flex;align-items:center;gap:8px;}\n')
        fp.write('.kv{display:grid;grid-template-columns:180px 1fr auto;gap:6px;margin:4px 0;align-items:center;}\n')
        fp.write('.kv input{font-size:12px;padding:5px 7px;}\n')
        fp.write('.kv .k{color:var(--muted);font-weight:600;}\n')
        fp.write('.muted{color:var(--faint);font-size:13px;}\n')
        fp.write('.hide{display:none;}\n')
        fp.write('.foot{color:var(--faint);font-size:11.5px;text-align:center;margin-top:18px;line-height:1.5;}\n')
        fp.write('a{color:var(--accent);}\n')
        fp.write('</style>\n')
        fp.write('</head>\n')

        # Write body content
        fp.write('<body>\n')
        fp.write('<div class="wrap">\n')
        fp.write('  <div class="brand"><div class="mark"></div><h1 id="title">Secret-Vault Public</h1></div>\n')
        fp.write('  <div class="sub" id="sub">Verschlüsselte Secret-Vault (AES-256-GCM, PBKDF2) — alles im Browser, kein Server.</div>\n')

        # Card: Open or new
        fp.write('  <div class="card">\n')
        fp.write('    <h2 id="h-open">Öffnen oder neu</h2>\n')
        fp.write('    <label class="lab" id="l-pass">Passphrase</label>\n')
        fp.write('    <input id="pass" type="password" placeholder="Passphrase…">\n')
        fp.write('    <label class="lab" id="l-file">Vault laden (Datei oder Base64 einfügen)</label>\n')
        fp.write('    <input id="file" type="file" accept=".svpb,.txt,.vault,.b64">\n')
        fp.write('    <textarea id="blob" placeholder="…oder Base64 hier einfügen"></textarea>\n')
        fp.write('    <div class="row" style="margin-top:10px">\n')
        fp.write('      <button class="btn primary" id="openBtn">Öffnen / Entschlüsseln</button>\n')
        fp.write('      <button class="btn" id="newBtn">Neuer leerer Vault</button>\n')
        fp.write('      <span class="msg" id="openMsg"></span>\n')
        fp.write('    </div>\n')
        fp.write('  </div>\n')

        # Card: Editor (hidden by default)
        fp.write('  <div class="card hide" id="editor">\n')
        fp.write('    <h2 id="h-edit">Inhalt</h2>\n')
        fp.write('    <div id="provs"></div>\n')
        fp.write('    <div class="row" style="margin-top:8px">\n')
        fp.write('      <input id="newProv" placeholder="Neuer Anbieter (Name)" style="max-width:280px">\n')
        fp.write('      <button class="btn sm" id="addProvBtn">+ Anbieter</button>\n')
        fp.write('    </div>\n')
        fp.write('  </div>\n')

        # Card: Save/Export (hidden by default)
        fp.write('  <div class="card hide" id="out">\n')
        fp.write('    <h2 id="h-save">Speichern / Export</h2>\n')
        fp.write('    <div class="row">\n')
        fp.write('      <button class="btn primary" id="encBtn">Verschlüsseln</button>\n')
        fp.write('      <button class="btn" id="dlBtn">Als .svpb herunterladen</button>\n')
        fp.write('      <button class="btn" id="expBtn">Klartext-JSON exportieren</button>\n')
        fp.write('      <span class="msg" id="saveMsg"></span>\n')
        fp.write('    </div>\n')
        fp.write('    <label class="lab" id="l-result">Ergebnis (zum Kopieren/Speichern)</label>\n')
        fp.write('    <textarea id="result" readonly></textarea>\n')
        fp.write('  </div>\n')

        # Footer
        fp.write('  <div class="foot" id="foot"></div>\n')
        fp.write('</div>\n')

        # JavaScript section
        fp.write('<script>\n')
        fp.write('const L = ((navigator.language||"en").toLowerCase().startsWith("de"))?"de":"en";\n')
        fp.write('const T = {\n')
        fp.write(' title:{de:"Secret-Vault Public",en:"Secret-Vault Public"},\n')
        fp.write(' sub:{de:"Verschlüsselte Secret-Vault (AES-256-GCM, PBKDF2) — alles im Browser, kein Server.",en:"Encrypted secret vault (AES-256-GCM, PBKDF2) — fully in the browser, no server."},\n')
        fp.write(' hOpen:{de:"Öffnen oder neu",en:"Open or new"},\n')
        fp.write(' pass:{de:"Passphrase",en:"Passphrase"},\n')
        fp.write(' file:{de:"Vault laden (Datei oder Base64 einfügen)",en:"Load vault (file or paste Base64)"},\n')
        fp.write(' blob:{de:"…oder Base64 hier einfügen",en:"…or paste Base64 here"},\n')
        fp.write(' open:{de:"Öffnen / Entschlüsseln",en:"Open / Decrypt"},\n')
        fp.write(' neu:{de:"Neuer leerer Vault",en:"New empty vault"},\n')
        fp.write(' hEdit:{de:"Inhalt",en:"Content"},\n')
        fp.write(' newProv:{de:"Neuer Anbieter (Name)",en:"New provider (name)"},\n')
        fp.write(' addProv:{de:"+ Anbieter",en:"+ Provider"},\n')
        fp.write(' hSave:{de:"Speichern / Export",en:"Save / Export"},\n')
        fp.write(' enc:{de:"Verschlüsseln",en:"Encrypt"},\n')
        fp.write(' dl:{de:"Als .svpb herunterladen",en:"Download as .svpb"},\n')
        fp.write(' exp:{de:"Klartext-JSON exportieren",en:"Export plaintext JSON"},\n')
        fp.write(' result:{de:"Ergebnis (zum Kopieren/Speichern)",en:"Result (to copy/save)"},\n')
        fp.write(' foot:{de:"Eigenes Format (PBKDF2). Nicht kompatibel mit dem scrypt-Python-Tool. Sicherheit liegt in der Passphrase; Inhalt ohne sie nicht wiederherstellbar.",en:"Own format (PBKDF2). Not compatible with the scrypt Python tool. Security rests on the passphrase; content is unrecoverable without it."},\n')
        fp.write(' needPass:{de:"Passphrase eingeben.",en:"Enter a passphrase."},\n')
        fp.write(' noInput:{de:"Datei laden oder Base64 einfügen.",en:"Load a file or paste Base64."},\n')
        fp.write(' bad:{de:"Falsche Passphrase oder ungültiger Vault.",en:"Wrong passphrase or invalid vault."},\n')
        fp.write(' opened:{de:"Geöffnet.",en:"Opened."},\n')
        fp.write(' created:{de:"Neuer Vault angelegt.",en:"New vault created."},\n')
        fp.write(' encrypted:{de:"Verschlüsselt — unten kopieren oder herunterladen.",en:"Encrypted — copy below or download."},\n')
        fp.write(' needOpen:{de:"Erst öffnen/anlegen.",en:"Open/create first."},\n')
        fp.write(' field:{de:"Feld",en:"field"}, value:{de:"Wert",en:"value"},\n')
        fp.write(' addField:{de:"+ Feld",en:"+ field"}, del:{de:"✕",en:"✕"},\n')
        fp.write(' newField:{de:"neues Feld",en:"new field"}, newValue:{de:"Wert",en:"value"}\n')
        fp.write('};\n')
        fp.write('const tr=k=>T[k][L];\n')
        fp.write('// apply static i18n\n')
        fp.write('title.textContent=tr("title"); sub.textContent=tr("sub"); document.title=tr("title");\n')
        fp.write('document.getElementById("h-open").textContent=tr("hOpen");\n')
        fp.write('document.getElementById("l-pass").textContent=tr("pass");\n')
        fp.write('document.getElementById("l-file").textContent=tr("file");\n')
        fp.write('blob.placeholder=tr("blob");\n')
        fp.write('openBtn.textContent=tr("open"); newBtn.textContent=tr("neu");\n')
        fp.write('document.getElementById("h-edit").textContent=tr("hEdit");\n')
        fp.write('newProv.placeholder=tr("newProv"); addProvBtn.textContent=tr("addProv");\n')
        fp.write('document.getElementById("h-save").textContent=tr("hSave");\n')
        fp.write('encBtn.textContent=tr("enc"); dlBtn.textContent=tr("dl"); expBtn.textContent=tr("exp");\n')
        fp.write('document.getElementById("l-result").textContent=tr("result");\n')
        fp.write('foot.textContent=tr("foot");\n')
        fp.write('\n')
        fp.write('let VAULT=null; // {meta, providers:{}}\n')
        fp.write('\n')
        fp.write('const enc=new TextEncoder(), dec=new TextDecoder();\n')
        fp.write('function u8b64(u8){ let s=""; for(let i=0;i<u8.length;i+=0x8000) s+=String.fromCharCode.apply(null,u8.subarray(i,i+0x8000)); return btoa(s); }\n')
        fp.write('function b64u8(b64){ const s=atob(b64.trim()); const u=new Uint8Array(s.length); for(let i=0;i<s.length;i++) u[i]=s.charCodeAt(i); return u; }\n')
        fp.write('async function deriveKey(pw,salt){\n')
        fp.write('  const km=await crypto.subtle.importKey("raw",enc.encode(pw),"PBKDF2",false,["deriveKey"]);\n')
        fp.write('  return crypto.subtle.deriveKey({name:"PBKDF2",salt,iterations:210000,hash:"SHA-256"},km,{name:"AES-GCM",length:256},false,["encrypt","decrypt"]);\n')
        fp.write('}\n')
        fp.write('async function encryptObj(obj,pw){\n')
        fp.write('  const salt=crypto.getRandomValues(new Uint8Array(16)), iv=crypto.getRandomValues(new Uint8Array(12));\n')
        fp.write('  const key=await deriveKey(pw,salt);\n')
        fp.write('  const ct=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv},key,enc.encode(JSON.stringify(obj,null,2))));\n')
        fp.write('  const magic=enc.encode("SVPB1"); const out=new Uint8Array(5+16+12+ct.length);\n')
        fp.write('  out.set(magic,0); out.set(salt,5); out.set(iv,21); out.set(ct,33); return u8b64(out);\n')
        fp.write('}\n')
        fp.write('async function decryptB64(b64,pw){\n')
        fp.write('  const raw=b64u8(b64); if(dec.decode(raw.slice(0,5))!=="SVPB1") throw new Error("magic");\n')
        fp.write('  const key=await deriveKey(pw,raw.slice(5,21));\n')
        fp.write('  const pt=await crypto.subtle.decrypt({name:"AES-GCM",iv:raw.slice(21,33)},key,raw.slice(33));\n')
        fp.write('  return JSON.parse(dec.decode(pt));\n')
        fp.write('}\n')
        fp.write('function esc(s){return (s==null?"":String(s)).replace(/[&<>"]/g,c=>({\'&\':\'&amp;\',\'<\':\'&lt;\',\'>\':\'&gt;\',\'"\':\'&quot;\'}[c]));}\n')
        fp.write('\n')
        fp.write('function renderEditor(){\n')
        fp.write('  document.getElementById("editor").classList.remove("hide");\n')
        fp.write('  document.getElementById("out").classList.remove("hide");\n')
        fp.write('  const P=VAULT.providers||{}; const root=document.getElementById("provs"); root.innerHTML="";\n')
        fp.write('  Object.keys(P).forEach(name=>{\n')
        fp.write('    const d=document.createElement("div"); d.className="prov";\n')
        fp.write('    let rows="";\n')
        fp.write('    Object.keys(P[name]).forEach(k=>{ rows+=`<div class="kv"><span class="k">${esc(k)}</span><input data-p="${esc(name)}" data-k="${esc(k)}" value="${esc(P[name][k])}"><button class="btn sm" data-del="${esc(name)}|${esc(k)}">${tr("del")}</button></div>`; });\n')
        fp.write('    d.innerHTML=`<h3>${esc(name)} <button class="btn sm" data-delp="${esc(name)}">${tr("del")}</button></h3>${rows}\n')
        fp.write('      <div class="row" style="margin-top:6px"><input class="nf" data-np="${esc(name)}" placeholder="${tr("newField")}" style="max-width:180px"><input class="nv" data-np="${esc(name)}" placeholder="${tr("newValue")}" style="max-width:260px"><button class="btn sm" data-addf="${esc(name)}">${tr("addField")}</button></div>`;\n')
        fp.write('    root.appendChild(d);\n')
        fp.write('  });\n')
        fp.write('  root.querySelectorAll("input[data-k]").forEach(i=>i.onchange=()=>{ VAULT.providers[i.dataset.p][i.dataset.k]=i.value; });\n')
        fp.write('  root.querySelectorAll("button[data-del]").forEach(b=>b.onclick=()=>{ const [p,k]=b.dataset.del.split("|"); delete VAULT.providers[p][k]; renderEditor(); });\n')
        fp.write('  root.querySelectorAll("button[data-delp]").forEach(b=>b.onclick=()=>{ delete VAULT.providers[b.dataset.delp]; renderEditor(); });\n')
        fp.write('  root.querySelectorAll("button[data-addf]").forEach(b=>b.onclick=()=>{ const p=b.dataset.addf; const nf=root.querySelector(`.nf[data-np="${CSS.escape(p)}"]`).value.trim(); const nv=root.querySelector(`.nv[data-np="${CSS.escape(p)}"]`).value; if(nf){ VAULT.providers[p][nf]=nv; renderEditor(); } });\n')
        fp.write('}\n')
        fp.write('\n')
        fp.write('document.getElementById("file").onchange=e=>{ const f=e.target.files[0]; if(!f)return; const r=new FileReader(); r.onload=()=>{ blob.value=r.result.trim(); }; r.readAsText(f); };\n')
        fp.write('openBtn.onclick=async()=>{\n')
        fp.write('  const m=document.getElementById("openMsg"); m.className="msg"; m.textContent="";\n')
        fp.write('  if(!pass.value){ m.className="msg err"; m.textContent=tr("needPass"); return; }\n')
        fp.write('  if(!blob.value.trim()){ m.className="msg err"; m.textContent=tr("noInput"); return; }\n')
        fp.write('  try{ VAULT=await decryptB64(blob.value,pass.value); if(!VAULT.providers)VAULT.providers={}; renderEditor(); m.className="msg ok"; m.textContent=tr("opened"); }\n')
        fp.write('  catch(err){ m.className="msg err"; m.textContent=tr("bad"); }\n')
        fp.write('};\n')
        fp.write('newBtn.onclick=()=>{\n')
        fp.write('  const m=document.getElementById("openMsg");\n')
        fp.write('  if(!pass.value){ m.className="msg err"; m.textContent=tr("needPass"); return; }\n')
        fp.write('  VAULT={meta:{created:new Date().toISOString().slice(0,10),format:"SVPB1"},providers:{}}; renderEditor();\n')
        fp.write('  m.className="msg ok"; m.textContent=tr("created");\n')
        fp.write('};\n')
        fp.write('addProvBtn.onclick=()=>{ if(!VAULT){ return; } const n=newProv.value.trim(); if(n){ VAULT.providers[n]=VAULT.providers[n]||{}; newProv.value=""; renderEditor(); } };\n')
        fp.write('encBtn.onclick=async()=>{\n')
        fp.write('  const m=document.getElementById("saveMsg"); m.className="msg";\n')
        fp.write('  if(!VAULT){ m.className="msg err"; m.textContent=tr("needOpen"); return; }\n')
        fp.write('  if(!pass.value){ m.className="msg err"; m.textContent=tr("needPass"); return; }\n')
        fp.write('  result.value=await encryptObj(VAULT,pass.value); m.className="msg ok"; m.textContent=tr("encrypted");\n')
        fp.write('};\n')
        fp.write('dlBtn.onclick=()=>{ if(!result.value)return; try{ const b=new Blob([result.value],{type:"text/plain"}); const u=URL.createObjectURL(b); const a=document.createElement("a"); a.href=u; a.download="vault.svpb"; document.body.appendChild(a); a.click(); a.remove(); setTimeout(()=>URL.revokeObjectURL(u),1500);}catch(e){} };\n')
        fp.write('expBtn.onclick=()=>{ if(!VAULT)return; result.value=JSON.stringify(VAULT,null,2); };\n')
        fp.write('</script>\n')
        fp.write('</body>\n')
        fp.write('</html>\n')

    print("HTML file generated: {}".format(output_file))

if __name__ == "__main__":
    main()
