#!/usr/bin/env python3
# 3d.tcl — portiert nach python
# Quelle: tcl, Projects@abstractions:tcl/3d.tcl
# Erzeugt: 2026-08-18 durch ABSTRACTIONS_MANAGER.py

# 3d.html — portiert nach tcl
# Quelle: html, Projects@secret-vault-public:public/3d.html
# Erzeugt: 2026-08-09 durch ABSTRACTIONS_MANAGER.py

# Python 3.12 script to generate 3d.html
# This script creates the HTML file programmatically, not as a string literal

import sys

def generate_html(filename):
    with open(filename, 'w') as f:
        # Write DOCTYPE and html tag
        f.write("<!DOCTYPE html>\n")
        f.write("<html lang=\"de\">\n")
        
        # Write head section
        write_head(f)
        
        # Write body section
        write_body(f)
        
        # Close html tag
        f.write("</html>\n")

def write_head(f):
    f.write("<head>\n")
    f.write("<meta charset=\"utf-8\">\n")
    f.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
    f.write("<title>Secret-Vault Public — Interaktive Architektur</title>\n")
    f.write("<meta name=\"description\" content=\"Vom Passwort zur verschlüsselten Datei — jede Schicht bleibt im Browser. Drehen, zoomen, Knoten auswählen.\">\n")
    f.write("<meta name=\"theme-color\" content=\"#5b5bd6\">\n")
    
    # Write CSS styles
    write_styles(f)
    
    f.write("</head>\n")

def write_styles(f):
    f.write("<style>\n")
    f.write("  :root{\n")
    f.write("    --bg:#fbfaf7; --panel:#fff; --line:#e6e3dc; --text:#16191d; --muted:#5f6773;\n")
    f.write("    --ac:#5b5bd6; --buehne:#0e1420; --buehne-line:#1d2739;\n")
    f.write("    color-scheme: light;\n")
    f.write("  }\n")
    f.write("  @media (prefers-color-scheme: dark){\n")
    f.write("    :root{ --bg:#0f1115; --panel:#171a21; --line:#262b36; --text:#f2f4f8; --muted:#9aa3b2;\n")
    f.write("           color-scheme: dark; }\n")
    f.write("  }\n")
    f.write("  *{box-sizing:border-box}\n")
    f.write("  body{margin:0;background:var(--bg);color:var(--text);\n")
    f.write("       font:15px/1.55 -apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,sans-serif}\n")
    f.write("  .wrap{max-width:1240px;margin:0 auto;padding:34px 22px 60px}\n")
    f.write("  .technik{font-size:12px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;\n")
    f.write("           color:var(--ac);margin:0 0 10px}\n")
    f.write("  h1{font-size:clamp(30px,5vw,52px);line-height:1.05;margin:0 0 14px;letter-spacing:-.03em}\n")
    f.write("  .lede{font-size:16.5px;color:var(--muted);max-width:62ch;margin:0 0 26px}\n")
    f.write("  .raster{display:grid;grid-template-columns:minmax(0,1fr) 288px;gap:18px;align-items:start}\n")
    f.write("  @media (max-width:880px){ .raster{grid-template-columns:1fr} }\n")
    f.write("  .buehne{position:relative;background:var(--buehne);border-radius:14px;overflow:hidden;\n")
    f.write("          min-height:520px;aspect-ratio:16/11}\n")
    f.write("  .buehne canvas{display:block;width:100%;height:100%}\n")
    f.write("  .knoepfe{position:absolute;top:14px;right:14px;display:flex;gap:8px;z-index:2}\n")
    f.write("  button{font:inherit;font-size:14px;font-weight:650;padding:9px 14px;border-radius:9px;\n")
    f.write("         border:1px solid var(--line);background:var(--panel);color:var(--text);cursor:pointer}\n")
    f.write("  button:hover{border-color:var(--ac)}\n")
    f.write("  button[aria-pressed=\"true\"]{background:var(--ac);border-color:var(--ac);color:#fff}\n")
    f.write("  .karte{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:20px}\n")
    f.write("  .karte h2{font-size:11px;font-weight:700;letter-spacing:.09em;text-transform:uppercase;\n")
    f.write("            color:var(--muted);margin:0 0 12px}\n")
    f.write("  .karte h3{font-size:23px;margin:0 0 4px;letter-spacing:-.02em}\n")
    f.write("  .karte .sub{color:var(--muted);margin:0 0 18px;font-size:14.5px}\n")
    f.write("  .feld{border-top:1px solid var(--line);padding:12px 0 0;margin:0 0 12px}\n")
    f.write("  .feld dt{font-size:11px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;\n")
    f.write("           color:var(--muted);margin:0 0 3px}\n")
    f.write("  .feld dd{margin:0;font-weight:650}\n")
    f.write("  .blaettern{display:flex;gap:8px;margin-top:16px}\n")
    f.write("  .blaettern button{flex:1;text-align:center;line-height:1.25;padding:11px 8px}\n")
    f.write("  .legende{display:flex;gap:22px;flex-wrap:wrap;margin:16px 0 0;font-size:13.5px;color:var(--muted)}\n")
    f.write("  .legende span{display:inline-flex;align-items:center;gap:9px}\n")
    f.write("  .strich{width:30px;height:0;border-top-width:3px;border-top-style:solid;display:inline-block}\n")
    f.write("  .fuss{margin:14px 0 0;font-size:13px;color:var(--muted);max-width:80ch}\n")
    f.write("  .fehler{padding:40px;text-align:center;color:var(--muted)}\n")
    f.write("  a{color:var(--ac)}\n")
    f.write("</style>\n")

def write_body(f):
    f.write("<body>\n")
    f.write("<div class=\"wrap\">\n")
    
    f.write("\n")
    f.write("  <p class=\"technik\">three.js · r128</p>\n")
    f.write("  <h1>Secret-Vault Public</h1>\n")
    f.write("  <p class=\"lede\">Vom Passwort zur verschlüsselten Datei — jede Schicht bleibt im Browser. Drehen, zoomen, Knoten auswählen.</p>\n")
    f.write("\n")
    f.write("  <div class=\"raster\">\n")
    f.write("    <div class=\"buehne\" id=\"buehne\">\n")
    f.write("      <div class=\"knoepfe\">\n")
    f.write("        <button id=\"btn-plus\" title=\"Näher\">+</button>\n")
    f.write("        <button id=\"btn-minus\" title=\"Weiter weg\">−</button>\n")
    f.write("        <button id=\"btn-reset\">Zurücksetzen</button>\n")
    f.write("        <button id=\"btn-iso\" aria-pressed=\"true\" title=\"Isometrisch oder perspektivisch\">Iso</button>\n")
    f.write("      </div>\n")
    f.write("    </div>\n")
    f.write("\n")
    f.write("    <aside class=\"karte\">\n")
    f.write("      <h2>Ausgewählter Knoten</h2>\n")
    f.write("      <h3 id=\"k-name\">—</h3>\n")
    f.write("      <p class=\"sub\" id=\"k-sub\">Knoten anklicken oder durchblättern</p>\n")
    f.write("      <dl class=\"feld\"><dt>Schicht</dt><dd id=\"k-schicht\">—</dd></dl>\n")
    f.write("      <dl class=\"feld\"><dt>ID</dt><dd id=\"k-id\">—</dd></dl>\n")
    f.write("      <div class=\"blaettern\">\n")
    f.write("        <button id=\"btn-prev\">←<br>Vorheriger</button>\n")
    f.write("        <button id=\"btn-next\">Nächster<br>→</button>\n")
    f.write("      </div>\n")
    f.write("    </aside>\n")
    f.write("  </div>\n")
    f.write("\n")
    f.write("  <div class=\"legende\" id=\"legende\"></div>\n")
    f.write("  <p class=\"fuss\">Schematische Dokumentationsansicht — Blockgrößen messen weder Datenmenge noch Leistung. Keine Telemetrie, keine Fernabfragen: Die Seite lädt einmalig three.js vom CDN und rechnet danach ausschließlich lokal.</p>\n")
    f.write("\n")
    f.write("</div>\n")
    
    # Write script tags
    write_scripts(f)
    
    f.write("</body>\n")

def write_scripts(f):
    f.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js\"></script>\n")
    f.write("<script>\n")
    f.write("(function(){\n")
    f.write("  \"use strict\";\n")
    f.write("  var SPEC = {\"schichten\": [{\"name\": \"Eingaben\", \"farbe\": \"#5f6773\", \"blocks\": [{\"id\": \"passphrase\", \"name\": \"Passphrase\", \"untertitel\": \"nie gespeichert\"}, {\"id\": \"vault-datei\", \"name\": \"Vault-Datei\", \"untertitel\": \"Ciphertext\"}, {\"id\": \"neue-felder\", \"name\": \"neue Felder\", \"untertitel\": \"Formular\"}]}, {\"name\": \"Schluesselableitung\", \"farbe\": \"#2481cc\", \"blocks\": [{\"id\": \"pbkdf2-210k\", \"name\": \"PBKDF2 210k\", \"untertitel\": \"Iterationen\"}, {\"id\": \"salt-16-b\", \"name\": \"Salt 16 B\", \"untertitel\": \"zufaellig\"}, {\"id\": \"sha-256\", \"name\": \"SHA-256\", \"untertitel\": \"HMAC\"}]}, {\"name\": \"Verschluesselung\", \"farbe\": \"#5b5bd6\", \"blocks\": [{\"id\": \"aes-256-gcm\", \"name\": \"AES-256-GCM\", \"untertitel\": \"authentisiert\"}, {\"id\": \"iv-12-b\", \"name\": \"IV 12 B\", \"untertitel\": \"nie doppelt\"}, {\"id\": \"crypto-subtle\", \"name\": \"crypto.subtle\", \"untertitel\": \"WebCrypto\"}]}, {\"name\": \"Verwaltung\", \"farbe\": \"#b45309\", \"blocks\": [{\"id\": \"anbieter\", \"name\": \"Anbieter\", \"untertitel\": \"Gruppen\"}, {\"id\": \"felder\", \"name\": \"Felder\", \"untertitel\": \"Schluessel/Wert\"}, {\"id\": \"rotation\", \"name\": \"Rotation\", \"untertitel\": \"neuer Wert\"}]}, {\"name\": \"Ausgabe\", \"farbe\": \"#22a06b\", \"blocks\": [{\"id\": \"download\", \"name\": \"Download\", \"untertitel\": \"Blob-URL\"}, {\"id\": \"export\", \"name\": \"Export\", \"untertitel\": \"JSON\"}, {\"id\": \"zwischenablage\", \"name\": \"Zwischenablage\", \"untertitel\": \"nur auf Klick\"}]}], \"kanten\": [{\"von\": \"passphrase\", \"nach\": \"pbkdf2-210k\", \"art\": \"fluss\"}, {\"von\": \"vault-datei\", \"nach\": \"salt-16-b\", \"art\": \"fluss\"}, {\"von\": \"neue-felder\", \"nach\": \"sha-256\", \"art\": \"fluss\"}, {\"von\": \"pbkdf2-210k\", \"nach\": \"aes-256-gcm\", \"art\": \"fluss\"}, {\"von\": \"salt-16-b\", \"nach\": \"iv-12-b\", \"art\": \"fluss\"}, {\"von\": \"sha-256\", \"nach\": \"crypto-subtle\", \"art\": \"fluss\"}, {\"von\": \"aes-256-gcm\", \"nach\": \"anbieter\", \"art\": \"fluss\"}, {\"von\": \"iv-12-b\", \"nach\": \"felder\", \"art\": \"fluss\"}, {\"von\": \"crypto-subtle\", \"nach\": \"rotation\", \"art\": \"fluss\"}, {\"von\": \"anbieter\", \"nach\": \"download\", \"art\": \"fluss\"}, {\"von\": \"felder\", \"nach\": \"export\", \"art\": \"fluss\"}, {\"von\": \"rotation\", \"nach\": \"zwischenablage\", \"art\": \"fluss\"}], \"kantenarten\": [{\"art\": \"fluss\", \"farbe\": \"#5b5bd6\", \"stil\": \"voll\", \"text\": \"Fluss von unten nach oben\"}]};\n")
    f.write("\n")
    f.write("  var buehne = document.getElementById(\"buehne\");\n")
    f.write("  if (typeof THREE === \"undefined\"){\n")
    f.write("    buehne.insertAdjacentHTML(\"beforeend\",\n")
    f.write("      '<div class=\"fehler\">three.js konnte nicht geladen werden. ' +\n")
    f.write("      'Die Seite braucht einmalig Netzzugang zum CDN.</div>');\n")
    f.write("    return;\n")
    f.write("  }\n")
    f.write("\n")
    f.write("  // ---------------------------------------------------------------- Szene ---\n")
    f.write("  var szene = new THREE.Scene();\n")
    f.write("  szene.background = new THREE.Color(0x0e1420);\n")
    f.write("  var renderer = new THREE.WebGLRenderer({antialias:true});\n")
    f.write("  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));\n")
    f.write("  buehne.appendChild(renderer.domElement);\n")
    f.write("\n")
    f.write("  var D = 26, radius = 82, aspekt = 1;\n")
    f.write("  var kameraIso = new THREE.OrthographicCamera(-D, D, D, -D, 0.1, 600);\n")
    f.write("  var kameraPersp = new THREE.PerspectiveCamera(42, 1, 0.1, 600);\n")
    f.write("  var kamera = kameraIso, iso = true;\n")
    f.write("\n")
    f.write("  szene.add(new THREE.AmbientLight(0xffffff, 0.66));\n")
    f.write("  var licht = new THREE.DirectionalLight(0xffffff, 0.8);\n")
    f.write("  licht.position.set(30, 46, 26); szene.add(licht);\n")
    f.write("  var gegen = new THREE.DirectionalLight(0x8ea2ff, 0.3);\n")
    f.write("  gegen.position.set(-32, 16, -28); szene.add(gegen);\n")
    f.write("\n")
    f.write("  var raster = new THREE.GridHelper(110, 34, 0x25324a, 0x1a2333);\n")
    f.write("  raster.position.y = -24; szene.add(raster);\n")
    f.write("\n")
    f.write("  // ------------------------------------------------------------ Schilder ---\n")
    f.write("  // Text auf eine Textur, dann als Billboard — bleibt bei jeder Drehung lesbar.\n")
    f.write("  function schild(text, unter){\n")
    f.write("    var c = document.createElement(\"canvas\"), x = c.getContext(\"2d\");\n")
    f.write("    var f1 = \"700 40px -apple-system,Segoe UI,Roboto,sans-serif\";\n")
    f.write("    var f2 = \"500 27px -apple-system,Segoe UI,Roboto,sans-serif\";\n")
    f.write("    x.font = f1; var w1 = x.measureText(text).width;\n")
    f.write("    x.font = f2; var w2 = unter ? x.measureText(unter).width : 0;\n")
    f.write("    var w = Math.ceil(Math.max(w1, w2)) + 40, h = unter ? 96 : 62;\n")
    f.write("    c.width = w; c.height = h;\n")
    f.write("    x = c.getContext(\"2d\");\n")
    f.write("    x.fillStyle = \"rgba(255,255,255,.95)\";\n")
    f.write("    if (x.roundRect){ x.beginPath(); x.roundRect(0,0,w,h,13); x.fill(); }\n")
    f.write("    else x.fillRect(0,0,w,h);\n")
    f.write("    x.fillStyle = \"#16191d\"; x.font = f1; x.textBaseline = \"middle\";\n")
    f.write("    x.fillText(text, 20, unter ? 32 : 31);\n")
    f.write("    if (unter){ x.fillStyle = \"#5f6773\"; x.font = f2; x.fillText(unter, 20, 68); }\n")
    f.write("    var t = new THREE.CanvasTexture(c); t.minFilter = THREE.LinearFilter;\n")
    f.write("    var s = new THREE.Sprite(new THREE.SpriteMaterial({map:t, transparent:true, depthTest:false}));\n")
    f.write("    s.scale.set(w/62*2.5, h/62*2.5, 1);\n")
    f.write("    s.renderOrder = 999;\n")
    f.write("    return s;\n")
    f.write("  }\n")
    f.write("\n")
    f.write("  // -------------------------------------------------------------- Aufbau ---\n")
    f.write("  var BW = 7.4, BD = 4.2, BH = 1.7, LUFT = 1.3, ABSTAND = 11.4, START = -17;\n")
    f.write("  var knoten = [], nachId = {}, klickbar = [];\n")
    f.write("  var gruppe = new THREE.Group();\n")
    f.write("\n")
    f.write("  SPEC.schichten.forEach(function(sch, si){\n")
    f.write("    var y = START + si * ABSTAND;\n")
    f.write("    var bl = sch.blocks.map(function(b){\n")
    f.write("      return (typeof b === \"string\") ? {id:null, name:b, untertitel:\"\"} : b;\n")
    f.write("    });\n")
    f.write("    var spalten = Math.max(1, Math.ceil(bl.length / 2));\n")
    f.write("    var reihen = bl.length <= 1 ? 1 : 2;\n")
    f.write("    var gx = spalten*BW + (spalten-1)*LUFT, gz = reihen*BD + (reihen-1)*LUFT;\n")
    f.write("\n")
    f.write("    var platte = new THREE.Mesh(\n")
    f.write("      new THREE.BoxGeometry(gx+3, 0.6, gz+3),\n")
    f.write("      new THREE.MeshLambertMaterial({color:new THREE.Color(sch.farbe).multiplyScalar(0.4)}));\n")
    f.write("    platte.position.set(0, y-1.7, 0); gruppe.add(platte);\n")
    f.write("\n")
    f.write("    bl.forEach(function(b, i){\n")
    f.write("      var sp = i % spalten, re = Math.floor(i / spalten);\n")
    f.write("      var x = -gx/2 + BW/2 + sp*(BW+LUFT), z = -gz/2 + BD/2 + re*(BD+LUFT);\n")
    f.write("      var mat = new THREE.MeshLambertMaterial({color:sch.farbe});\n")
    f.write("      var m = new THREE.Mesh(new THREE.BoxGeometry(BW, BH, BD), mat);\n")
    f.write("      m.position.set(x, y, z);\n")
    f.write("      gruppe.add(m); klickbar.push(m);\n")
    f.write("      var kante = new THREE.LineSegments(new THREE.EdgesGeometry(m.geometry),\n")
    f.write("        new THREE.LineBasicMaterial({color:0x0e1420, transparent:true, opacity:.55}));\n")
    f.write("      kante.position.copy(m.position); gruppe.add(kante);\n")
    f.write("\n")
    f.write("      var s = schild(b.name, b.untertitel);\n")
    f.write("      s.position.set(x, y + BH/2 + (b.untertitel ? 2.1 : 1.6), z);\n")
    f.write("      gruppe.add(s);\n")
    f.write("\n")
    f.write("      var id = b.id || (b.name.toLowerCase().replace(/[^a-z0-9]+/g, \"-\").replace(/^-|-$\"g, \"\"));\n")
    f.write("      var eintrag = {id:id, name:b.name, untertitel:b.untertitel||\"\", schicht:sch.name,\n")
    f.write("                     mesh:m, mat:mat, farbe:new THREE.Color(sch.farbe), pos:m.position};\n")
    f.write("      m.userData.index = knoten.length;\n")
    f.write("      knoten.push(eintrag); nachId[id] = eintrag;\n")
    f.write("    });\n")
    f.write("  });\n")
    f.write("\n")
    f.write("  // -------------------------------------------------------------- Kanten ---\n")
    f.write("  var STIL = {};\n")
    f.write("  (SPEC.kantenarten || []).forEach(function(a){ STIL[a.art] = a; });\n")
    f.write("\n")
    f.write("  (SPEC.kanten || []).forEach(function(k){\n")
    f.write("    var a = nachId[k.von], b = nachId[k.nach];\n")
    f.write("    if (!a || !b) return;\n")
    f.write("    var art = STIL[k.art] || {farbe:\"#8ea2ff\", stil:\"voll\"};\n")
    f.write("    var g = new THREE.BufferGeometry().setFromPoints([\n")
    f.write("      a.pos.clone().setY(a.pos.y + 0.9), b.pos.clone().setY(b.pos.y - 0.9)]);\n")
    f.write("    var linie;\n")
    f.write("    if (art.stil === \"gestrichelt\"){\n")
    f.write("      linie = new THREE.Line(g, new THREE.LineDashedMaterial(\n")
    f.write("        {color:art.farbe, dashSize:1.4, gapSize:1.0, transparent:true, opacity:.9}));\n")
    f.write("      linie.computeLineDistances();\n")
    f.write("    } else {\n")
    f.write("      linie = new THREE.Line(g, new THREE.LineBasicMaterial(\n")
    f.write("        {color:art.farbe, transparent:true, opacity:.85}));\n")
    f.write("    }\n")
    f.write("    gruppe.add(linie);\n")
    f.write("  });\n")
    f.write("\n")
    f.write("  szene.add(gruppe);\n")
    f.write("\n")
    f.write("  var leg = document.getElementById(\"legende\");\n")
    f.write("  (SPEC.kantenarten || []).forEach(function(a){\n")
    f.write("    var s = document.createElement(\"span\");\n")
    f.write("    s.innerHTML = '<i class=\"strich\" style=\"border-top-color:' + a.farbe +\n")
    f.write("                  ';border-top-style:' + (a.stil === \"gestrichelt\" ? \"dashed\" : \"solid\") +\n")
    f.write("                  '\"></i>' + a.text;\n")
    f.write("    leg.appendChild(s);\n")
    f.write("  });\n")
    f.write("\n")
    f.write("  // ------------------------------------------------------------- Auswahl ---\n")
    f.write("  var aktiv = -1;\n")
    f.write("  function waehle(i){\n")
    f.write("    if (aktiv >= 0){\n")
    f.write("      knoten[aktiv].mat.color.copy(knoten[aktiv].farbe);\n")
    f.write("      knoten[aktiv].mat.emissive.setHex(0x000000);\n")
    f.write("      knoten[aktiv].mesh.scale.set(1,1,1);\n")
    f.write("    }\n")
    f.write("    aktiv = ((i % knoten.length) + knoten.length) % knoten.length;\n")
    f.write("    var k = knoten[aktiv];\n")
    f.write("    k.mat.emissive.setHex(0x333333);\n")
    f.write("    k.mesh.scale.set(1.1, 1.5, 1.1);\n")
    f.write("    document.getElementById(\"k-name\").textContent = k.name;\n")
    f.write("    document.getElementById(\"k-sub\").textContent = k.untertitel || \"—\";\n")
    f.write("    document.getElementById(\"k-schicht\").textContent = k.schicht;\n")
    f.write("    document.getElementById(\"k-id\").textContent = k.id;\n")
    f.write("  }\n")
    f.write("\n")
    f.write("  var strahl = new THREE.Raycaster(), zeiger = new THREE.Vector2();\n")
    f.write("  renderer.domElement.addEventListener(\"click\", function(e){\n")
    f.write("    if (gezogen) return;\n")
    f.write("    var r = renderer.domElement.getBoundingClientRect();\n")
    f.write("    zeiger.x = ((e.clientX - r.left) / r.width) * 2 - 1;\n")
    f.write("    zeiger.y = -((e.clientY - r.top) / r.height) * 2 + 1;\n")
    f.write("    strahl.setFromCamera(zeiger, kamera);\n")
    f.write("    var treffer = strahl.intersectObjects(klickbar, false);\n")
    f.write("    if (treffer.length) waehle(treffer[0].object.userData.index);\n")
    f.write("  });\n")
    f.write("  document.getElementById(\"btn-prev\").addEventListener(\"click\", function(){ waehle(aktiv - 1); });\n")
    f.write("  document.getElementById(\"btn-next\").addEventListener(\"click\", function(){ waehle(aktiv + 1); });\n")
    f.write("\n")
    f.write("  // ------------------------------------------------------------- Kamera ----\n")
    f.write("  var azimut = Math.PI/4, elevation = 0.62, rotiert = true;\n")
    f.write("  function stelle(){\n")
    f.write("    var x = radius*Math.cos(elevation)*Math.sin(azimut);\n")
    f.write("    var y = radius*Math.sin(elevation);\n")
    f.write("    var z = radius*Math.cos(elevation)*Math.cos(azimut);\n")
    f.write("    kamera.position.set(x, y, z); kamera.lookAt(0, 0, 0);\n")
    f.write("  }\n")
    f.write("  var zieht = false, gezogen = false, lx = 0, ly = 0;\n")
    f.write("  renderer.domElement.addEventListener(\"pointerdown\", function(e){\n")
    f.write("    zieht = true; gezogen = false; lx = e.clientX; ly = e.clientY;\n")
    f.write("  });\n")
    f.write("  window.addEventListener(\"pointermove\", function(e){\n")
    f.write("    if (!zieht) return;\n")
    f.write("    if (Math.abs(e.clientX-lx) + Math.abs(e.clientY-ly) > 3){ gezogen = true; rotiert = false; }\n")
    f.write("    azimut -= (e.clientX - lx) * 0.006;\n")
    f.write("    elevation = Math.max(0.08, Math.min(1.45, elevation + (e.clientY - ly) * 0.005));\n")
    f.write("    lx = e.clientX; ly = e.clientY;\n")
    f.write("  });\n")
    f.write("  window.addEventListener(\"pointerup\", function(){ zieht = false; setTimeout(function(){ gezogen = false; }, 0); });\n")
    f.write("\n")
    f.write("  function zoom(f){\n")
    f.write("    if (iso){ D = Math.max(11, Math.min(54, D * f)); groesse(); }\n")
    f.write("    else { radius = Math.max(32, Math.min(160, radius * f)); }\n")
    f.write("  }\n")
    f.write("  document.getElementById(\"btn-plus\").addEventListener(\"click\", function(){ zoom(0.85); });\n")
    f.write("  document.getElementById(\"btn-minus\").addEventListener(\"click\", function(){ zoom(1.18); });\n")
    f.write("  renderer.domElement.addEventListener(\"wheel\", function(e){\n")
    f.write("    e.preventDefault(); zoom(e.deltaY > 0 ? 1.08 : 0.93);\n")
    f.write("  }, {passive:false});\n")
    f.write("  document.getElementById(\"btn-reset\").addEventListener(\"click\", function(){\n")
    f.write("    azimut = Math.PI/4; elevation = 0.62; D = 26; radius = 82; rotiert = true;\n")
    f.write("    iso = true; kamera = kameraIso;\n")
    f.write("    document.getElementById(\"btn-iso\").setAttribute(\"aria-pressed\", \"true\");\n")
    f.write("    document.getElementById(\"btn-iso\").textContent = \"Iso\";\n")
    f.write("    waehle(0); groesse();\n")
    f.write("  });\n")
    f.write("  document.getElementById(\"btn-iso\").addEventListener(\"click\", function(){\n")
    f.write("    iso = !iso; kamera = iso ? kameraIso : kameraPersp;\n")
    f.write("    this.setAttribute(\"aria-pressed\", String(iso));\n")
    f.write("    this.textContent = iso ? \"Iso\" : \"Persp\";\n")
    f.write("    groesse();\n")
    f.write("  });\n")
    f.write("\n")
    f.write("  function groesse(){\n")
    f.write("    var w = buehne.clientWidth, h = buehne.clientHeight;\n")
    f.write("    aspekt = w / h;\n")
    f.write("    kameraIso.left = -D*aspekt; kameraIso.right = D*aspekt;\n")
    f.write("    kameraIso.top = D; kameraIso.bottom = -D; kameraIso.updateProjectionMatrix();\n")
    f.write("    kameraPersp.aspect = aspekt; kameraPersp.updateProjectionMatrix();\n")
    f.write("    renderer.setSize(w, h, false);\n")
    f.write("  }\n")
    f.write("  window.addEventListener(\"resize\", groesse);\n")
    f.write("\n")
    f.write("  groesse();\n")
    f.write("  waehle(0);\n")
    f.write("  (function schleife(){\n")
    f.write("    requestAnimationFrame(schleife);\n")
    f.write("    if (rotiert) azimut += 0.003;\n")
    f.write("    stelle();\n")
    f.write("    renderer.render(szene, kamera);\n")
    f.write("  })();\n")
    f.write("})();\n")
    f.write("</script>\n")

# Main execution
if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: {} <output-file>".format(sys.argv[0]))
        sys.exit(1)

    output_file = sys.argv[1]
    generate_html(output_file)
    print("Generated {}".format(output_file))
